### ISSUE TITLE
Remove moviepy

### ISSUE THREAD

**Issue by adw0rd** [adw0rd/instagrapi#1]
To simplify the library, take it out as an example in a separate file

**Comment by adw0rd** [comment]
ashh, [22.12.20 21:23]
anyone seen this error before?

ashh, [22.12.20 21:23]
File "moviepy\editor.py", line 87, in <module>
  File "<string>", line 1, in <module>
AttributeError: module 'moviepy.audio.fx.all' has no attribute 'audio_fadein'

**Comment by trashmit** [comment]
Thanks :)

**Comment by trashmit** [comment]
My error is still occuring whenever moviepy is imported :(

**Comment by adw0rd** [comment]
@trashmit try updating moviepy to last version
Which function from instagrapi are you using (upload video, igtv or build story)? Where exactly do you get this error?
Send full traceback

**Comment by trashmit** [comment]
It's the same error as this.

https://github.com/Zulko/moviepy/issues/591

It seems like an error in moviepy, not one caused by instagrapi I think a solution to it would be importing the required classes from moviepy individually instead of just import moviepy

**Comment by adw0rd** [comment]
@trashmit expect a PR from you

**Comment by adw0rd** [comment]
The error is reproduced only for you, if you can fix it, then I can accept your code as PR and check with tests

**Comment by msr8** [comment]
Is there a way to disable the console output and/or delete the files created when using the `client.video_upload()` function?
