### ISSUE TITLE
Followers is capped at 50

### ISSUE THREAD

**Issue by nikilster** [adw0rd/instagrapi#1006]
How do you get the full list of followers? Tried on a user with 20k+ followers and got:
 user_followers (gave 50)
 user_followers_v1 (gave 48)

**Comment by adw0rd** [comment]
Hi Nikil again, everything works fine for me, it gives more than 50. Can you send part of your code and user_id for an example? You can by mail or https://telegram.me/m11k4

```
In [5]: f = cl.user_followers(29817608135, amount=100)

In [6]: len(f)
Out[6]: 100

In [7]: len(set(f.keys()))
Out[7]: 100
```

**Comment by hoflz5** [comment]
I think they are flagging your account after a while.
I get this when setting amount=0 or some high number (> 2000).
After a while my account is also blocked, and I'll have to unlock it in the the instagram app.
It is also different between accounts. Some accounts never get more than a few hundred.
They might also flag the IP number, not sure about this one.

**Comment by tonybustamante** [comment]
Any more feedback on this one. I am trying to pull my own followers and it is only returning the first 261. 

```user_id = cl.user_id_from_username('arainydayrescue')
followers = cl.user_followers(user_id, amount=2000)
user_info = cl.user_info_by_username('arainydayrescue')

print("Total Followers: ", user_info.follower_count)
print("Followers in list: ", len(followers))
print("done")```

Results
Total Followers: 1562
Followers in List: 261
