### ISSUE TITLE
cl.media_likers(media_id: str) return max 1k likers 

### ISSUE THREAD

**Issue by mikebgrep** [adw0rd/instagrapi#101]
I test it with posts with 4000 and 8k likers its allways return max 1k usernames

**Comment by adw0rd** [comment]
@mikebgrep Instagram always returns ~ 1000 likes, it is not possible to get any more (Instagram Private API restrictions)


```
>>> cl.media_likers('2574770999598123330_8530598273')
>>> cl.last_json
{
 'users': [<list of users>]
 'user_count': 6820,
 'status': 'ok'}
```
