### ISSUE TITLE
Change PFP Error Photo Upload failed with the following response: <Response [400]>

### ISSUE THREAD

**Issue by r1dddy4sv** [adw0rd/instagrapi#1025]
hey mate

trying to get "pics_insta/444.jpg" as pfp

with "cl.account_change_picture(pics_insta/444.jpg)"

and gets error: 

Photo Upload failed with the following response: <Response [400]>
PhotoNotUpload('{"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}')

**Comment by midjunkie** [comment]
same here, when I try to upload a photo to profile

```
photo_path = 'img1.png'
cl = Client()
cl.login(email, password)
media = cl.photo_upload(
    "img1.png",
    "Test caption for photo with #hashtags and mention users such @user"
)
```

got this on terminal
```
Photo Upload failed with the following response: <Response [400]>
Traceback (most recent call last):
...
line 192, in photo_rupload
    raise PhotoNotUpload(response.text, response=response, **last_json)    
instagrapi.exceptions.PhotoNotUpload: {"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}
```

**Comment by adw0rd** [comment]
try uploading the photo you downloaded from instagram, it works fine, then check what is wrong with your file
