### ISSUE TITLE
Ошбика SentryBlock  при авторизации

### ISSUE THREAD

**Issue by markdrrr** [adw0rd/instagrapi#103]
При попытки авторизоваться падает ошибка 
` instagrapi.exceptions.SentryBlock: Sorry, there was a problem with your request. ` 
Пробовал разные аккаунты на разных устройствах с разными ip...
Подскажите как решить ?

**Comment by markdrrr** [comment]
Иногда получается пройти успешную авторизацию раза с 20го) тогда я сохраняю словарь из `get_settings()`
и в дальнейшем подставляю данные для авторизации из него. Но все равно иногда слетает авторизация и при использовании этого же словаря настроек падает эта же ошибка

**Comment by markdrrr** [comment]
Мне кажется ошибка в каких то данных при генерации словаря для настроек девайса

**Comment by adw0rd** [comment]
@markdrrr возможно в инсте что-то поменяло за последнее время,  надо проверять в Charles, а его нет под рукой

**Comment by yusufusta** [comment]
Please use a universal language for everyone to understand. It's like English.

**Comment by Aryan-401** [comment]
Yes, after 5 minutes of Google Translating. I am also getting the same error as markdrrr

**Comment by adw0rd** [comment]
@Aryan-401 login fixed in instagrapi==1.5.1, if the SentryError stayed, then reset your device_id in the settings

**Comment by Aryan-401** [comment]
@adw0rd hey sorry i'm new to your module, can you please tell me the steps to reset my device_id in settings, , or what values i have to put inside the settings dict.

**Comment by italy** [comment]
@Aryan-401 just use a random uuid4 in the device id

**Comment by italy** [comment]
@Aryan-401 the device id is 'android-' + random string of 16 characters

**Comment by adw0rd** [comment]
@Aryan-401 In version 1.5.2, the generation of device_id has been improved, so you can not transfer settings
