### ISSUE TITLE
[BUG] error after a login

### ISSUE THREAD

**Issue by Yqno** [adw0rd/instagrapi#1040]
When i want to log in and type my account data and i get this error

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/instagrapi/mixins/private.py", line 302, in _send_private_request
    response.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/

i use Arch linux
python version 3.10.5
instagrapi version 1.16.30

**Comment by adw0rd** [comment]
I cannot reproduce it, try another proxy and another account. I will wait for your decision!

**Comment by Yqno** [comment]
It works with another Connection and account thanks, I guess Instagram temporary blocked the traffic from my Wi-Fi because of too much traffic
