### ISSUE TITLE
Is it possible to handle the limited Comments error?

### ISSUE THREAD

**Issue by Yqno** [adw0rd/instagrapi#1078]
i added the handle exception in my code and the only error i get is the Comments limited error, is it possible to handle the error so the bot didnt stop?

![image](https://user-images.githubusercontent.com/79216939/213937192-20b0e33d-18f0-4657-aac4-6710c391fbbb.png)

here a piece of Code 

    client = Client()
    client.handle_exception = handle_exception
    client.login(username, password)

   for i, media in enumerate(medias):
        try:
            client.media_like(media.id)
            print(Fore.BLUE + f"Liked post Number {i+1} of hashtag {hashtag}")
            if i % 5 == 0:
                client.user_follow(media.user.pk)
                print(Fore.RED + f"Followed user {media.user.username} ")
        except Exception as e:
            if e.status_code == 400 and "comments for this media are closed" in e.message:
                        print(Fore.CYAN + "comments for this media are closed.")
                        comment = random.choice(comments) 
                        client.media_comment(media.id, comment)
                        print(Fore.GREEN + f"Commented {comment} under post number {i+1} ")

except Exception as e:
    handle_exception(client, e)

**Comment by adw0rd** [comment]
Show your handle_exception function

**Comment by Yqno** [comment]
def handle_exception(self, client, e):

    if isinstance(e, BadPassword):
        client.logger.exception(e)
        client.set_proxy(self.next_proxy().href)
        if client.relogin_attempt > 0:
            self.freeze(str(e), days=7)
            raise ReloginAttemptExceeded(e)
        client.settings = self.rebuild_client_settings()
        return self.update_client_settings(client.get_settings())
    elif isinstance(e, ChallengeRequired):
        client.logger.exception(e)
        client.set_proxy(self.next_proxy().href)
        if client.relogin_attempt > 0:
            self.freeze(str(e), days=7)
            raise ReloginAttemptExceeded(e)
        client.settings = self.rebuild_client_settings()
        return self.update_client_settings(client.get_settings())
    elif isinstance(e, SelectContactPointRecoveryForm):
        client.logger.exception(e)
        client.set_proxy(self.next_proxy().href)
        if client.relogin_attempt > 0:
            self.freeze(str(e), days=7)
            raise ReloginAttemptExceeded(e)
        client.settings = self.rebuild_client_settings()
        return self.update_
    elif isinstance(e, RecaptchaChallengeForm):
        client.logger.exception(e)
        client.set_proxy(self.next_proxy().href)
        if client.relogin_attempt > 0:
            self.freeze(str(e), days=7)
            raise ReloginAttemptExceeded(e)
        client.settings = self.rebuild_client_settings()
        return self.update_client_settings(client.get_settings())
    elif isinstance(e, FeedbackRequired):
        client.logger.exception(e)
        client.set_proxy(self.next_proxy().href)
        if client.relogin_attempt > 0:
            self.freeze(str(e), days=7)
            raise ReloginAttemptExceeded(e)
        client.settings = self.rebuild_client_settings()
        return self.update_client_settings(client.get_settings())
    elif isinstance(e, PleaseWaitFewMinutes):
        client.logger.exception(e)
        client.set_proxy(self.next_proxy().href)
        if client.relogin_attempt > 0:
            self.freeze(str(e), days=7)
            raise ReloginAttemptExceeded(e)
        client.settings = self.rebuild_client_settings()
        return self.update_client_settings(client.get_settings())
    elif isinstance(e, LoginRequired):
        client.logger.exception(e)
        client.set_proxy(self.next_proxy().href)
        if client.relogin_attempt > 0:
            self.freeze(str(e), days=7)
            raise ReloginAttemptExceeded(e)
        client.settings = self.rebuild_client_settings()
        return self.update_client_settings(client.get_settings())
    else:
        raise e

**Comment by adw0rd** [comment]
You are taking three arguments and passing two. Read the python documentation about it

And you just copied the contents of handle_exception from the example, write your implementation

**Comment by Yqno** [comment]
Yes I have tested a bit, I will do, thanks
