### ISSUE TITLE
ValueError when Logging in

### ISSUE THREAD

**Issue by Aryan-401** [adw0rd/instagrapi#108]
`Traceback (most recent call last):`
  `File "<input>", line 1, in <module>`
  `File "C:\Users\Aryan Garg\PycharmProjects\Intagrapi_proj\venv\lib\site-packages\instagrapi\mixins\auth.py", line 327, in login`
    `enc_password = self.password_encrypt(password)`
  `File "C:\Users\Aryan Garg\PycharmProjects\Intagrapi_proj\venv\lib\site-packages\instagrapi\mixins\password.py", line 14, in password_encrypt`
    `timestamp = datetime.now().strftime('%s')`
`ValueError: Invalid format string
`

Error shows up when logging into Instagram (upgraded to 1.5.1)

I really don't want to break anything else so didn't try to fiddle with the code...

**Comment by adw0rd** [comment]
@Aryan-401 what version of python?

**Comment by Aryan-401** [comment]
3.7.4 @adw0rd

**Comment by adw0rd** [comment]
@Aryan-401 

`In [3]: datetime.now().strftime('%s') == str(int(time.time()))
Out[3]: True`

**Comment by adw0rd** [comment]
@Aryan-401 i change `datetime.now().strftime('%s')` to `str(int(time.time()))` in instagrapi 1.5.3

**Comment by Aryan-401** [comment]
Yup Cleared it! Thanks!
