### ISSUE TITLE
Retrieve notifications?

### ISSUE THREAD

**Issue by vltclz** [adw0rd/instagrapi#1090]
Does this project include the ability to retrieve one user's notifications?
I can see that we can tweak a lot of the [notifications settings](https://github.com/adw0rd/instagrapi/blob/master/instagrapi/mixins/notification.py) but I don't see where I can retrieve notifications. (but maybe I've missed it?)

**Comment by adw0rd** [comment]
I do not remember that it was implemented, but you can help the project

**Comment by vltclz** [comment]
I tried analysing what happens when fetching notifications on Instagram website but I'm not really good at reverse-engineering APIs, so I'll pass on that. Thanks for your answer and I hope someone will have time to implement this!

**Comment by SinaKhalili** [comment]
If you use `cl.news_inbox_v1()` you can get them under `new_stories` and `old_stories`

**Comment by vltclz** [comment]
> If you use cl.news_inbox_v1() you can get them under new_stories and old_stories

Thank you @SinaKhalili, indeed this is where they are!
