### ISSUE TITLE
video_upload() don't upload videos instagrapi.exceptions.UnknownError: server processing error: VideoSourceError

### ISSUE THREAD

**Issue by mikebgrep** [adw0rd/instagrapi#110]
`instagrapi.exceptions.UnknownError: server processing error: VideoSourceError`

`Traceback (most recent call last):
  File "C:\Users\mike2\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1895, in call
    return self.func(*args)
  File "gui_dr.py", line 145, in go
    self.start_hashtag()
  File "gui_dr.py", line 240, in start_hashtag
    cl.video_upload(path_jpg + '/' + each, caption_dt)
  File "C:\Users\mike2\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\video.py", line 240, in video_upload
    raise e
  File "C:\Users\mike2\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\video.py", line 222, in video_upload
    configured = self.video_configure(
  File "C:\Users\mike2\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\video.py", line 311, in video_configure
    return self.private_request(
  File "C:\Users\mike2\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\private.py", line 306, in private_request
    raise e
  File "C:\Users\mike2\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\private.py", line 293, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\mike2\AppData\Local\Programs\Python\Python38\lib\site-packages\instagrapi\mixins\private.py", line 223, in _send_private_request
    raise UnknownError(**last_json)
instagrapi.exceptions.UnknownError: server processing error: VideoSourceError`

**Comment by Aryan-401** [comment]
IDK if its the same thing or not, but according to  instagrapi the video uploads to instagram, but even after refreshing for 5 min, it isnt uploaded... The code executes perfectly and there is no error message that pops up (the vide owas taken in 18:9 ratio and was 10 seconds long)

**Comment by adw0rd** [comment]
@mikebgrep VideoSourceError returns instagram, not instagrapi

**Comment by leikoilja** [comment]
@adw0rd, thanks a lot for all your hard work and amazing package!
I am also getting `VideoSourceError` just when running the "The full example" from README. Any ideas why is instagram returning it? 🤔  The video is in [place](https://www.instagram.com/p/CGgDsi7JQdS/) and should work

**Comment by adw0rd** [comment]
@leikoilja I checked and everything works fine, you are doing something wrong:

```
>>> from instagrapi import Client

>>> cl = Client()
>>> cl.login(username, password)

>>> m = cl.video_download(cl.media_pk_from_url('https://www.instagram.com/p/CGgDsi7JQdS/'), folder='/tmp')
PosixPath('/tmp/dhbastards_2422952854821341010.mp4')

>>> cl.video_upload(m, 'Test caption')
Analizing video file "/tmp/dhbastards_2422952854821341010.mp4"
Generating thumbnail "/tmp/dhbastards_2422952854821341010.mp4.jpg"...
Media(pk=2609885404247520994, id='2609885404247520994_1903424587', code='CQ4LPKIpnbi', ....
```

**Comment by leikoilja** [comment]
@adw0rd thanks for coming back to me on that one.
So, the example you have just texted above works for `video_upload` perfectly fine for me as well. Just realised that I am still getting `VideoSourceError` when trying to upload the `video_upload_to_story` like so:
```python
from instagrapi import Client

cl = Client()
cl.login(username, password)
media_path = cl.video_download(
    cl.media_pk_from_url('https://www.instagram.com/p/CGgDsi7JQdS/'),
    folder='/tmp')
)
vnly_test = cl.user_info_by_username('vnly_test')
#  loc = cl.location_complete(Location(name='Test', lat=59.48682142013645, lng=18.064404096806104))
#  ht = cl.hashtag_info('dhbastards')

cl.video_upload_to_story(
    media_path,
    "Credits @adw0rd",
    #  mentions=[StoryMention(user=vnly_test, x=0.49892962, y=0.703125, width=0.8333333333333334, height=0.125)],
    #  locations=[StoryLocation(location=loc, x=0.33, y=0.22, width=0.4, height=0.7)],
    #  links=[StoryLink(webUri='https://github.com/adw0rd/instagrapi')],
    #  hashtags=[StoryHashtag(hashtag=ht, x=0.23, y=0.32, width=0.5, height=0.22)],
)

```
Commented out many of lines just to get the basis working :) 
And what i get is: 

> Using '.sessions/vnly_test.json' session file
> Analizing video file "/private/tmp/dhbastards_2422952854821341010.mp4"
> Generating thumbnail "/private/tmp/dhbastards_2422952854821341010.mp4.jpg"...
> Traceback (most recent call last):
>   File "/Users/leikoilja/Library/Caches/pypoetry/virtualenvs/igcracker-lj5Sbx08-py3.8/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 184, in _sen
> ivate_request
>     response.raise_for_status()
>   File "/Users/leikoilja/Library/Caches/pypoetry/virtualenvs/igcracker-lj5Sbx08-py3.8/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_stat
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/media/configure_to_story/?video=1
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "main2.py", line 41, in <module>
>     cl.video_upload_to_story(
>   File "/Users/leikoilja/Library/Caches/pypoetry/virtualenvs/igcracker-lj5Sbx08-py3.8/lib/python3.8/site-packages/instagrapi/mixins/video.py", line 396, in video_
> ad_to_story
>     raise e
>   File "/Users/leikoilja/Library/Caches/pypoetry/virtualenvs/igcracker-lj5Sbx08-py3.8/lib/python3.8/site-packages/instagrapi/mixins/video.py", line 375, in video_
> ad_to_story
>     configured = self.video_configure_to_story(
>   File "/Users/leikoilja/Library/Caches/pypoetry/virtualenvs/igcracker-lj5Sbx08-py3.8/lib/python3.8/site-packages/instagrapi/mixins/video.py", line 619, in video_
> igure_to_story
>     return self.private_request(
>   File "/Users/leikoilja/Library/Caches/pypoetry/virtualenvs/igcracker-lj5Sbx08-py3.8/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 321, in priv
> request
>     raise e
>   File "/Users/leikoilja/Library/Caches/pypoetry/virtualenvs/igcracker-lj5Sbx08-py3.8/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 308, in priv
> request
>     self._send_private_request(endpoint, **kwargs)
>   File "/Users/leikoilja/Library/Caches/pypoetry/virtualenvs/igcracker-lj5Sbx08-py3.8/lib/python3.8/site-packages/instagrapi/mixins/private.py", line 238, in _sen
> ivate_request
>     raise UnknownError(**last_json)
> instagrapi.exceptions.UnknownError: server processing error: VideoSourceError
>

**Comment by adw0rd** [comment]
@leikoilja stories should be in resolution 9:16 (720x1280)

To not think about it, you can use [StoryBuilder](https://adw0rd.github.io/instagrapi/usage-guide/story.html)

**Comment by leikoilja** [comment]
Thanks @adw0rd, will try it out! Once again, thanks for an awesome project 🤩
