### ISSUE TITLE
Instagram Note

### ISSUE THREAD

**Issue by nil-malh** [adw0rd/instagrapi#1121]
**Is your feature request related to a problem? Please describe.**
A new feature

**Describe the solution you'd like**
Instagram implemented a new feature called Note that can't be interacted with the public API, I was wondering if it was planned to be implemented to instagrapi ?

**Comment by adw0rd** [comment]
I do not plan to add this, but if you do and send a PR I will be grateful

**Comment by nil-malh** [comment]
Done you can check #1127 :)
