### ISSUE TITLE
[BUG] ChallengeResolve: Unknown step_name "select_contact_point_recovery"

### ISSUE THREAD

**Issue by mahirozdin** [adw0rd/instagrapi#1138]
`ChallengeResolve: Unknown step_name "select_contact_point_recovery" for "waqakc" in challenge resolver: {'step_name': 'select_contact_point_recovery', 'step_data': {'choice': '1', 'email': 'w****c@gmail.com', 'hl_co_enabled': False, 'sigp_to_hl': False}, 'flow_render_type': 3, 'bloks_action': 'com.instagram.challenge.navigation.take_challenge', 'nonce_code': 'Bb8L35qF9I', 'user_id': 3897040005, 'cni': 18275304355128006, 'challenge_context': '{"step_name": "select_contact_point_recovery", "nonce_code": "Bb8L35qF9I", "user_id": 3897040005, "cni": 18275304355128006, "is_stateless": false, "challenge_type_enum": "HACKED_LOCK", "present_as_modal": false}', 'challenge_type_enum_str': 'HACKED_LOCK', 'status': 'ok'}`

And my code is 

```
def handle_exception(client, e):
    if isinstance(e, BadPassword):
        client.logger.exception(e)
        client.set_proxy(self.next_proxy().href)
        if client.relogin_attempt > 0:
            self.freeze(str(e), days=7)
            raise ReloginAttemptExceeded(e)
        client.settings = self.rebuild_client_settings()
        return self.update_client_settings(client.get_settings())
    elif isinstance(e, LoginRequired):
        client.logger.exception(e)
        client.relogin()
        return self.update_client_settings(client.get_settings())
    elif isinstance(e, ChallengeRequired):
        api_path = json_value(client.last_json, "challenge", "api_path")
        if api_path == "/challenge/":
            client.set_proxy(self.next_proxy().href)
            client.settings = self.rebuild_client_settings()
        else:
            try:
                client.challenge_resolve(client.last_json)
            except ChallengeRequired as e:
                self.freeze('Manual Challenge Required', days=2)
                raise e
            except (ChallengeRequired, SelectContactPointRecoveryForm, RecaptchaChallengeForm) as e:
                self.freeze(str(e), days=4)
                raise e
            self.update_client_settings(client.get_settings())
        return True
    elif isinstance(e, FeedbackRequired):
        message = client.last_json["feedback_message"]
        if "This action was blocked. Please try again later" in message:
            self.freeze(message, hours=12)
            # client.settings = self.rebuild_client_settings()
            # return self.update_client_settings(client.get_settings())
        elif "We restrict certain activity to protect our community" in message:
            # 6 hours is not enough
            self.freeze(message, hours=12)
        elif "Your account has been temporarily blocked" in message:
            """
            Based on previous use of this feature, your account has been temporarily
            blocked from taking this action.
            This block will expire on 2020-03-27.
            """
            self.freeze(message)
    elif isinstance(e, PleaseWaitFewMinutes):
        self.freeze(str(e), hours=1)
    raise e

        

cl = Client()
cl.handle_exception = handle_exception


try:
    cl.login("xxx", "xxx")
except Exception as e:
    print(e)






user_id = cl.user_id_from_username("instagram")
user = cl.user_info(user_id)
print(user)

cl.user_follow(user_id)
```

**Comment by adw0rd** [comment]
https://github.com/adw0rd/instagrapi/issues?q=select_contact_point_recovery

**Comment by mahirozdin** [comment]
Sorry I implemented the commit thanks.

**Comment by sekoakb** [comment]
hi, my code is:

`# -*- coding: utf-8 -*-
#imports from other files
from creds2 import USERNAME, PASSWORD
import os
#****************************************************************************************
#Module imports
from instagrapi import Client
from instagrapi.exceptions import (ClientNotFoundError, ClientError)
#****************************************************************************************
#Constants
IG_USERNAME = USERNAME
IG_PASSWORD = PASSWORD
IG_CREDENTIAL_PATH = "./ig_settings.json"
#****************************************************************************************
class Bot:
    username = IG_USERNAME
    password = IG_PASSWORD
    def get_client(self):
        def handle_exception(client,e):
            if isinstance(e, ClientNotFoundError):
                print(f'user not found, {e}')
            elif isinstance(e, ClientError):
                print(f'Client error occurred: {e}')
                time.sleep(3)
        cl = Client()     
        cl.handle_exception=handle_exception
        if os.path.exists(IG_CREDENTIAL_PATH):
            session = cl.load_settings(IG_CREDENTIAL_PATH)
            cl.set_settings(session)
            print('executed3')
            cl.get_timeline_feed()
        return cl

if __name__ == "__main__":
    bot = Bot()
    cl=bot.get_client()
    `
    
Appearent it handles the exception clienterror and prints.
**"executed3
Client error occurred: Please wait a few minutes before you try again."**
but it doesnt leave with handling, and keeps traceback, it prints following. what am i doing wrong?
normally i expect it to print only above.


executed3
Client error occurred: Please wait a few minutes before you try again.
Traceback (most recent call last):
  File "C:\Users\akbul\AppData\Local\Programs\Python\Python311\Lib\site-packages\instagrapi\mixins\private.py", line 360, in _send_private_request
    response.raise_for_status()
  File "C:\Users\akbul\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://i.instagram.com/api/v1/feed/timeline/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\akbul\AppData\Local\Programs\Python\Python311\Lib\site-packages\instagrapi\mixins\private.py", line 520, in private_request      
    self._send_private_request(endpoint, **kwargs)
  File "C:\Users\akbul\AppData\Local\Programs\Python\Python311\Lib\site-packages\instagrapi\mixins\private.py", line 459, in _send_private_request
    raise ClientError(e, response=e.response, **last_json)
instagrapi.exceptions.ClientError: Please wait a few minutes before you try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\akbul\AppData\Local\Programs\Python\Python311\Lib\site-packages\instagrapi\mixins\private.py", line 360, in _send_private_request
    response.raise_for_status()
  File "C:\Users\akbul\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://i.instagram.com/api/v1/feed/timeline/

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\akbul\Desktop\codes\deneme\deneme3.py", line 52, in <module>
    cl=bot.get_client()
       ^^^^^^^^^^^^^^^^
  File "c:\Users\akbul\Desktop\codes\deneme\deneme3.py", line 45, in get_client
    cl.get_timeline_feed()
  File "C:\Users\akbul\AppData\Local\Programs\Python\Python311\Lib\site-packages\instagrapi\mixins\auth.py", line 218, in get_timeline_feed
    return self.private_request(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akbul\AppData\Local\Programs\Python\Python311\Lib\site-packages\instagrapi\mixins\private.py", line 539, in private_request
    return self._send_private_request(endpoint, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\akbul\AppData\Local\Programs\Python\Python311\Lib\site-packages\instagrapi\mixins\private.py", line 459, in _send_private_request
    raise ClientError(e, response=e.response, **last_json)
instagrapi.exceptions.ClientError: Please wait a few minutes before you try again.
