### ISSUE TITLE
"Link Sticker" of Story 

### ISSUE THREAD

**Issue by sametcopur** [adw0rd/instagrapi#1139]
Hi, 

Firstly thanks for who contributed this amazing project.

I am trying to do a instagram bot which automaticall yshares stories with LINK sticker.

https://adw0rd.github.io/instagrapi/usage-guide/story.html in here, StoryLink works well, it adds link to story but only problem is there is no "link sticker". 

this is what i mean:
![image](https://user-images.githubusercontent.com/72708109/219945645-4f133ca0-0162-4998-b602-b87c2172cabd.png)

https://github.com/adw0rd/instagrapi/issues/644 here it explains how it stickers works and says check it with charles.

then i tried to do what this article says: https://adw0rd.com/2020/3/26/sniffing-instagram-charles-proxy/en/ and finally got something in charles.

![image](https://user-images.githubusercontent.com/72708109/219945415-fe2bc1e4-31e7-4540-b1c3-42d285c7ad87.png)

in the end of article, author says if headers-accept contains "zstd" you can decompress then but i couldn't do it :/

for adding link with stickler to my story what should i do or where do i look.

**Comment by idrizdi** [comment]
@sametcopur knew how to add Link Sticker ?

**Comment by adw0rd** [comment]
@idrizdi https://adw0rd.github.io/instagrapi/usage-guide/story.html

**Comment by sametcopur** [comment]
@adw0rd it's add they link but just the link, there is no stickler. that is the problem.

**Comment by adityaa-codes** [comment]
Thats an Instagram App StoryEditor Feature and not the api feature.

**Comment by danielsantos852** [comment]
Good day, everyone!

Has anyone got more information on this issue?

I'm trying to make stories with link stickers as well and am facing the same issues (lack of documentation/examples of URL sticker use).

 Any help will be immensely appreciated!

**Comment by adw0rd** [comment]
https://adw0rd.github.io/instagrapi/usage-guide/story.html

**Comment by juppcamper** [comment]
> https://adw0rd.github.io/instagrapi/usage-guide/story.html

Hi adw0rd, I really appreciate your work, but this issue can't be clarified with a reference to the documentation. Alone the hint that link stickers need x and y coordinates and size information like hashtags is missing at all. Moreover, this results in the sticker remaining invisible (my workaround is to make it huge (e.g. width and height = 5)) so that it doesn't matter where the user taps. But answering the request with a link to the documentation is really not helpful.

**Comment by adw0rd** [comment]
@juppcamper Thank you very much for the comment, send your improvements to the documentation please, where you share your experience with StorySticker

**Comment by amitsingh8899** [comment]
hi @adw0rd , can you help me understand how adding link feature works, currently both the links i.e charles and usage-guide are not opening.

**Comment by bondobrus** [comment]
> hi @adw0rd , can you help me understand how adding link feature works, currently both the links i.e charles and usage-guide are not opening.

Hello did you find a way? Anybody?
