### ISSUE TITLE
[BUG] cl.photo_upload(path, caption) stop uploading photo

### ISSUE THREAD

**Issue by AHEKOT** [adw0rd/instagrapi#1151]
**Describe the bug**
cl.photo_upload(path, caption) stop uploading photo. It returns:
Photo Upload failed with the following response: <Response [400]>
{"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}

**To Reproduce**
try to upload photo using cl.photo_upload(path, caption)

**Expected behavior**
photo uploaded.

**Comment by adw0rd** [comment]
Forks fine:
```
>>> user_id = cl.user_id_from_username("adw0rd_")
>>> medias = cl.user_medias(user_id, 100)
>>> path = cl.photo_download_by_url(medias[-1].thumbnail_url)
>>> cl.photo_upload(path, "caption")
Media(pk='3043698088812728822', id='3043698088812728822_58217347077', code='Co9Y0kbN9H2', ...
```

cannot reproduce
