### ISSUE TITLE
Every time I try to login, it asks for verification code

### ISSUE THREAD

**Issue by Sxvxgee** [adw0rd/instagrapi#1165]
**Describe the bug**
Not so long ago I used to use this library and I never was asked for a "verification code" by Instagram, but recently every time I try to login, it asks for a verification code. This isn't good for me as I want to log into the account through a custom application of mine, so I'm not sure what to do as it asks for the code through terminal input and the terminal isn't a part of my application.

**To Reproduce**
```py
from instagrapi import Client
bot = Client()
bot.login("username", "password")
```

**Traceback**
No traceback

**Expected behavior**
I expect it to login without asking for a code just like it goes when using the normal app

**Desktop (please complete the following information):**
 - OS: Zorin OS 16.2
 - Python version 3.11.0
 - instagrapi version [e.g. 1.9.3, not "latest"] 1.16.41
 - moveipy version if used -
 - imagemagick version if used -

**Comment by adw0rd** [comment]
https://adw0rd.github.io/instagrapi/usage-guide/challenge_resolver.html

**Comment by Sxvxgee** [comment]
> https://adw0rd.github.io/instagrapi/usage-guide/challenge_resolver.html

How do I know which challenge is presented by Instagram? Since the user would be entering the account credentials through the GUI, I'd need to know when to ask them for a new password if the challenge was a new password, or ask them for the code when the challenge is asking for one.

**Comment by Sxvxgee** [comment]
Thank you!
