### ISSUE TITLE
Explore Tab

### ISSUE THREAD

**Issue by myaicreator** [adw0rd/instagrapi#1175]
Hello, which endpoint should we use for the explore tab?

I tried this. Bu response empty list.

medias = self.client.explore_reels(amount=10)
        print(medias)

**Comment by SaeidB** [comment]
> Hello, which endpoint should we use for the explore tab?
> 
> I tried this. Bu response empty list.
> 
> medias = self.client.explore_reels(amount=10) print(medias)

`self.explore_page()`
