### ISSUE TITLE
how to pass the settings in cl = Client(settings) for saved cookies so that session never expires?

### ISSUE THREAD

**Issue by purnima110895** [adw0rd/instagrapi#1195]
I followed below steps -
cl = Client()
print(cl.get_settings())
>> settings = {'uuids': {'phone_id': 'a3e60051-dc5b-4dd4-b089-29ab63deddcb', 'uuid': '3c6df3c5-39cc-480f-ba6d-47d999bfd59c', 'client_session_id': '861281df-776a-4909-a3b3-e0cbaa2c4b3d', 'advertising_id': 'ce7525d7-d55a-46db-8daf-ad868122018e', 'android_device_id': 'android-3e7f020e89ee73fb',
                                  'request_id': '5100825d-f84f-46fb-85c8-72542fba5f66', 'tray_session_id': '70f690b7-b9f5-4c2a-b9a5-3d483713348d'}, 'mid': None, 'ig_u_rur': None, 'ig_www_claim': None, 'authorization_data': {}, 'cookies': {}, 'last_login': None, 'device_settings': {'app_version': '203.0.0.29.118', 'android_version': 26, 'android_release': '8.0.0', 'dpi': '480dpi', 'resolution': '1080x1920', 'manufacturer': 'Xiaomi', 'device': 'capricorn', 'model': 'MI 5s', 'cpu': 'qcom', 'version_code': '314665256'}, 'user_agent': 'Instagram 203.0.0.29.118 Android (26/8.0.0; 480dpi; 1080x1920; Xiaomi; MI 5s; capricorn; qcom; en_US; 314665256)', 'country': 'US', 'country_code':1, 'locale': 'en_US', 'timezone_offset': -14400}
cl = Client(settings)

Here last_login gives None , what all argument needs to be changed while passing saved cookies, how we will get the last login?

@adw0rd ,,Please help.

**Comment by adw0rd** [comment]
Save it and get it, or I didn't understand the question?

**Comment by purnima110895** [comment]
> Save it and get it, or I didn't understand the question?

When I save the settings, it gives last_login = None, it is fine as previously I was getting challenge resolver error, and sometimes the username you entered is incorrect?

**Comment by adw0rd** [comment]
@purnima110895 

https://github.com/adw0rd/instagrapi/issues?q=username+your+entered

https://github.com/adw0rd/instagrapi/discussions?discussions_q=The+username+you+entered

**Comment by purnima110895** [comment]
resolved by saving the settings .
