### ISSUE TITLE
user_medias_gql not using the "amount" parameter correctly

### ISSUE THREAD

**Issue by riccardolunardi** [adw0rd/instagrapi#120]
Hello,
I might be wrong here, but in [user_medias_gql](https://github.com/adw0rd/instagrapi/blob/6045f93630fe674cf9e5a6bc732fbaa5f5718cb4/instagrapi/mixins/media.py#L408), which is used by user_media, too, I think the paramater "amount" is not taken in consideration when setting the parameters for the request (line 433). 

From line 431 to line 433 is:
```
variables = {
    "id": user_id,
    "first": 50,  # default amount
}
```

when I think is should be:
```
variables = {
    "id": user_id,
    "first": amount,  # default amount
}
```

I'm a bit ignorant on the instagram APIs, but I think if I need just 1 media this will increase substantialy the time spent doing this operation.

Thanks and keep up the good work :)

**Comment by keethesh** [comment]
To avoid having requests with an amount too big, I think the script should divide the amount modulo 50, and use that in the 'first' parameter

**Comment by riccardolunardi** [comment]
It could be an idea for sure. Despite that, if you look at the code, he does already handle that though the maximum number of result Instagram returns in a single page. In this way big `amount` are already handled. What is not handle, in my opinion, is amounts that are < 50.
I solved this using another function in the code anyway, so it's not that big of a deal :)

**Comment by adw0rd** [comment]
These are Instagram restrictions, you can only specify <= 50:

```
>>> data = self.public_graphql_request({'id': 1903424587, 'first': 50}, query_hash="e7e2f4da4b02303f74f0841279e52d76")
>>> len(data["user"]["edge_owner_to_timeline_media"]["edges"])
50

>>> data = self.public_graphql_request({'id': 1903424587, 'first': 62}, query_hash="e7e2f4da4b02303f74f0841279e52d76")
>>> len(data["user"]["edge_owner_to_timeline_media"]["edges"])
50

>>> data = self.public_graphql_request({'id': 1903424587, 'first': 22}, query_hash="e7e2f4da4b02303f74f0841279e52d76")
>>> len(data["user"]["edge_owner_to_timeline_media"]["edges"])
22
```
