### ISSUE TITLE
Publish story for close friends

### ISSUE THREAD

**Issue by LuisDuarte1** [adw0rd/instagrapi#1210]
Hi! Sorry to bother,
is there any way to make a private story in this unofficial api?

If yes, can you give me a hint to do it? ^^
If no, I maybe want to look at it and contribute!

Thanks :)

**Comment by adw0rd** [comment]
I think this is done through `extra_data`, but I need to look up the key through ProxyMan/Charles, but now I don't have time

https://adw0rd.github.io/instagrapi/usage-guide/story.html

**Comment by LuisDuarte1** [comment]
this is done through `"audience":"besties"` extra option, thanks ^^
