### ISSUE TITLE
[BUG] I am unable to install instagrapi... It was working fine few days ago 

### ISSUE THREAD

**Issue by musaib821** [adw0rd/instagrapi#1249]
Because replit (3.2.4) depends on typing_extensions (>=3.7.4,<4.0.0)
   and no versions of replit match >3.2.4,<3.2.5 || >3.2.5,<4.0.0, replit (>=3.2.4,<3.2.5 || >3.2.5,<4.0.0) requires typing_extensions (>=3.7.4,<4.0.0).
  And because replit (3.2.5) depends on typing_extensions (>=3.7.4,<4.0.0), replit (>=3.2.4,<4.0.0) requires typing_extensions (>=3.7.4,<4.0.0).
  Because instagrapi (1.17.3) depends on pydantic (1.10.7)
   and pydantic (1.10.7) depends on typing-extensions (>=4.2.0), instagrapi (1.17.3) requires typing-extensions (>=4.2.0).
  Thus, instagrapi (1.17.3) is incompatible with replit (>=3.2.4,<4.0.0).
  So, because python-template depends on both replit (^3.2.4) and instagrapi (1.17.3), version solving failed.

**Comment by adw0rd** [comment]
Yes, it works well, here is an example:

```
pip install instagrapi
Collecting instagrapi
  Downloading instagrapi-1.17.3.tar.gz (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.2/88.2 kB 1.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests<3.0,>=2.25.1 in /Users/adw0rd/.venv/lib/python3.10/site-packages (from instagrapi) (2.27.1)
Requirement already satisfied: PySocks==1.7.1 in /Users/adw0rd/.venv/lib/python3.10/site-packages (from instagrapi) (1.7.1)
Collecting pydantic==1.10.7
  Downloading pydantic-1.10.7-cp310-cp310-macosx_11_0_arm64.whl (2.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 9.1 MB/s eta 0:00:00
Requirement already satisfied: pycryptodomex==3.17 in /Users/adw0rd/.venv/lib/python3.10/site-packages (from instagrapi) (3.17)
Requirement already satisfied: typing-extensions>=4.2.0 in /Users/adw0rd/.venv/lib/python3.10/site-packages (from pydantic==1.10.7->instagrapi) (4.4.0)
Requirement already satisfied: idna<4,>=2.5 in /Users/adw0rd/.venv/lib/python3.10/site-packages (from requests<3.0,>=2.25.1->instagrapi) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/adw0rd/.venv/lib/python3.10/site-packages (from requests<3.0,>=2.25.1->instagrapi) (1.26.12)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/adw0rd/.venv/lib/python3.10/site-packages (from requests<3.0,>=2.25.1->instagrapi) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in /Users/adw0rd/.venv/lib/python3.10/site-packages (from requests<3.0,>=2.25.1->instagrapi) (2022.6.15.1)
Building wheels for collected packages: instagrapi
  Building wheel for instagrapi (setup.py) ... done
  Created wheel for instagrapi: filename=instagrapi-1.17.3-py3-none-any.whl size=101501 sha256=a217d7c774d82133e198248fe388776f678976f4a45e26b13b80456a0d693cba
  Stored in directory: /Users/adw0rd/Library/Caches/pip/wheels/ce/c9/12/424eb0569fc7fc96ee6c23fd2e285f483d6753a3ec6a8b2e81
Successfully built instagrapi
Installing collected packages: pydantic, instagrapi
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.10.2
    Uninstalling pydantic-1.10.2:
      Successfully uninstalled pydantic-1.10.2
Successfully installed instagrapi-1.17.3 pydantic-1.10.7

[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: pip install --upgrade pip
```

Ask the community if anyone can help
https://t.me/instagrapi

**Comment by adw0rd** [comment]
Apparently some dependency conflicts with replit, but this does not apply directly to instagrapi, solve the problem with replit

**Comment by musaib821** [comment]
Thanks I managed to solve it

**Comment by musaib821** [comment]
But I am continuously getting error that instagrapi.exceptions.UnknownError: The username you entered doesn't appear to belong to an account. Please check your username and try again. 
I tried many times but it's same error.. I am getting this error from few days I tried with different working accounts but still the same problem... Can you help me here???

**Comment by adw0rd** [comment]
https://github.com/adw0rd/instagrapi/discussions?discussions_q=The+username+you+entered
https://github.com/adw0rd/instagrapi/issues?q=The+username+you+entered
