### ISSUE TITLE
NoneType' object has no attribute 'startswith' in cl.direct_send

### ISSUE THREAD

**Issue by moradpoor** [adw0rd/instagrapi#125]
hi

i got this error when tried to send message
NoneType' object has no attribute 'startswith' 

my code like this 
cl = instagrapi.Client()
cl.login('usr','pass')
code = randit(9999,99999)
try :
  userid = cl.user_id_from_username(str(instaid))
  cl.direct_send('code : %s' %code ,[userid])
except Exception as e :
   if 'User not found' in str(e) :
       bot.sendMessage(chatid,'username invalid')
   else :
       bot.sendmessage(admin,str(e))

**Comment by adw0rd** [comment]
@moradpoor fixed 1.5.9
