### ISSUE TITLE
hashtag_medias_recent always returning top media instead of recent

### ISSUE THREAD

**Issue by coder-maddy** [adw0rd/instagrapi#1256]
hashtag_medias_recent always returning top media instead of recent media.
Can be reproduced from below code.

`
from instagrapi import Client
import time

client = Client()
client.login('<username>','<password>')

medias = client.hashtag_medias_recent('programming', 20)

for i, media in enumerate(medias):
    client.media_like(media.id)
    print(f'Likes post number {i+1}')
    time.sleep(3)

print('exiting')
`

**Comment by SaeidB** [comment]
will be fixed soon :

**Comment by SaeidB** [comment]
will be fixed soon : 

https://github.com/adw0rd/instagrapi/pull/1257

**Comment by coder-maddy** [comment]
@adw0rd May I know when package will be available with this fix?

**Comment by SaeidB** [comment]
> @adw0rd May I know when package will be available with this fix?

Its already added, update your package to get fixes

**Comment by adw0rd** [comment]
@coder-maddy try `pip install instagrapi==1.17.4`

**Comment by coder-maddy** [comment]
Working now thanks @adw0rd  and @SaeidB
