### ISSUE TITLE
[Enhancement] Slow hashtag retrieving 

### ISSUE THREAD

**Issue by DeusAres** [adw0rd/instagrapi#126]
There should be a way to retrieve only selected data about a media in a hashtag. Is it doable?

**Comment by adw0rd** [comment]
@DeusAres Can you give an example?

**Comment by DeusAres** [comment]
@adw0rd 
```media_in_hashtag = cl.hashtag_medias_recent(hashtag, number_of_likes)```
Even if num of likes is low, less than 20, it takes some times, around 1 to 3 minutes to complete the function.
It's very slow, compared to the datas I need, ID only

**Comment by adw0rd** [comment]
@DeusAres  number_of_likes - what is this?

![image](https://user-images.githubusercontent.com/546889/113395364-64334a00-93a2-11eb-99c1-014252f0fdfd.png)

second argument is not "number_of_likes", this is amount of returned medias

**Comment by adw0rd** [comment]
Regarding the fact that the function is slow because of sleeps, you can change `cl.request_timeout = 0.1`

**Comment by DeusAres** [comment]
Oppsss, the var means number of post to retrieve in a hashtags and like after.
Thank you for the feedback, will look into it.
In your experience, around which rate of request a bot becomes spottable?

**Comment by adw0rd** [comment]
I sleep for 5 seconds/request, but in general I need to think over the request chains for each case and make timeouts similar to the user

**Comment by adw0rd** [comment]
You can also try using `hashtag_medias_recent_v1` instead of `hashtag_medias_recent`, most likely `hashtag_medias_recent_a1` is sleeping

**Comment by mrmmg** [comment]
> Regarding the fact that the function is slow because of sleeps, you can change `cl.request_timeout = 0.1`

hi
i'm using this method and it's very slow so, I tried to make it faster by given option that you wrote but nothing change.

do you have any idea how to fix this problem?

**Comment by adw0rd** [comment]
@mrmmg show your code

**Comment by mrmmg** [comment]
> @mrmmg show your code

I Adds a new router to instagrapi-rest repository called hashtags.py

this is file content:

```
from fastapi import APIRouter, Depends, Form

from typing import List, Dict, Optional

from instagrapi import Client
from instagrapi.types import Media, Usertag, Location, UserShort

from dependencies import ClientStorage, get_clients


router = APIRouter(
    prefix="/explore",
    tags=["explore"],
    responses={404: {"description": "Not found"}}
)

@router.post("/search/recent")
async def get_hashtag_recent(sessionid: str = Form(...),
                        tag: str = Form(...),
                        amount: int = Form(...),
                        clients: ClientStorage = Depends(get_clients)):

    cl = clients.get(sessionid)
    cl.request_timeout = 0.1
    return cl.hashtag_medias_recent(tag, amount)

@router.post("/search/top")
async def get_hashtag_top(sessionid: str = Form(...),
                        tag: str = Form(...),
                        amount: int = Form(...),
                        clients: ClientStorage = Depends(get_clients)):

    cl = clients.get(sessionid)
    cl.request_timeout = 0.1
    return cl.hashtag_medias_top(tag, amount)
```

With this code for one tag it's took ~6 seconds to retrieve and for 200 tags it's took 15 - 25 seconds

**Comment by adw0rd** [comment]
@mrmmg try `cl.hashtag_medias_recent_v1` and `cl.hashtag_medias_top_v1`
