### ISSUE TITLE
Cant login [429 error]

### ISSUE THREAD

**Issue by amiwrpremiumold** [adw0rd/instagrapi#129]
I got `429: Too many requests` | `PleaseWaitFewMinutes: Please wait a few minutes before you try again.` errors when I try to log in. I don't send too many requests. It's like the second or third login attempt I'm making this month and all I did was getting some user IDs and that's it

I tried different VPN connection and adding proxy but it didn't help

**Comment by adw0rd** [comment]
@amiwrpremium Show example code how you use

**Comment by amiwrpremium** [comment]
First, I wanna thank you for providing such a great library.


I've tried `cl = Client(proxy='https://165.225.77.47:9443')` .
And also tried using `cl.set_proxy("https://165.225.77.47:9443")` before `cl.login(uname, passwd)`

Didn't Work.


I changed my wifi connection and connected to another wifi and it worked fine.

**Comment by adw0rd** [comment]
https://165.225.77.47:9443 does not work

**Comment by adw0rd** [comment]
![image](https://user-images.githubusercontent.com/546889/113571236-aa94dd00-961e-11eb-877f-42c1b45c7df9.png)

**Comment by amiwrpremium** [comment]
That was a public free proxy that I scraped and checked before using it.
Anyway, it's working now. 

thanks for your answer.

**Comment by amiwrpremium** [comment]
I'm getting 429 error, again and again, even though I use proxy for each account
When the proxy is bad it gives me me proxy error, but when it's good I think it just ignores it.
It doesn't fix with proxy, VPN, or anything. I have to change my network. 

And I see other people keep getting this error too.


Thanks again

**Comment by adw0rd** [comment]
This is a error from Instagram that says that you exceed the frequency of requests, make them less often, or change IP (pool of proxies), uuids, etc. I use proxy rotation and timeouts for 10 seconds per request, and I also freeze accounts in geometric progression up to 24 hours

**Comment by amiwrpremium** [comment]
Can you please provide a short code snippet?

I want to log in to multiple accounts (say around 50+) at the same time using threading to perform just one simple task (like send a special direct message or follow a user or ...) at a time. Every account uses a different checked proxy (socks4, socks5, http or https) 
‍‍‍
This is my login snippet now
```
try:
    cl = Client(proxy=new_checked_proxy())
    login = cl.login(username, password)
except Exception as e:
    print(e)
    return
```



Thanks

**Comment by adw0rd** [comment]
@amiwrpremium I can't fit all this into one snippet, e.g. freezes are stored in the database and controlled by background processes

1) I save (cl.dump_settings) and specify the saved settings in Client before login
2) Rotation of proxies
3) Rotation of devices
4) Regenerate uuids
5) Change user_agent
6) Sleep each request to 10 seconds
7) Freeze account to 24 hours
8) automate challenge resolve by email and sms

**Comment by amiwrpremium** [comment]
Whatever I change I bump into another Error. And it doesn't get fix until I change my network completely. Premium VPNs like Nord VPN or Express VPN or ... doesn't help either.

**Comment by amiwrpremium** [comment]
Whatever I change I bump into another Error. And it doesn't get fix until I change my network completely. Premium VPNs like Nord VPN or Express VPN or ... doesn't help either.

**Comment by TremotinoVolante** [comment]
First of all thank you for providing such a great library!

I also get this error: since yesterday:
`instagrapi.exceptions.ClientThrottledError: 429 Client Error: - for url: https://i.instagram.com/accounts/login/`

It was working fine for a week or so.
What I want to do is to upload one video every day. 
the code is: 
`cl = Client()
cl.login(username, password)

#upload to Instagram
cl.video_upload(
    path = pathVideo,
    caption = captionVideo,
    thumbnail = pathThumbnail,
)`

How do I make the request less often? is one login a day too often? 
What do you mean with point 8 

> automate challenge resolve by email and sms

**Comment by adw0rd** [comment]
@TremotinoVolante @amiwrpremiumold I fixed one of the login problems after error 429 yesterday, check if the fix helped you?

**Comment by TremotinoVolante** [comment]
Hi @adw0rd, 
Thank you very much for your replay and fix.
yes it kind of worked with a first test. 
I still got the error message, but it uploaded successfully a test sunrise video at the dolomiti_timelapse channel. 
Thank your very much! I will observe the upload the next few days and I will report how it does in the long term.
The error I got was:
```
D:\...\upload_video_insta_sunrise.py : Status 429: Too many requests
In D:\...\sunrise_ps_script_insta_testupload.ps1:106 Zeichen:1
+ D:\...\upload_video_insta_sunrise.py ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Status 429: Too many requests:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandErro
```

**Comment by adw0rd** [comment]
@TremotinoVolante make fewer requests

**Comment by TremotinoVolante** [comment]
I'm sorry I don't understand how to do that. Or what is wrong with the code. 
I just want to login once and upload one file a day. How is it possible to influence the # of requests in the code? I found line 
`307 self.private_requests_count += 1` 
in private.py do I have to change this part?

Also after the update to release 1.6.3 I get with every login a email that a new device logged in. Is this good or bad? 
How may I use always the same device?

**Comment by adw0rd** [comment]
Use `instagrapi==1.7.3`

`private_requests_count` is counter only

if you are making few requests, try increasing the timeout `cl.request_timeout = 30`

**Comment by TremotinoVolante** [comment]
> Use `instagrapi==1.7.3`
> 
> `private_requests_count` is counter only
> 
> if you are making few requests, try increasing the timeout `cl.request_timeout = 30`

 `cl.request_timeout = 30` worked for me! Thank you very much!
