### ISSUE TITLE
[BUG] Like_Count

### ISSUE THREAD

**Issue by AppleUser0310** [adw0rd/instagrapi#1291]
First of all, fantastic job to adword on the api, it works a charm on most aspects.

However, I've been encountering a problem when it comes to like_count and view_count. Unless I made a mistake, these two instances are returned as NoneTypes, and I've tried looking through the backend to modify the instance to float() or int() but haven't been able to.

I've been accessing these values through this line of code: 
media.user.dict().get("view_count")

Am I missing something? Is there a reason it is left as Nonetype?

Thanks for the help

**Comment by adw0rd** [comment]
`view_count` is available only for `Media` type `video` or `IGTV`, but you are trying to get it from `User`
