### ISSUE TITLE
Problems with absolute path passed to photo_upload()

### ISSUE THREAD

**Issue by emorevival** [adw0rd/instagrapi#130]
Is there a way to pass the full path to the function? I tried all 3 ways (passing it as `'C:\\...'`, `'C:/'` and `r'C:\'`) but they all return `FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\Desktop\\project\\01.jpg'`

Am I missing something?

**Comment by adw0rd** [comment]
Show example code how do you pass the path to photo_upload?

**Comment by emorevival** [comment]
I was using it like `client.photo_upload(path='C:\\...01.jpg', caption="")`, and I also tried the other 2 methods I mentioned above. I ended up just `cd`ing into my folder from my script and then using relative paths.

**Comment by adw0rd** [comment]
Do you need to specify two slashes in windows, or I don’t know something?
`client.photo_upload(path='C:\Users\user\Desktop\project\01.jpg', caption="")`
can it work like that?

**Comment by adw0rd** [comment]
instead of a string, you must pass Path:

![image](https://user-images.githubusercontent.com/546889/113782689-41ef5280-973b-11eb-934c-23b377771af6.png)


`from pathlib import Path
client.photo_upload(path=Path('C:\Users\user\Desktop\project\01.jpg'), caption="")
`
