### ISSUE TITLE
ClientError: 500 Server Error: Internal Server Error

### ISSUE THREAD

**Issue by cukormentescukorka** [adw0rd/instagrapi#1305]
Hi,

I revisited one of my old projects today and got this error when trying to send a direct answer: `instagrapi.exceptions.ClientError: 500 Server Error: Internal Server Error for url: https://i.instagram.com/api/v1/direct_v2/threads/broadcast/text/`

I don't know what this exactly means or how to solve this as I did not find it here: [https://adw0rd.github.io/instagrapi/exceptions.html](url) 

Thanks

**Comment by birdhouses** [comment]
500 Server error means an internel server error with instagram. This could be due to anything, but I suspect that the URL you're making calls to has been deprecated. That means that you can't really do anything to fix it, because this is an issue with Instagram. Try to see if there is another endpoint available with the same functionality as this one.

**Comment by cukormentescukorka** [comment]
Thank you so much, have a good day.

**Comment by cukormentescukorka** [comment]
I've been trying to find one, but I did not really find anything since I do not fully understand what I'm looking for. Do you know any that I could try, and how to try? I am really sorry if I'm being annoying but I am very new to api-s.

**Comment by birdhouses** [comment]
I don't know the exact functionality of the request you mentioned earlier but I think this could be useful: https://adw0rd.github.io/instagrapi/usage-guide/direct.html 
I assume that the request you mentioned was used to send a message to many threads so to replicate that you could use:
To get all the threads in your inbox:
- direct_threads(amount: int = 20, selected_filter: str = "", thread_message_limit: Optional[int] = None)

then you could send a message to the desired threads using this:
- direct_send(text: str, user_ids: List[int] = [], thread_ids: List[int] = [])

so for example:
```
threads = client.direct_threads(amount=10, selected_filter="", thread_message_limit=10)

# Extract the thread IDs from the threads list
thread_ids = [thread.id for thread in threads]

# Send a message to the desired threads
client.direct_send(text="Cool message here", thread_ids=thread_ids)
```
Let me know if you need any more assistance, I'll try to help!

**Comment by cukormentescukorka** [comment]
Thanks I figured it out. I was accidentally giving it the message id-s not the thread id-s.
