### ISSUE TITLE
let you know Instagram's new challenge type error

### ISSUE THREAD

**Issue by nebula0225** [adw0rd/instagrapi#1307]
![image](https://user-images.githubusercontent.com/93500898/235056655-6153b052-e87c-40fd-bd03-20df645f423e.png)

to slove this challlenge just login web or mobile and click ok button 

this warning is notify you that your account is used in scraping

**Comment by nebula0225** [comment]
I found this error's solution 
Fix challenge.py file => IT WAS ME
Change to this please
`if step_name == "delta_login_review" or step_name == "scraping_warning":`

**Comment by adw0rd** [comment]
@nebula0225 send me your PR, I will check it and accept it

**Comment by nebula0225** [comment]
@adw0rd 
Hello
In response to your request, I sent a PR
