### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by musaib821** [adw0rd/instagrapi#1308]
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg' 
I am using replit app in Android... I tried  to install ffmpeg module but I got
RuntimeError: No ffmpeg exe could be found. Install ffmpeg on your system, or set the IMAGEIO_FFMPEG_EXE environment variable.
Now I installed entire ffmpeg in main directory but I got above error

**Comment by adw0rd** [comment]
This is not an instagrapi bug, read on the Internet how to install ffmpeg
