### ISSUE TITLE
[BUG] instagrapi.exceptions.PhotoNotUpload: {"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}

### ISSUE THREAD

**Issue by cuchorapido** [adw0rd/instagrapi#1309]
### Compensate with donations ($15 and more) for the time I spent to fix problems or send me your [Pull Request](https://github.com/adw0rd/instagrapi/pulls) with fixes

[![Donate](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/adw0rd)

* Tron TRX/USDT: `TLprxuzHjXPkHYa7ZfTTt165p7Fphwy1Ee`
* Bitcoin: `bc1qmp7538hktvg2gx994hrpkmsmyjc03q29awe9ra`
* Ethereum: `0x0E674815d513d4a00F6a7Cd4A990807aB97cC70D`
* Dogecoin: `DSEXzMBYhBTwhNqzPGxVWFsTqVsTCeDejo`

**Describe the bug**
I am using this script to try to post a picture on instagram it worked on the past, the picture is 1024x1024 and 3.0MB  

```
from instagrapi import Client
import sys
import os

def post_image(image_path, username, password, caption):
    cl = Client(request_timeout=7)
    cl.login(username, password)
    cl.photo_upload(image_path, caption)

if __name__ == "__main__":
    image_path = sys.argv[1]
    username = sys.argv[2]
    password = sys.argv[3]
    caption = sys.argv[4]
```

**To Reproduce**
`python3 post-ig.py posted/1.png "myusername" "mypassword" "good bye".`
**(while waiting to run i am checking in the instagram app to allow new devices to log in and manually approve)**

```
**Traceback**
Status 429: Too many requests
Ignore 429: Continue login   
Photo Upload failed with the following response: <Response [400]>
Traceback (most recent call last):
  File "/home/ubuntu/twitch-content/1805097782/audios/text-parts/post-ig.py", line 16, in <module>
    post_image(image_path, username, password, caption)
  File "/home/ubuntu/twitch-content/1805097782/audios/text-parts/post-ig.py", line 8, in post_image
    cl.photo_upload(image_path, caption)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/instagrapi/mixins/photo.py", line 228, in photo_upload
    upload_id, width, height = self.photo_rupload(path, upload_id)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/instagrapi/mixins/photo.py", line 190, in photo_rupload
    raise PhotoNotUpload(response.text, response=response, **last_json)
instagrapi.exceptions.PhotoNotUpload: {"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}
```

**Expected behavior**
upload a picture on instagram

**Screenshots**
![image](https://user-images.githubusercontent.com/109241660/235216789-37bf8037-c0b4-48b8-84d1-3b89ad9799c6.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Python version 3.10
 - instagrapi version 1.17.3 and 1.17.6
 - moveipy version if used
 - imagemagick version if used

**Additional context**

**Comment by cuchorapido** [comment]
any ideas?

**Comment by adw0rd** [comment]
@cuchorapido yes, use the search on Issue and Discussions

**Comment by adw0rd** [comment]
https://github.com/adw0rd/instagrapi/issues?q=PhotoNotUpload

https://github.com/adw0rd/instagrapi/discussions?discussions_q=PhotoNotUpload
