### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by C0DEn1s** [adw0rd/instagrapi#132]
I used the API 2 months ago and everything went fine, but now I encountered an error while logging _"requests.exceptions.HTTPError: 400 Client Error: Invalid request for url: https://i.instagram.com/api/v1 / accounts / login / "_ and _"instagrapi.exceptions.SentryBlock: Sorry, there was a problem with your request. "_ I am assuming that Instagram has blocked my device because I cannot use it for different accounts. But logging into the site manually is fine. What is the problem?

**Comment by adw0rd** [comment]
https://github.com/adw0rd/instagrapi/issues?q=SentryBlock

**Comment by adw0rd** [comment]
Change your IP and device / uuids
