### ISSUE TITLE
[BUG] method_whitelist argument need to be changed into allowed_methods

### ISSUE THREAD

**Issue by mesutfd** [adw0rd/instagrapi#1321]
instagrapi/mixins/private.py
line 87:
TypeError: Retry.__init__() got an unexpected keyword argument 'method_whitelist'

this line:
method_whitelist=["GET", "POST"],

needs to be changed into this:
allowed_methods=["GET", "POST"],

and its working perfectly fine.

**Comment by mesutfd** [comment]
method_whitelist init error

**Comment by VadyChel** [comment]
I got the same bug

**Comment by adw0rd** [comment]
@VadyChel send me PR with fixes this issue

**Comment by MazrimT** [comment]
same thing needs to be changed in instagrapi/mixins/public.py

**Comment by yotrew** [comment]
pip install requests==2.29.0
