### ISSUE TITLE
Expose max_id in user_followers API

### ISSUE THREAD

**Issue by flatplate** [adw0rd/instagrapi#136]
Getting all of the followers of a user in one go is not practical for users with a lot of followers. Exposing the `max_id` used in the internal `user_followers` would make it easier to continue from where it was left at a later point. This would be useful for getting different followers each time the code is run. 

That being said I am not sure if this would work, or how long the max_id is valid.

**Comment by adw0rd** [comment]
@flatplate I have implemented `user_followers_v1_chunk` which will give a list of users and max_id

However, Instagram via the private API (mobile app) stopped giving out all followers, it gives out a maximum of 200 users, it is considered that you no longer need to give

But the web api still gives all followers, I will try to implement the method based on it

**Comment by adw0rd** [comment]
@flatplate added `user_followers_gql_chunk` and `user_followers_gql`, which give out a full list of followers through the web api, while `user_followers_gql_chunk` also gives out a `cursor` (alternative of `max_id`), you can set some `max_amount` (for example, 100) and get a `cursor`, later use it to continue the selection
