### ISSUE TITLE
downloading highlights

### ISSUE THREAD

**Issue by enakhi** [adw0rd/instagrapi#1364]
Hello,

I am experiencing an error while attempting to download highlights using the highlight  link provided. The specific error message I receive is as follows:

AssertionError: URL must contain "/highlights/"

Here is the link I am using:
https://www.instagram.com/s/aGlnaGxpZ2h0OjE3ODc3MjExMTY5NDIzMzE4?story_media_id=2610133240251375492_40437575235&igshid=MzRlODBiNWFlZA==

Could you kindly assist me in resolving this issue? I would greatly appreciate any guidance or solution you can provide.

Thank you for your attention and assistance.

**Comment by adw0rd** [comment]
https://www.instagram.com/s/ - share URL, not highlight

https://github.com/adw0rd/instagrapi/blob/master/instagrapi/mixins/share.py

**Comment by enakhi** [comment]
but when i copy the link of highlight,this will appear in my clipboard

**Comment by enakhi** [comment]
How do I download a share link?

**Comment by adw0rd** [comment]
https://github.com/adw0rd/instagrapi/blob/master/instagrapi/mixins/share.py
