### ISSUE TITLE
Support Upload Multiple Image

### ISSUE THREAD

**Issue by ardinusawan** [adw0rd/instagrapi#1365]
**Is your feature request related to a problem? Please describe.**
In this function `photo_upload` has a way to publish multiple image?

**Describe the solution you'd like**
```
photo_upload(
    ["file_path1", "file_path2"],
```

**Describe alternatives you've considered**
-

**Additional context**
- Here https://adw0rd.github.io/instagrapi/usage-guide/media.html in Upload Media looks like we don't have it

**Comment by adw0rd** [comment]
It's called an album, read the documentation about it

https://adw0rd.github.io/instagrapi/usage-guide/media.html

https://github.com/adw0rd/instagrapi/blob/master/instagrapi/mixins/album.py
