### ISSUE TITLE
Is any way to getting uploaded photo/album URL

### ISSUE THREAD

**Issue by ardinusawan** [adw0rd/instagrapi#1368]
**Is your feature request related to a problem? Please describe.**
in this function `.photo_upload` or `.album_upload` is any way to getting upload url from the return?

**Describe the solution you'd like**
media = cl.photo_upload()
media.url

**Describe alternatives you've considered**
Or anyway to getting url from media_id or media_pk?

**Additional context**
- nope

**Comment by adw0rd** [comment]
Print `media.dict()` and see all attributes

https://github.com/adw0rd/instagrapi/blob/master/instagrapi/types.py#L119

https://github.com/adw0rd/instagrapi/blob/master/instagrapi/types.py#L132

**Comment by ardinusawan** [comment]
That is thumbnail url and video url, is there any way for getting feed url?
