### ISSUE TITLE
Get thread_id by user_id

### ISSUE THREAD

**Issue by edisax** [adw0rd/instagrapi#137]
Would be great implement a way to search for user_id and get a thread_id.
The option is available if you go do the DM section in the IG app and search for a specific user, you will get to a thread no matter
if a previous conversation is available or not.
Thank you.

**Comment by adw0rd** [comment]
@edisax added Client.direct_search(query)
where query is string, example username, maybe it will be useful

**Comment by edisax** [comment]
Great thanks!
I noticed that it works great on 2 of my accounts but one of them is verified so it's making other requests when searching for a user and opening a thread.
Here is the GET request done:
https://i.instagram.com/api/v1/direct_v2/threads/get_by_participants/?recipient_users=%5B13154671%5D&seq_id=2580572&limit=20

Possible to add that to?
Thanks!

**Comment by edisax** [comment]
Do you have time to add this feature? Would be grateful for it. Looks like it's same request for all business accounts. The method you did works great for private accounts :)

**Comment by adw0rd** [comment]
@edisax I'll take a look this today )

**Comment by adw0rd** [comment]
@edisax please check cl.direct_thread_by_participants
