### ISSUE TITLE
Logging in by session id but cant upload media

### ISSUE THREAD

**Issue by jgore077** [adw0rd/instagrapi#1386]
This script below can be used to replicate the issue
```
from instagrapi import Client

SESH_ID="Your session id"
VID        ="Test video path"
client =Client()
cl.login_by_sessionid(SESH_ID)
client.video_upload(VID,"Test")
client.logout()
```
I was Logging in with the session_id cookie from the web-browser in which I am logged in.

The login_by_sessionid method threw no errors but upon reaching the video upload method this error was thrown.
``
 raise LoginRequired(response=e.response, **last_json)
instagrapi.exceptions.LoginRequired: login_required
``

This may be a bug or perhaps I am providing the wrong session_id/using the method incorrectly.

**Comment by adw0rd** [comment]
Instagram suspects you and asks you to log in with your username and password

**Comment by jgore077** [comment]
> Instagram suspects you and asks you to log in with your username and password

Is there any way to get unsuspected? I could always catch the error but logging in by session id is super convenient.

Do you have alternative methods with less chance of getting flagged?

**Comment by adw0rd** [comment]
Not yet, but if you find one, please share it with us

**Comment by luisadrianpuga** [comment]
same issue here. I had to create a new account and sign in using username (not email) and password. This let me log in and it's crucial to do the dump best practice to stay logged in.
