### ISSUE TITLE
[BUG] `Pillow` missing as a requirement

### ISSUE THREAD

**Issue by goekce** [adw0rd/instagrapi#1394]
**Describe the bug**
Pillow is missing in the requirements.

**To Reproduce**
`pip install instagrapi` on a machine without `Pillow` and run the first example.

**Traceback**

```
...
    from instagrapi import Client
  File "/home/u/apps/insta/venv/lib/python3.11/site-packages/instagrapi/__init__.py", line 12, in <module>
    from instagrapi.mixins.clip import DownloadClipMixin, UploadClipMixin
  File "/home/u/apps/insta/venv/lib/python3.11/site-packages/instagrapi/mixins/clip.py", line 18, in <module>
    raise Exception("You don't have PIL installed. Please install PIL or Pillow>=8.1.1")
Exception: You don't have PIL installed. Please install PIL or Pillow>=8.1.1
```

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Python version 3.11.3
 - instagrapi version 1.17.10

---

Feel free to close this issue if `Pillow` is an optional requirement.

**Comment by adw0rd** [comment]
Not all clients of this library need Pillow (most of the functions work without it), and some cannot build it on their environment

**Comment by paboum** [comment]
https://github.com/subzeroid/instagrapi/blob/712caea5739a17ef96a3ec3849eddfadf049c205/instagrapi/mixins/clip.py#L18
