### ISSUE TITLE
Getting Feed URL after success upload Feed

### ISSUE THREAD

**Issue by ardinusawan** [adw0rd/instagrapi#1406]
## Is your feature request related to a problem? Please describe.
in this function .photo_upload or .album_upload is any way to getting upload url from the return?

There is media.dict() and there is attributes thumbnail url and video url. I want it has feed url. Is it possible?

- https://github.com/adw0rd/instagrapi/blob/master/instagrapi/types.py#L119

- https://github.com/adw0rd/instagrapi/blob/master/instagrapi/types.py#L132

## Describe the solution you'd like
media = cl.photo_upload()
media.feed_url

## Describe alternatives you've considered
Or anyway to getting url from media_id or media_pk?

## Additional context

nope

**Comment by adw0rd** [comment]
I think you need `media.code`

Or send your PR with improvements
