### ISSUE TITLE
Getting very less posts per request in hashtags media endpoint

### ISSUE THREAD

**Issue by patilaum** [adw0rd/instagrapi#1440]
Thanks for Lamadava Saas first of all.

**Describe the bug**
In the endpoint `/v1/hashtag/medias/recent/chunk` earlier we used to get 27 posts (also thats the default value of `max_amount` in lamadava api docs). However, now I am just getting 9 (sometimes only 5) posts in single request. Not sure why this is happening.
Also why does it return unequal number of post every time we run it.

**Comment by patilaum** [comment]
Also not getting what exactly is to be used as `max_id`  in `/v1/hashtag/medias/recent/chunk . Can you please give me the right usage of max_id?

**Comment by adw0rd** [comment]
> However, now I am just getting 9 (sometimes only 5) posts in single request.

We respond AS IS from instagram server

**Comment by adw0rd** [comment]
> Also not getting what exactly is to be used as `max_id` in `/v1/hashtag/medias/recent/chunk . Can you please give me the right usage of max_id?

`max_id` is returned with the response (second attr) to the request, this is the ID for moving to the next page

**Comment by patilaum** [comment]
Hey @adw0rd 
Thanks for clearing this. Closing it.
