### ISSUE TITLE
[BUG] edit profile picture

### ISSUE THREAD

**Issue by 6ky** [adw0rd/instagrapi#1456]
### Compensate with donations ($15 and more) for the time I spent to fix problems or send me your [Pull Request](https://github.com/adw0rd/instagrapi/pulls) with fixes

[![Donate](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/adw0rd)

* Tron TRX/USDT: `TLprxuzHjXPkHYa7ZfTTt165p7Fphwy1Ee`
* Bitcoin: `bc1qmp7538hktvg2gx994hrpkmsmyjc03q29awe9ra`
* Ethereum: `0x0E674815d513d4a00F6a7Cd4A990807aB97cC70D`
* Dogecoin: `DSEXzMBYhBTwhNqzPGxVWFsTqVsTCeDejo`

**Describe the bug**
error on account change picture

**To Reproduce**
Provide a piece of code to reproduce the problem.
cl.account_change_picture(pathtoprofilepicture)

**Traceback**
Show your full traceback so that it is clear where exactly the error occurred.
Photo Upload failed with the following response: <Response [400]>
Traceback (most recent call last):
  File "automate.py", line 29, in <module>
    cl.account_change_picture(pathtoprofilepicture)
  File "Python38\site-packages\instagrapi\mixins\account.py", line 199, in account_change_picture   
    upload_id, _, _ = self.photo_rupload(Path(path))
  File "\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\instagrapi\mixins\photo.py", line 190, in photo_rupload
    raise PhotoNotUpload(response.text, response=response, **last_json)
instagrapi.exceptions.PhotoNotUpload: {"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}

**Expected behavior**
update pfp

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 21.04]
 - Python version [e.g. 3.8.3]
 - instagrapi version [e.g. 1.9.3, not "latest"]
 - moveipy version if used
 - imagemagick version if used

everything latest

**Additional context**

**Comment by 6ky** [comment]
Solved, it was due to instagram only allowing jpg/jpeg. Error handling should be added for this.

**Comment by adw0rd** [comment]
@6ky can you add an exception when a non-jpeg is passed?

**Comment by 6ky** [comment]
> 

in the src of instagrapi? I will have a look and let you know

**Comment by 6ky** [comment]
@adw0rd https://github.com/adw0rd/instagrapi/pull/1471 yw! If possible look into the enhancement I have opened.
