### ISSUE TITLE
[BUG] Caption not Uploading on reel

### ISSUE THREAD

**Issue by 6ky** [adw0rd/instagrapi#1473]
### Compensate with donations ($15 and more) for the time I spent to fix problems or send me your [Pull Request](https://github.com/adw0rd/instagrapi/pulls) with fixes

[![Donate](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/adw0rd)

* Tron TRX/USDT: `TLprxuzHjXPkHYa7ZfTTt165p7Fphwy1Ee`
* Bitcoin: `bc1qmp7538hktvg2gx994hrpkmsmyjc03q29awe9ra`
* Ethereum: `0x0E674815d513d4a00F6a7Cd4A990807aB97cC70D`
* Dogecoin: `DSEXzMBYhBTwhNqzPGxVWFsTqVsTCeDejo`

**Describe the bug**
The caption is not uploading with the reel

**To Reproduce**
Provide a piece of code to reproduce the problem.
media = cl.clip_upload(path=file, caption=caption)

**Traceback**
Show your full traceback so that it is clear where exactly the error occurred.
no error:

**Expected behavior**
reel upload with caption

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 21.04]
 - Python version [e.g. 3.8.3]
 - instagrapi version [e.g. 1.9.3, not "latest"]
 - moveipy version if used
 - imagemagick version if used

**Additional context**

**Comment by adw0rd** [comment]
The caption is a comment in instagram, apparently Instagram temporarily blocked you, usually commenting, likes, following do not work after that

Wait a few hours or maybe days and try again

**Comment by adw0rd** [comment]
But if you are sure that this is a bug, then help fix it! 🙏

**Comment by 6ky** [comment]
> The caption is a comment in instagram, apparently Instagram temporarily blocked you, usually commenting, likes, following do not work after that
> 
> Wait a few hours or maybe days and try again

Yep it was this. Thanks.
