### ISSUE TITLE
Поделиться профилем в директ

### ISSUE THREAD

**Issue by orchestrah** [adw0rd/instagrapi#150]
Здравсвуйте. Существует ли метод для того что бы поделиться профилем в директ ? 
Ссылка на профиль в send_message не форматируется так красиво.

**Comment by adw0rd** [comment]
There is no such method yet, but you can implement it
Or you will need to wait 2-3 weeks until I get free from my main job

Такого метода ешё нет, но вы можете его реализовать
Либо нужно будет подождать 2-3 недели, пока я не освобожусь от основной работы

**Comment by orchestrah** [comment]
Попробую сделать. По поводу снятия пиннинга facebook whitehat settings срабоатет? или нужно снимать его руками ?

**Comment by adw0rd** [comment]
@orchestrah думаю поможет

**Comment by adw0rd** [comment]
@orchestrah сделали метод?)

**Comment by adw0rd** [comment]
Implemented in #99
