### ISSUE TITLE
[BUG] cl.user_stories(id) ERROR 500

### ISSUE THREAD

**Issue by velas02** [adw0rd/instagrapi#1501]

**Comment by adw0rd** [comment]
What is passed in `id`?
And also show traceback

**Comment by velas02** [comment]
In some instagram accounts I get a challenge and in others I don't. What is it due to and is it a bug to be resolved or is it something normal?

**Comment by adw0rd** [comment]
This is not an instagrapi bug, instagram likes to push the challenge, you just need to make fewer requests and pretend to be a real user
