### ISSUE TITLE
I keep getting Unauthorized: Please wait a few minutes before you try again.

### ISSUE THREAD

**Issue by diegotrasobares** [adw0rd/instagrapi#1503]
Hey! Firstly, thanks for this amazing tool, I've been having a ton of fun with it!!
I'm trying just to get `"user_info"` from ID of users. It starts smoothly but when it reaches a few accounts it always gets "banned".
I already tried setting up delays between every request, I have also implemented session login to avoid the re-login and also tried to implement different proxies from Bright Data.
In all cases, I'm getting "banned" and I have to wait a long time to do any request again, even If I change proxy. Most of the time when this happens, my Instagram account looks fine and It's not down or something.

The error I always get is: `instagram_private_api.errors.ClientError: Unauthorized: Please wait a few minutes before you try again.
`

What are you guys using to avoid this? Any tips for me?
Thanks all in advance!!

**Comment by vaibhavkansal** [comment]
did you find the solution

**Comment by wytex** [comment]
Here same..

**Comment by adw0rd** [comment]
Try [Lamadava API](https://lamadava.com/p/3msyAKDX) with a free period to receive data, inside the same instagrapi, but with the accounts and proxies we bought

**Comment by diezo** [comment]
Do you get similar error when using [ensta](https://github.com/diezo/ensta)?

Here's the code:
```py
from ensta import AutoHost

host = AutoHost(username, password, file="session.txt")
host.follow("cristiano")
profile = host.profile("cristiano")

if profile is not None:
    print(profile.followers)
    print(profile.followings)
```

**Comment by hichemmezemate** [comment]
Did you find a solution for this ?

**Comment by Altimis** [comment]
Hi Guys. Any update about this issue please ?
