### ISSUE TITLE
[BUG] DEBUG: https://i.instagram.com:443 "POST /api/v1/media/configure/ HTTP/1.1" 500 51

### ISSUE THREAD

**Issue by adminha** [adw0rd/instagrapi#1505]
When I try to post a photo, it keeps getting this error message:

> 2023-08-02 16:44:40,006.006 DEBUG: https://i.instagram.com:443 "POST /rupload_igphoto/1690982078177_0_4344186225 HTTP/1.1" 200 64
> 2023-08-02 16:44:40,007.007 INFO: user [200] POST https://i.instagram.com/rupload_igphoto/1690982078177_0_4344186225 (269.0.0.18.75, OnePlus 6T Dev)
> 2023-08-02 16:44:40,008.008 DEBUG: Attempt #0 to configure Photo: C:\Users\Me\Desktop\Folder\unsplash_temp.jpg
> 2023-08-02 16:44:44,025.025 INFO: https://i.instagram.com/api/v1/media/configure/
> 2023-08-02 16:44:44,027.027 DEBUG: Resetting dropped connection: i.instagram.com
> 2023-08-02 16:44:46,072.072 DEBUG: https://i.instagram.com:443 "POST /api/v1/media/configure/ HTTP/1.1" 500 51
> 2023-08-02 16:44:46,074.074 DEBUG: Incremented Retry for (url='/api/v1/media/configure/'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
> 2023-08-02 16:44:47,156.156 DEBUG: Retry: /api/v1/media/configure/
> 2023-08-02 16:44:48,158.158 DEBUG: https://i.instagram.com:443 "POST /api/v1/media/configure/ HTTP/1.1" 500 51
> 2023-08-02 16:44:48,160.160 DEBUG: Incremented Retry for (url='/api/v1/media/configure/'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
> 2023-08-02 16:44:49,164.164 DEBUG: Retry: /api/v1/media/configure/
> 2023-08-02 16:44:50,155.155 DEBUG: https://i.instagram.com:443 "POST /api/v1/media/configure/ HTTP/1.1" 500 51
> 2023-08-02 16:44:50,155.155 DEBUG: Incremented Retry for (url='/api/v1/media/configure/'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
> 2023-08-02 16:44:51,161.161 DEBUG: Retry: /api/v1/media/configure/
> 2023-08-02 16:44:51,831.831 DEBUG: https://i.instagram.com:443 "POST /api/v1/media/configure/ HTTP/1.1" 500 51

Here is my class:

```
class Instagram:
    def __init__(self):
        self.cl = Client()
        
    def post_instagram_photo(self, img, caption):
        cl = self.cl
        cl.login('user', 'pass')
        path = os.path.abspath(os.path.join(os.getcwd(), img))
        print(path)
        cl.photo_upload(path, caption)
```

And here is the printed path:

> C:\Users\Me\Desktop\Folder\unsplash_temp.jpg

Is there something wrong with the configure URL?

**Comment by adw0rd** [comment]
print at the end of `cl.last_json`:

```python
print(cl.last_json)
print(cl.last_response.content)
```

**Comment by adminha** [comment]
it's empty after photo upload

**Comment by adminha** [comment]
it's fixed now, the problem was because of bad formatting of the caption. I was trying to pass an object instead of a text as the caption. fixed now. thanks.

**Comment by adminha** [comment]
> it's fixed now, the problem was because of bad formatting of the caption. I was trying to pass an object instead of a text as the caption. fixed now. thanks.

I'm closing the issue now. thank you for this great tool.

**Comment by adminha** [comment]
> it's fixed now, the problem was because of bad formatting of the caption. I was trying to pass an object instead of a text as the caption. fixed now. thanks.

I'm closing the issue now. thank you for this great tool.
