### ISSUE TITLE
 doubt at login

### ISSUE THREAD

**Issue by velas02** [adw0rd/instagrapi#1508]
How can I make instagram trust my login. Every time I use the login function, it detects it as misuse and forces me to reset the password after logging out.

**Comment by adw0rd** [comment]
For my hundreds of accounts, I always log in from one device and Instagram never offers me to change the password or something like that

https://adw0rd.github.io/instagrapi/usage-guide/interactions.html

https://adw0rd.github.io/instagrapi/usage-guide/best-practices.html
