### ISSUE TITLE
[BUG] ChallengeResolve: Unknown step_name "ufac_www_bloks"

### ISSUE THREAD

**Issue by jiangcheng1214** [adw0rd/instagrapi#1520]
Looks like my account has been blocked?
Login issue with following error message:

**ChallengeResolve: Unknown step_name "ufac_www_bloks" for "u*******q" in challenge resolver: {'step_name': 'ufac_www_bloks', 'step_data': {'screen_data': '{"screen_output_payload":{}}'}, 'flow_render_type': 7, 'bloks_action': 'com.bloks.www.checkpoint.ufac', 'challenge_context': '{"step_name": "ufac_www_bloks", "is_stateless": false, "challenge_type_enum": "UFAC_WWW_BLOKS", "present_as_modal": false}', 'challenge_type_enum_str': 'UFAC_WWW_BLOKS', 'status': 'ok'}**

**Comment by PurpleTape** [comment]
Hello @jiangcheng1214! How did you solve this?
