### ISSUE TITLE
recent version can't work hashtag public requests

### ISSUE THREAD

**Issue by nebula0225** [adw0rd/instagrapi#1524]
When i upgrade to recent version 
hashtag_medias_a1_chunk() This method is changed 
It works looks like private requests

error screentshot
![화면 캡처 2023-08-11 002047](https://github.com/adw0rd/instagrapi/assets/93500898/fabc8c8c-817f-43bb-9881-2040dfa6289a)

But downgrade to 1.18.2 version is working

**Comment by adw0rd** [comment]
@nebula0225 fixed `instagrapi 1.19.7`

```python
>>> cl.hashtag_medias_a1_chunk("love", tab_key="top")
([Media(pk='3170622896158277224', id='3170622896158277224_3057857058', code='CwAULmyO_5o', taken_at=datetime.datetime(2023, 8, 16, 12, 15, 51, tzinfo=datetime.timezone.utc), media_type=2, ...
```
