### ISSUE TITLE
[BUG] Infinite loop in ssl.py, status code 560

### ISSUE THREAD

**Issue by MataloDeEiras** [adw0rd/instagrapi#1540]
Currently, instagrapi is not working due to an infinite loop in ssl.py, where it is unable to exit the loop due to always receiving a status code of 560. This occurs using Client.user_medias(), but I suspect it would be the same with other functions. Logging to Instagram worked properly.

**Comment by adw0rd** [comment]
instagrapi does not contain `ssl.py`, please show your traceback
