### ISSUE TITLE
[Question] Unknown device issues when trying to setup as a Galaxy S21

### ISSUE THREAD

**Issue by Steelio** [adw0rd/instagrapi#1542]
First off let me apologize for posting this if it is a silly question, and or the wrong place.

So, I set all my device parameters;
```
deviceSet = {
            "app_version": "269.0.0.18.75",
            "android_version": 30,
            "android_release": "11.0.0",
            "dpi": "480dpi",
            "resolution": "1080x2400",
            "manufacturer": "Samsung",
            "device": "Galaxy S21",
            "model": "SM-G991B",
            "cpu": "snapdragon",
            "version_code": "314665256"
        }
        user_agent = f'Instagram {deviceSet["app_version"]} Android ({deviceSet["android_version"]}/{deviceSet["android_release"]}; {deviceSet["dpi"]}; {deviceSet["resolution"]}; {deviceSet["manufacturer"]}; {deviceSet["device"]}; {deviceSet["model"]}; {deviceSet["cpu"]}; en_US; {deviceSet["version_code"]})'
        #UA Translates to: "Instagram 269.0.0.18.75 Android (30/11.0.0; 480dpi; 1080x2400; Samsung; Galaxy S21; SM-G991B; snapdragon; en_US; 314665256)"
        cl = Client()
        cl.set_country('US')
        cl.set_country_code(1)
        cl.set_locale('en_US')
        cl.set_timezone_offset(-21600)
        cl.set_user_agent(user_agent)
        cl.set_device(device = deviceSet)
```
        
 However, Instagram still registers it as an unknown device. I am trying to make the profile of a Galaxy s21, and I just cant seem to figure out what I messed up or am forgetting.
 
 Thank you for any help! ♥

**Comment by Steelio** [comment]
Edit: Fixed.

**Comment by JorgeGAGR** [comment]
How did you fix this issue?

**Comment by Steelio** [comment]
> How did you fix this issue?

I believe it just dealt with my formatting for my device settings.
If i am not mistaken, I was just passing the args incorrectly. 
(So if you're having this issue, take a look there, make sure everything is formatted/passed properly.)

Sorry my response isn't of much help directly.

**Comment by unl1kely** [comment]
how can I get the profile of my android device like you did?
