### ISSUE TITLE
how to force image resolution

### ISSUE THREAD

**Issue by Nexuss05** [adw0rd/instagrapi#168]
I would like to know if there is a code string where it forces the maximum resolution of the photo (1080x1080) before uploading the photo on Instagram. i am using this simple code:

``` python
from instagrapi import Client
bot = Client()
bot.login("usr", "psw")

album_path = "image1.jpg", "image2.jpg", "image3.jpg", "image4.jpg"]
text =  "text"

bot.album_upload(
album_path,
caption = text
)
```

for example, the images I upload have a resolution of 1300x1300 (for example) I would like the program to automatically transform them to 1080x1080

Thanks for your help!

**Comment by adw0rd** [comment]
@Nexuss05 
``` python
from PIL import Image

im = Image.open('image1.jpg')
im = im.resize((1080, 1080))
im.save(open('image1_.jpg', 'w'))
im.close()
```
