### ISSUE TITLE
Add "unsend message" DM

### ISSUE THREAD

**Issue by edisax** [adw0rd/instagrapi#172]
Would be great feature to add the "unsend" message function to be able to retrieve and then re-send messages if the receiver didn't reply to the message.
Thanks!

**Comment by adw0rd** [comment]
Added to 1.7.8

```
>>> cl.direct_thread_mark_unread(340282366841710301949128122292511813703)
True
```

**Comment by adw0rd** [comment]
Added cl.direct_message_delete to 1.7.9

```
>>> cl.direct_message_delete(340282362841710300949128236601599431157, 29319738514177233899691938718593024)
True
```
