### ISSUE TITLE
insightAccount

### ISSUE THREAD

**Issue by rhatami7495** [adw0rd/instagrapi#173]
hi.how to get doc_id and set for api ads/graphql/?

**Comment by adw0rd** [comment]
For example, you can dump requests through ProxyMan or [Charles](https://adw0rd.com/2020/03/26/sniffing-instagram-charles-proxy/)

But why do you need it? Everything is already implemented in https://adw0rd.github.io/instagrapi/usage-guide/insight.html

**Comment by rhatami7495** [comment]
![error](https://user-images.githubusercontent.com/17021588/118726952-45502080-b847-11eb-9acf-ece04c8cdfc4.png)
When I use Charles , it gets a binary result for Instagram api. What do you think I should do?

**Comment by adw0rd** [comment]
@rhatami7495 have you turned on Whitehat Settings? 
![image](https://user-images.githubusercontent.com/546889/118782283-a2bf8e00-b896-11eb-8f0e-c07c9bd10637.png)

**Comment by adw0rd** [comment]
Does instagram give you response headers?
If only body is binary, then is there any mention of zstd compression in the headers?

![image](https://user-images.githubusercontent.com/546889/118792454-56794b80-b8a0-11eb-9a19-5f1040694a21.png)


![image](https://user-images.githubusercontent.com/546889/118792417-4e211080-b8a0-11eb-90ac-f95ea95e5740.png)

**Comment by adw0rd** [comment]
And install zstd tool. For macos:

`brew install zstd`

```
$ cat ~/response.bin
eDʔ�I��mWv��̤C'wV�z'$(�|�s�ߜ�is6@.*vC{v	|�w3���

$ zstdcat ~/response.bin
{"friendship_status":{"following":false,"followed_by":false,"blocking":false,"muting":false,"is_private":false,"incoming_request":false,"outgoing_request":false,"is_bestie":false,"is_restricted":false},"status":"ok"}
````

**Comment by adw0rd** [comment]
Or for install python package `pip install zstd`

``` python
import zstd, json
json.loads(zstd.decompress(open('/tmp/response.bin', 'rb').read()).decode())
```

**Comment by rhatami7495** [comment]
> Or install python package `pip install zstd`
> 
> ```python
> import zstd, json
> json.loads(zstd.decompress(open('/tmp/response.bin', 'rb').read()).decode())
> ```

**Comment by adw0rd** [comment]
@rhatami7495 just created for this https://github.com/adw0rd/zstdcat
