### ISSUE TITLE
Need help with Json Response in Charles (not sure!) 

### ISSUE THREAD

**Issue by git-avinash** [adw0rd/instagrapi#179]
First of all thanks for that amazing article and for introducing me to Charles @adw0rd . I've been literally trying to learn network reverse engineering forever now. Went through Burp, Fiddler, and what not and finally, Charles seems good!

Okay so now about my problem. Charles doesn't seem to decode bigger JSON responses properly.
Example 1 (Not Working):
![image](https://user-images.githubusercontent.com/61590601/119236556-b0566b80-bb55-11eb-9515-32f043e4dba5.png)

Example 2 (Working):
![image](https://user-images.githubusercontent.com/61590601/119236620-16db8980-bb56-11eb-875d-51fd4accc588.png)

I really love the amount of effort you have put into this! Hopefully, I can help you manage this project very soon.

**Comment by adw0rd** [comment]
@git-avinash Try to send this data to my [zstdcat](https://github.com/adw0rd/zstdcat)

```
pip install zstdcat
cat /tmp/response.bin | zstdcat
```

**Comment by adw0rd** [comment]
I also advise you to try [Proxyman](https://proxyman.io/), I like it better now

**Comment by git-avinash** [comment]
> I also advise you to try [Proxyman](https://proxyman.io/), I like it better now

I looked into it actually but it's only for mac os right? I got only windows.

**Comment by adw0rd** [comment]
> > I also advise you to try [Proxyman](https://proxyman.io/), I like it better now
> 
> I looked into it actually but it's only for mac os right? I got only windows.

I have a Mac, I don’t know if it works for other platforms :(

**Comment by git-avinash** [comment]
Yeah, I checked the website just now. Only for mac os. Charles seems to perform the best so far out of all the softwares that I've tried in the past. It's just that it's trial is very annoying. Let's me use only for 30mins and closes.

**Comment by adw0rd** [comment]
> Let's me use only for 30mins and closes.

You can always buy a license)
