### ISSUE TITLE
cl.ablum_upload throws instagrapi.exceptions.AlbumUnknownFormat

### ISSUE THREAD

**Issue by TunnelThruTime** [adw0rd/instagrapi#188]
Hello, 

In using ablum_upload to post carousal I've been thrown error. 
`j = click.edit()`
`k = ['abspath/fille1.JPG ', 'abspath/file2.jpg']`
`def blast():`
    `    cl.upload_album(
                                paths=k,
                                j)`

then the bit calling the function

above is  more or less the problematic bit of code, that throws the error.
Just wondering if aspect ratio, or anything else could be tripping up the procedure.
does the module support .jpg, .JPG, .JPEG, and .jpg? 

a quick look into ablum.py indicates that the function only takes .jpg, and .jpeg as extensions,
however modifying the files and the contents of list result in the same exception message. 
It;s slightly worth note that I'm only receiveing the exception and not an accompanying error message.

**Comment by adw0rd** [comment]
@TunnelThruTime I'll fix it today

**Comment by adw0rd** [comment]
Fixed
