### ISSUE TITLE
getting a user's followers

### ISSUE THREAD

**Issue by schaumju** [adw0rd/instagrapi#192]
For accounts with tons of followers, is there any way to speed up the process of compiling the followers such as multithreading it or something along those lines? 

This entire project is amazing!

**Comment by adw0rd** [comment]
@schaumju you can always use threading or multiprocessing

I deliberately did not make the code asynchronous, Instagram will not like it (there will be many parallel requests)

**Comment by schaumju** [comment]
That makes sense. How do you suggest going about making sure I do not make too many requests that result in a 429 error. I saw somewhere people suggesting to modify IP, but I'm not sure how to go about it. Again thank you so much for your help.

**Comment by adw0rd** [comment]
@schaumju use `cl.set_proxy`

https://adw0rd.github.io/instagrapi/usage-guide/interactions.html
