### ISSUE TITLE
Status 429: Too many requests + json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by CoLoR58** [adw0rd/instagrapi#195]
Hello!
Yesterday, the following code in the *.py script worked perfectly, without errors:
```
from instagrapi import Client
cl = Client()
cl.login(LOGIN, PASSWORD)
us = cl.user_medias_gql(xxx, 100, 4)
print(us)
```

Today I am running the same code and errors:

> **Status 429: Too many requests**
> Traceback (most recent call last):
>   File "D:\Python\inst\venv\lib\site-packages\instagrapi\mixins\public.py", line 125, in _send_public_request
>     return response.json() if return_json else response.text
>   File "D:\Python\inst\venv\lib\site-packages\requests\models.py", line 900, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "c:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "c:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "c:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "d:/Python/inst/2.py", line 4, in <module>
>     us = cl.user_medias_gql(669667765, 100, 4)
>   File "D:\Python\inst\venv\lib\site-packages\instagrapi\mixins\media.py", line 446, in user_medias_gql
>     data = self.public_graphql_request(
>   File "D:\Python\inst\venv\lib\site-packages\instagrapi\mixins\public.py", line 203, in public_graphql_request
>     body_json = self.public_request(
>   File "D:\Python\inst\venv\lib\site-packages\instagrapi\mixins\public.py", line 72, in public_request
>     raise e
>   File "D:\Python\inst\venv\lib\site-packages\instagrapi\mixins\public.py", line 65, in public_request
>     return self._send_public_request(url, **kwargs)
>   File "D:\Python\inst\venv\lib\site-packages\instagrapi\mixins\public.py", line 129, in _send_public_request
>     raise ClientLoginRequired(e, response=response)
> instagrapi.exceptions.ClientLoginRequired: Expecting value: line 1 column 1 (char 0)
> 
> Process finished with exit code 1

At the same time, if I run this code not through a py script, but in IDLE Python, then everything is fine:
```
>>> from instagrapi import Client
>>> cl = Client()
>>> cl.login('login', 'password')
Status 429: Too many requests
True
```

What can I do to fix this?
There was no mistake yesterday (Status 429: Too many requests)

Sorry for my English!

**Comment by adw0rd** [comment]
Instagram thinks that you have made too many requests to it, change your proxy (`cl.set_proxy`)

Works in IDLE because you are not doing `cl.user_medias_gql(xxx, 100, 4)`
