### ISSUE TITLE
Изображения в директ

### ISSUE THREAD

**Issue by V-ampire** [adw0rd/instagrapi#2]
Здравствуйте, я правильно понимая что отправка сообщений через директ не поддерживается?

**Comment by adw0rd** [comment]
@V-ampire поддерживается https://github.com/adw0rd/instagrapi/blob/master/instagrapi/direct.py#L74

**Comment by V-ampire** [comment]
Ой ой, я неправильно написал, хотел написать изображени.

**Comment by V-ampire** [comment]
> @V-ampire поддерживается https://github.com/adw0rd/instagrapi/blob/master/instagrapi/direct.py#L74

Ой ой, я неправильно написал, хотел написать изображений.

**Comment by adw0rd** [comment]
@V-ampire нет, но можно реализовать, до этого в этом небыло необходимости

**Comment by V-ampire** [comment]
> @V-ampire нет, но можно реализовать, до этого в этом небыло необходимости

Намек понял) Время будет поразбираюсь)

**Comment by Leraner** [comment]
Done
