### ISSUE TITLE
Challenge Issue

### ISSUE THREAD

**Issue by schaumju** [adw0rd/instagrapi#205]
I've been trying to look at followers of a given account and look at their data. Originally I created like 20 Instagram accounts and split the follower list into different threads. Each login had a different proxy which was rotated every 30 requests. 

After running the code like 2 times, my accounts started to raise instagrapi.exceptions.ChallengeRequired every time they were logged in. I attempted to look at the code to sort this out as I know you have examples. However, when I run the challenge resolver I still get the error. Any suggestions how to sort this out and in the future not have this happen? Thank you so much for the amazing repository.

**Comment by adw0rd** [comment]
@schaumju Changing proxies is often a bad idea, Instagram doesn't like when the IP address changes

What errors do you get?

**Comment by schaumju** [comment]
So you would advise just setting the proxy when I first login with an account and not changing it correct?

Typically the errors are with the login. The most common ones are:
- ChallengeRequired
- UnkownError
- RecaptchaChallengeForm

**Comment by adw0rd** [comment]
> So you would advise just setting the proxy when I first login with an account and not changing it correct?

Yes

**Comment by adw0rd** [comment]
@schaumju try https://github.com/adw0rd/instagrapi/blob/master/examples/handle_exception.py
