### ISSUE TITLE
Implement getting highlights

### ISSUE THREAD

**Issue by 97amigo** [adw0rd/instagrapi#215]
Hey, guys. It would be great to impelemt getting highlights. Thank's

**Comment by adw0rd** [comment]
Please sponsor the development of this feature if you need it.
**5 cups of coffee**

[![Donate](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/adw0rd)

**Comment by adw0rd** [comment]
Done getting a list of stories from highlight
