### ISSUE TITLE
reels upload problem

### ISSUE THREAD

**Issue by user-azad** [adw0rd/instagrapi#224]
when I try to upload reels it given an error as too many requests and reels doesn't get uploaded. Can you help me fix this. 
Also please do mention is there any daily limitations for using this will my Instagram account get banned if I use reels upload feature of this API. Is uploading content from this API **safe** .
please answer

**Comment by adw0rd** [comment]
@user-azad The upload is safe, but you must use the timings (sleeps) as if you were a regular user so that Instagram doesn't suspect you.

About [too many requests](https://github.com/adw0rd/instagrapi/issues?q=too+many+requests)
