### ISSUE TITLE
what about the (to many requests error which i get)

### ISSUE THREAD

**Issue by user-azad** [adw0rd/instagrapi#227]
@user-azad The upload is safe, but you must use the timings (sleeps) as if you were a regular user so that Instagram doesn't suspect you.

About [too many requests](https://github.com/adw0rd/instagrapi/issues?q=too+many+requests)

_Originally posted by @adw0rd in https://github.com/adw0rd/instagrapi/issues/224#issuecomment-869227664_

**Comment by adw0rd** [comment]
Answered here #226
