### ISSUE TITLE
Access Public data

### ISSUE THREAD

**Issue by Ranjeetjain** [adw0rd/instagrapi#233]
As per the documentation
```Public (anonymous request via web api) methods have a suffix _gql (Instagram GraphQL) or _a1 (example https://www.instagram.com/adw0rd/?__a=1)```
so to access any public user profile do i need to login ?

I am trying to perform something like
```bot = Client()
bot.user_info_gql(<user_id>)```

are there any better ways to access public information without login?


I want to scrape users (public account) post, story, reels, igtv and sidecar stories (carousel post)

**Comment by Ranjeetjain** [comment]
Found the solution 
bot.user_medias_gql(<user_di>, amount=10)
but the amount is max 50,

is there any work around to get more than 50 posts like getting 100 ?

**Comment by adw0rd** [comment]
@Ranjeetjain since this year, Instagram does not like anonymous (public) requests, so you need a lot of proxy IP addresses to make them
