### ISSUE TITLE
Update bio tagging user

### ISSUE THREAD

**Issue by dmunozv04** [adw0rd/instagrapi#263]
When updating the account's bio of an account tagging a user (like @/instagram) it doesn't make it available to click and only shows it as a string. 

The method used for updating the bio is: `account_edit`

**Comment by adw0rd** [comment]
@dmunozv04 thanks! I'll take a look this week

**Comment by zankoAn** [comment]
Why use " @/ "  in tagging? Just write the username, you do not need " / ".

**Comment by dmunozv04** [comment]
When tagging on Instagram I didn't use the /. I used it on GitHub so that it wouldn't ping that user. I'm sorry for not making that clear

**Comment by zankoAn** [comment]
> When tagging on Instagram I didn't use the /. I used it on GitHub so that it wouldn't ping that user. I'm sorry for not making that clear

I tried this and it worked properly, no problem!

`cl.account_edit(biography="@instagram")
`


![image](https://user-images.githubusercontent.com/45467643/126065300-8ef1b545-428b-4402-a7d6-6773ce968368.png)

and for multi tagging you can use "\n" like this:

`cl.account_edit(biography="@instagram\n@test1\n@test2")
`

![image](https://user-images.githubusercontent.com/45467643/126065368-efcff8a4-0d53-4b24-9cb8-e40e0ab33263.png)

**Comment by adw0rd** [comment]
@zankoAn in the web-browser the links are clickable, but in the Instagram application they are not
I think @dmunozv04 talked about this problem

**Comment by dmunozv04** [comment]
Exactly, the people tagged are not clickable on the Instagram apps when using the `account_edit` option but they were when I sent requests with Charles Proxy

**Comment by adw0rd** [comment]
@dmunozv04 implemented in instagrapi 1.9.7

**Comment by dmunozv04** [comment]
Thank you!
