### ISSUE TITLE
Similar hashtags not working

### ISSUE THREAD

**Issue by idhikash** [adw0rd/instagrapi#265]
Similar hashtags always returns empty list, please help sort this out

**Comment by adw0rd** [comment]
Instagram temporarily stopped providing data for this endpoint
I don't know when they will start returning data again

**Comment by idhikash** [comment]
> Instagram temporarily stopped providing data for this endpoint
> I don't know when they will start returning data again

is there any other way to do this?

**Comment by adw0rd** [comment]
@idhikash you need to crawl posts yourself and make hashtag relations, then mark the most related

**Comment by idhikash** [comment]
> @idhikash you need to crawl posts yourself and make hashtag relations, then mark the most related

alright thanks, can instagrapi get me banned? (I'm only using it for posting)

**Comment by adw0rd** [comment]
@idhikash I have been using several years for publishing posts and stories and I am not banned
