### ISSUE TITLE
Is there any way I share my post to my story?

### ISSUE THREAD

**Issue by atllokk** [adw0rd/instagrapi#270]
Hi!

Is there any way to share my post to my story like below?

![Artboard 1](https://user-images.githubusercontent.com/87631411/126103747-ba7cfc36-760e-4526-b1c7-f97828046e7d.jpg)

![Artboard 2](https://user-images.githubusercontent.com/87631411/126103755-3e87be97-a319-4b18-9c60-ec2ea9d2a71f.jpg)

Thank for the amazing work!

**Comment by adw0rd** [comment]
1. When you click on this button, the Instagram video editor starts, we have `StoryBuilder` for this
2. After building the video, you need to mark it up (mention. links, locations, hashtags) and upload it to the instagram server, for this there is `cl.video_upload_to_story`

More details here https://adw0rd.github.io/instagrapi/usage-guide/story.html
