### ISSUE TITLE
Like and Unlike features

### ISSUE THREAD

**Issue by gennaromellone** [adw0rd/instagrapi#28]
Hello all!
Is there a method to insert/remove like on a post, comment, etc?
Thank you all, and good job!

**Comment by adw0rd** [comment]
Hello, like/unlike was once implemented, but was removed as unnecessary. I can return)

Comment - https://github.com/adw0rd/instagrapi/blob/master/instagrapi/media.py#L222

**Comment by gennaromellone** [comment]
Thank you for fast answer!
Yes, if you can return like/unlike it would be really appreciated !!

**Comment by gennaromellone** [comment]
Hi @adw0rd if you could link me the old implemented part of code for like/unlike, I could create a function by myself! Thanks!

**Comment by adw0rd** [comment]
@gennaromellone done
