### ISSUE TITLE
Cannot login using Client.login()

### ISSUE THREAD

**Issue by Denosadchiy** [adw0rd/instagrapi#289]
I'm using Client.login(username, password) and get "LoginRequired: login_required" Error. I'm entering username and password absolutely correctly. Help me please with the problem.

**Comment by alicanyuksel** [comment]
Same issue, I can't login...

**Comment by adw0rd** [comment]
Show your code? And where is the traceback?

**Comment by alicanyuksel** [comment]
> Show your code? And where is the traceback?

The traceback was exactly the same with you. (https://github.com/adw0rd/instagrapi/issues/287#issuecomment-886188394)
But I upgraded the instagrapi version to 1.8.11. Problem resolved !

**Comment by adw0rd** [comment]
@alicanyuksel nice 👍
