### ISSUE TITLE
How to start using?

### ISSUE THREAD

**Issue by paradox70** [adw0rd/instagrapi#3]
Please add an example to show how to start and use this library.
How to login and save cookies to prevent relogin?
Thanks for this great warper.

**Comment by adw0rd** [comment]
```
cl = Client(settings)
# cl.set_proxy("socks5://127.0.0.1:30235")
cl.login(ACCOUNT_USERNAME, ACCOUNT_PASSWORD)

user_id = cl.user_id_from_username("adw0rd")
medias = cl.user_medias(user_id, 20)
```

There are many examples in tests https://github.com/adw0rd/instagrapi/blob/master/tests.py
In the near future I will add README

**Comment by adw0rd** [comment]
Cookie are stored as part of settings and specified next: https://github.com/adw0rd/instagrapi/blob/758c89bf8b85fe2a91ba40530349007d2d2760e1/tests.py#L39

**Comment by adw0rd** [comment]
```
cl = Client()
cl.login(username, password)
print(cl.get_settings())
```

**Comment by paradox70** [comment]
Thank for you reply,
I started using this library and I'm sure this is one the best one.
I will contribute to this project.

**Comment by adw0rd** [comment]
@paradox70 added more examples https://github.com/adw0rd/instagrapi
