### ISSUE TITLE
KeyError after user_info_by_username

### ISSUE THREAD

**Issue by pompushko** [adw0rd/instagrapi#302]
Cant get user info :(
Got **KeyError**

```
>>> instagram.user_info_by_username('Poliakov_tattoo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.7/site-packages/instagrapi/mixins/user.py", line 197, in user_info_by_username
    return self.user_info(self._usernames_cache[username])
KeyError: 'Poliakov_tattoo'
```

**Comment by adw0rd** [comment]
Thank you, I will decide it.
But now you can specify your username in lower case, as indicated in the Instagram profile

![image](https://user-images.githubusercontent.com/546889/127295826-9b5e9b53-e091-41b7-b507-adde88264288.png)

Спасибо, буду решать.
Cейчас ты можешь передать никнейм в нижнем регистре, как и указано в профиле инстаграм

**Comment by pompushko** [comment]
Or put .lower() ?

ср, 28 июл. 2021 г., 12:07 Mikhail Andreev ***@***.***>:

**Comment by adw0rd** [comment]
@pompushko fixed 1.9.2
