### ISSUE TITLE
location not showing

### ISSUE THREAD

**Issue by dheeraj009joshi** [adw0rd/instagrapi#304]
**Describe the bug**

**To Reproduce**
Provide a piece of code to reproduce the problem.

**Traceback**
Show your full traceback so that it is clear where exactly the error occurred.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 21.04]
 - Python version
 - instagrapi version
 - moveipy version if used
 - imagemagick version if used

**Additional context**

**Comment by adw0rd** [comment]
@dheeraj009joshi you did not fill in any of the fields, I am waiting for you to provide data (source code to reproduce, traceback, screenshots, additional context such as region) to solve the problem
