### ISSUE TITLE
Story Mention

### ISSUE THREAD

**Issue by HelloTan** [adw0rd/instagrapi#31]
I got a problem when uploading the story and then mentioning, there was no writing when someone saw the story, but the mention was successful, it's just that someone couldn't click the mention because there was no writing / name of the person mentioned

**Comment by adw0rd** [comment]
@HelloTan publish a story and give me a link to it

**Comment by HelloTan** [comment]
https://www.instagram.com/stories/rbot_tanysz/2457448261122185634/

See dude, I have mentioned you, but there is no writing at all

my code

cl.photo_upload_to_story(
    "dasdawdsd.jpg",
    "Hello @adw0rd",
    mentions=[StoryMention(user=usernamenya, x=0.49892962, y=0.703125, width=0.8333333333333334, height=0.125)],
    links=[StoryLink(webUri='https://tanysz.me')]
)

**Comment by adw0rd** [comment]
@HelloTan you must place the text on the picture itself, instagram also does

See https://github.com/adw0rd/instagrapi/blob/master/instagrapi/story.py#L86
and result https://www.instagram.com/stories/dhbastards/2457451983137977288/

![image](https://user-images.githubusercontent.com/546889/101277227-ff852b80-37c3-11eb-8fd9-7a62010bc14b.png)

**Comment by HelloTan** [comment]
So when I write using the PIL module, will Instagram mention the article? I still don't understand the story performance??

**Comment by adw0rd** [comment]
@HelloTan Write text as picture to dasdawdsd.jpg and mark at the same coordinates `StoryMention(user=usernamenya, x=0.49892962, y=0.703125, width=0.8333333333333334, height=0.125)`

**Comment by HelloTan** [comment]
Is there a module that reads the coordinates of the writing in the image?

**Comment by adw0rd** [comment]
@HelloTan When you place an writing on a picture, you know its coordinates
Or I don't understand you)

**Comment by HelloTan** [comment]
Okay, I got it @adw0rd

**Comment by mario-amazing** [comment]
@adw0rd, could you please explain what `x, y, width, height` variables mean? Are they a percentage? And is the picture correct?
<img width="276" alt="image" src="https://github.com/subzeroid/instagrapi/assets/9537753/be651cda-f3c5-4d66-9b97-4d342b9afa4c">

**Comment by mario-amazing** [comment]
I found a solution, in the browser version of instagram you can customize the desired area
<img width="1507" alt="Screenshot 2023-12-13 at 07 48 09" src="https://github.com/subzeroid/instagrapi/assets/9537753/f78186bd-0826-4818-9d54-212adf185092">
