### ISSUE TITLE
instagrapi.exceptions.ClipNotUpload: Unknown ({'response': None})

### ISSUE THREAD

**Issue by markdrrr** [adw0rd/instagrapi#310]
При первой авторзиации и загрузки фото или видео все работает.
так же при первой авторизации я сохраняю словарь настроек
`cl.get_settings()`
При повторной авторзиации с использованием предыдущих настроек при попытке загрузить фото или видео падает следующая ошибка
```
File "..../env/lib/python3.8/site-packages/instagrapi/mixins/clip.py", line 139, in clip_upload
    raise ClipNotUpload(response=self.last_response, **self.last_json)
instagrapi.exceptions.ClipNotUpload: Unknown ({'response': None})
```

**Comment by cloudoftg** [comment]
This also happens with IGTV

**Comment by adw0rd** [comment]
@markdrrr fixed in 1.11.0
