### ISSUE TITLE
Option to create highlights

### ISSUE THREAD

**Issue by klaytonpaiva** [adw0rd/instagrapi#317]
Can you create highlights?

I didn't find this function in the repository!

**Comment by adw0rd** [comment]
Related #215

**Comment by adw0rd** [comment]
Please sponsor the development of this feature if you need it.
**5 cups of coffee**

[![Donate](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/adw0rd)

**Comment by victorsmart** [comment]
Hi! I would really like to see a function by
highlights:

- adding and removing stories in highlights
- getting a list of stories from highlights
- creating and deleting highlights
- edit highlights (cover, title)
- getting a list of highlights on your account

How much coffee does it take? :-)

**Comment by adw0rd** [comment]
> Hi! I would really like to see a function by highlights:
> 
> * adding and removing stories in highlights
> * getting a list of stories from highlights
> * creating and deleting highlights
> * edit highlights (cover, title)
> * getting a list of highlights on your account
> 
> How much coffee does it take? :-)

10 cups and I am implementing this functionality 👍

**Comment by adw0rd** [comment]
Implemented in 1.16.3
