### ISSUE TITLE
contents not posting in upload de fotos, stories, clips..

### ISSUE THREAD

**Issue by adw0rd** [adw0rd/instagrapi#323]
### Discussed in https://github.com/adw0rd/instagrapi/discussions/322

<sup>Originally posted by **klaytonpaiva** August  7, 2021</sup>
Yesterday it was working perfectly, today no longer, I don't know what happened, the code is the same. I can post, but the description won't go and there's no error or exception.

```
cl = Client()
cl.login(USERNAME, PASSWORD)

path = ("imagens/img2.jpg")

cl.photo_upload_to_story(path, 'Meu Storyes', locations=[StoryLocation(location=loc, x=0.33, y=0.22, width=0.4, height=0.7)])#publish photo, location, but no comment
#or
cl.photo_upload_to_story(path, 'Meu Storyes')#publish photo without comment (with or without the caption)
#or
cl.photo_upload(path, caption = 'Meu Storyes')#publish photo without comment
```

**Comment by adw0rd** [comment]
Fixed `instagrapi==1.11.1`

**Comment by danilp12** [comment]
hi there, im having this bug. the code looks good, it upload the story, but no caption on in
api = Client()
api.login(user,passw)
api.photo_upload_to_story(os.getcwd()+"/fotos/day1.jpg",caption="caption")

i already try with and without the caption variable. any idea why ?

**Comment by adw0rd** [comment]
https://github.com/adw0rd/instagrapi/discussions/271

use StoryBuilder

**Comment by danilp12** [comment]
i've got this error now

Moviepy - Building video C:\Users\cerfa\AppData\Local\Temp\tmp_mu0_03u.mp4.
Moviepy - Writing video C:\Users\cerfa\AppData\Local\Temp\tmp_mu0_03u.mp4

Moviepy - Done !
Moviepy - video ready C:\Users\cerfa\AppData\Local\Temp\tmp_mu0_03u.mp4
Photo Upload failed with the following response: <Response [400]>
{"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}


the code is :
api = Client()
api.login(user,passw)
path = os.getcwd()+"/fotos/day1.jpg"
caption = "Testing text "
usuario = api.user_info_by_username("danilp12")
buildout = StoryBuilder(path,caption,[StoryMention(user=usuario)]).photo()
api.photo_upload_to_story(buildout.path,caption,mentions=buildout.mentions)


im i setting wrong the story builder??

im using version =1.15.16
