### ISSUE TITLE
Syntax Error - File "/python3.9/site-packages/instagrapi/mixins/comment.py", line 43

### ISSUE THREAD

**Issue by pierreminiggio** [adw0rd/instagrapi#327]
I'm running a Github action that postes Instagram Stories.

My last story upload from yesterday got a syntax error from the Instagrapi Package, the ones 2 days ago and before didn't have that issue.

```
File "/home/runner/work/instagram-story-poster/instagram-story-poster/main.py", line 5, in <module>
    from upload_story import upload_story
  File "/home/runner/work/instagram-story-poster/instagram-story-poster/upload_story.py", line 2, in <module>
    from instagrapi import Client
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/instagrapi/__init__.py", line 10, in <module>
    from instagrapi.mixins.comment import CommentMixin
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/instagrapi/mixins/comment.py", line 43
    or (result.get("has_more_headload_comments") and result.get("next_min_id")))
                                                                                ^
SyntaxError: invalid syntax
```
![image](https://user-images.githubusercontent.com/35456349/129187746-9ae8e393-5c2d-4276-86e5-83ff9c5ca866.png)

The failed action : https://github.com/pierreminiggio/instagram-story-poster/runs/3300782560?check_suite_focus=true

I haven't yet looked into the recent pushes from this package, but it's quite likely that this bug got introduced in the last few days.
EDIT : Found it ! https://github.com/adw0rd/instagrapi/issues/327#issuecomment-897556284

**Comment by adw0rd** [comment]
Use 1.9.14

**Comment by pierreminiggio** [comment]
Oups, forgot to give feedback that 1.9.14 did indeed fix this, thanks !
