### ISSUE TITLE
Photo Upload failed with the following response: <Response [400]>

### ISSUE THREAD

**Issue by parth23** [adw0rd/instagrapi#328]
**Describe the bug**

I can't simply upload jpeg photo on my insta account
![image](https://user-images.githubusercontent.com/17453977/129212826-9a352a65-71db-41b5-8232-e9e26cbfe006.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/17453977/129212871-3bbda319-f933-4b40-868e-fbc784791da4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version 3.8
 - instagrapi version latest

**Comment by adw0rd** [comment]
@parth23 show your code after which this error appeared

**Comment by parth23** [comment]
> @parth23 show your code after which this error appeared

![image](https://user-images.githubusercontent.com/17453977/129311778-4205a534-cca7-49b8-b5fc-23b679c24496.png)

**Comment by adw0rd** [comment]
@parth23 cannot reproduce
![image](https://user-images.githubusercontent.com/546889/129942811-07f59bd2-0b52-4ac2-b3e8-788958d79d05.png)
