### ISSUE TITLE
Post in both on Instagram and Facebook

### ISSUE THREAD

**Issue by jvsrvictor** [adw0rd/instagrapi#334]
I know that this project was designed to work only with Instagram, but in the app, there is a feature to post publications and stories also on Facebook with a single checkbox (if the accounts are linked).
I think that would be awesome to have this funcionality in this project without the need to seek for the facebook API. It looked simple to me, but I dont know if it is hard to implement.

**Comment by adw0rd** [comment]
Please sponsor the development of this feature if you need it.
**5 cups of coffee**

[![Donate](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/adw0rd)
