### ISSUE TITLE
set_uuids not working 

### ISSUE THREAD

**Issue by elmissouri16** [adw0rd/instagrapi#339]
**Describe the bug**
 `set_uuids` not working as expected when you set it before login and try to see if uuids are matched before and after login they arent 

**To Reproduce**
```
from instagrapi import Client
uuids = {
    "phone_id": "b44e7245-8fb9-416b-a432-139c562bd2da",
    "uuid": "5c24cd86-7a21-4299-9f50-3ff75eae460a",
    "android_device_id": "android-f0270b70090d7384",
}

client = Client()
client.set_uuids(uuids)
client.login('USERNAME', 'PASSWORD')
print(client.phone_id)
print(client.uuid)
print(client.android_device_id)
```
**Traceback**
No TraceBack

**Expected behavior**
 the uuids before login should be the same after login

**Comment by adw0rd** [comment]
https://gist.github.com/elmissouri16/1ee6246ecc81f661c9e5e8df8e0dbd60
