### ISSUE TITLE
Login Bug

### ISSUE THREAD

**Issue by ImperialCrise** [adw0rd/instagrapi#340]
**Describe the bug**
Bug when i try to login 
![image](https://user-images.githubusercontent.com/16134489/130268100-739200f8-4aa1-4ac4-8454-ce7ac9ac0457.png)

**Comment by adw0rd** [comment]
Cannot reproduce

![image](https://user-images.githubusercontent.com/546889/130286661-95d1e4b0-5584-4092-9098-23a047d71470.png)

need more information (proxy, region, show code)
fill in all required fields when create bug report!
