### ISSUE TITLE
With public or shared image url(http) photo_upload not working

### ISSUE THREAD

**Issue by parth23** [adw0rd/instagrapi#343]
**Describe the bug**
I am trying to upload photo using http(public url) but it's throwing error:
OSError: [Errno 22] Invalid argument: 'https:\\i.pinimg.com\\originals\\32\\c6\\8b\\32c68bf4a443232286d91b1cc66f3822.jpg'

**To Reproduce**
Use any public image url to upload

**Expected behavior**
local image upload is working fine but the issue is with the public image url

**Screenshots**
![image](https://user-images.githubusercontent.com/17453977/130638659-2995107e-427f-4761-9f3d-b05c96435e22.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version latest
 - instagrapi version latest

**Comment by adw0rd** [comment]
You need to pass the path to the file, not the URL

![image](https://user-images.githubusercontent.com/546889/130642004-57495a1c-23da-47a9-b605-da3c497956f0.png)

https://adw0rd.github.io/instagrapi/usage-guide/media.html

**Comment by parth23** [comment]
> You need to pass the path to the file, not the URL
> 
> ![image](https://user-images.githubusercontent.com/546889/130642004-57495a1c-23da-47a9-b605-da3c497956f0.png)
> 
> https://adw0rd.github.io/instagrapi/usage-guide/media.html

@adw0rd   so you mean I can't upload image with url?
Could you please provide any solution for that then?

**Comment by adw0rd** [comment]
@parth23 you can download the file and upload it
![image](https://user-images.githubusercontent.com/546889/130659608-c2a90017-1740-4e2f-9280-6306f280fb23.png)
https://adw0rd.github.io/instagrapi/usage-guide/media.html

**Comment by adw0rd** [comment]
@parth23 If you are downloading from some other site, you can use the [requests](https://docs.python-requests.org/en/master/) or [urllib](https://docs.python.org/3/library/urllib.html) library to download the file, read their documentation

**Comment by parth23** [comment]
> @parth23 If you are downloading from some other site, you can use the [httpx](https://www.python-httpx.org/), [requests](https://docs.python-requests.org/en/master/) or [urllib](https://docs.python.org/3/library/urllib.html) library to download the file, read their documentation

@adw0rd Actually I have a list of URLs that are stored in DB and I am planning to schedule it. I don't want to download and then upload it.
Facebook Graph API is providing such facility to upload photos using URL path.
I am using instagrapi is because of album_upload.
See if you can find out any solution in your existing code that will be more helpful

**Comment by adw0rd** [comment]
@parth23 Instagram does not allow to download content by URL, it requires the transfer of the file content, in any case, you will have to download the content to upload it to the Instagram server
