### ISSUE TITLE
instagrapi.exceptions.ClipNotUpload: Unknown ({'response': None})

### ISSUE THREAD

**Issue by kunal52** [adw0rd/instagrapi#344]
When I am trying to upload a clip or video. It throws below error

File "/usr/local/lib/python3.6/dist-packages/instagrapi/mixins/clip.py", line 140, in clip_upload
raise ClipNotUpload(response=self.last_response, **self.last_json)
instagrapi.exceptions.ClipNotUpload: Unknown ({'response': None})

The code I have used to download and upload the same clip.

```
media_path = cl.clip_download(media.pk)
location = media.location if media.location == None else cl.location_info(media.location.pk)
user = media.user
post = cl.clip_upload(media_path, generate_caption(media.caption_text, location.name if location != None else ''), location=location)

```

**Comment by adw0rd** [comment]
cannot reproduce

![image](https://user-images.githubusercontent.com/546889/130745353-5f91c59b-eced-484a-9be1-08c0d56d2626.png)

provide more details, at least `media.pk` from your example

**Comment by kunal52** [comment]
Can you please try this pk.

2647800636683757153

**Comment by adw0rd** [comment]
@kunal52 works fine

![image](https://user-images.githubusercontent.com/546889/130764041-e5f83096-0170-4f71-893c-f78c430a6d56.png)

Try to simplify caption (I don't know what generate_caption does) or change your session/proxy
