### ISSUE TITLE
 want to get  Tagged post for a user 

### ISSUE THREAD

**Issue by dheeraj009joshi** [adw0rd/instagrapi#356]
This is a feature request plz.. try to make it fast it is seriously very important 
![image](https://user-images.githubusercontent.com/73873399/131665822-893c1705-0be9-4baa-b9bf-bf9b0cda27c9.png)
as shown in image i want to get those posts of a user

**Comment by dheeraj009joshi** [comment]
Any progress @adw0rd on this plz.. This is so  important for me

**Comment by adw0rd** [comment]
Implemented in 1.12.11
``` python
medias = cl.usertag_medias(user_id)
```
