### ISSUE TITLE
`user_followers_v1` and `user_followers` return duplicates of UserShort-s

### ISSUE THREAD

**Issue by Rodionxx** [adw0rd/instagrapi#359]
**Describe the bug**
User has 3898 subscribers.
`user_followers_v1` and `user_followers` return 3898 UserShort-s that contain duplicates.
So finally number of unique subscribers is less than 3898.

**Expected behavior**
Methods should return the same number of unique UserShort as user subscribers.

<img width="402" alt="Screenshot 2021-09-02 at 02 54 28" src="https://user-images.githubusercontent.com/8184871/131829767-610a7fe3-fbef-485a-ad5b-f921eeb1f7ca.png">

**Comment by adw0rd** [comment]
Added uniqueness check for follower.pk

![image](https://user-images.githubusercontent.com/546889/131853217-0118fdbd-371d-4d16-9683-d6dd1fd09f63.png)

instagrapi 1.12.10

**Comment by Rodionxx** [comment]
Now method return 3584 unique users instead 3898
![Screenshot 2021-09-02 at 17 53 36](https://user-images.githubusercontent.com/8184871/131866942-9b1abfa6-a8b8-4276-aeda-1d03c082fa81.png)

**Comment by adw0rd** [comment]
I have 740 followers

![telegram-cloud-photo-size-2-5298920879763338172-x](https://user-images.githubusercontent.com/546889/131877711-5db09e1b-e7bf-4012-a495-b56e71723eb4.jpg)

but instagram return 
![telegram-cloud-photo-size-2-5298920879763338174-x](https://user-images.githubusercontent.com/546889/131877745-3231864c-ec88-42de-b383-d926f2c930a8.jpg)

![telegram-cloud-photo-size-2-5298920879763338181-y](https://user-images.githubusercontent.com/546889/131877769-48681fef-2602-423d-9ea7-377ec2c3dd41.jpg)

Instagram lazily recalculate counters, or return an incorrect list of followers
