### ISSUE TITLE
KeyError: 'payload'

### ISSUE THREAD

**Issue by mahdi-asadzadeh** [adw0rd/instagrapi#363]
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    cl.direct_story_share(story_id, [user_id1], [thread_id])
  File "/home/mahdi/Desktop/my-insta/instagram/mixins/direct.py", line 176, in direct_story_share
    return extract_direct_message(result["payload"])
KeyError: 'payload'

**Comment by adw0rd** [comment]
@mahdi-asadzadeh specify user_ids or thread_ids, together causes an error on the Instagram server. I will now add a check (assert) to the code so that both parameters are not passed

![image](https://user-images.githubusercontent.com/546889/132095844-e6048056-c424-45a8-a571-01b4ac003000.png)
