### ISSUE TITLE
No "response_to_comment" method

### ISSUE THREAD

**Issue by lucabinotti** [adw0rd/instagrapi#365]
### Compensate with donations ($50 and more) for the time I spent to implement new functionality or send me your [Pull Request](https://github.com/adw0rd/instagrapi/pulls) with your implementation of the new functionality

* Bitcoin: 3KHgnvNNWio6wyQ71cgNeBQojXStxzkzfd
* Ethereum: 0x6e644c6b975B47801072b07a9a57DDfEC10DE74F
* https://paypal.me/adw0rd
* https://www.patreon.com/adw0rd
* https://www.buymeacoffee.com/adw0rd
* For Russia: СБП, Qiwi и тп: **+79118107609**

**Is your feature request related to a problem? Please describe.**
There are no method for responding to a comment with a comment.

**Describe the solution you'd like**
A "response_to_comment" method

**Comment by adw0rd** [comment]
Please sponsor the development of this feature if you need it.
**5 cups of coffee**

[![Donate](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/adw0rd)

**Comment by Chuckler22** [comment]
Sponsored this 25-Nov. Following with interest!

**Comment by adw0rd** [comment]
@Chuckler22 implemented in instagrapi 1.15.20
