### ISSUE TITLE
Login required and session restore

### ISSUE THREAD

**Issue by wpbloger** [adw0rd/instagrapi#367]
After the session is restored, each time it asks to login to post a photo. 
But for example, if you receive a timeline feed, then everything works.

Example code to reproduce: 
```
cl = Client()
if has_session:
    cl.load_settings('/tmp/dump.json')
cl.login(USERNAME, PASSWORD)
cl.dump_settings('/tmp/dump.json')
cl.get_timeline_feed() # this is work
cl.photo_upload(iimg_path, text) # this is not work after restore
```
Maybe this can be fixed? 

python - 3.6.9
instagrapi - 1.12.19

**Comment by adw0rd** [comment]
@wpbloger try to figure it out yourself and send a PR
