### ISSUE TITLE
Information about unread messages in direct

### ISSUE THREAD

**Issue by annalitvin** [adw0rd/instagrapi#37]
Is it possible to get information to display unread messages?

Example - https:// ibb.co/xqH7SPX

**Comment by adw0rd** [comment]
I'll look today

**Comment by adw0rd** [comment]
@annalitvin thread.last_seen_at have timestamps, by it you can identify unread

**Comment by adw0rd** [comment]
@annalitvin added thread.is_seen(you_user_id) function.
It will return False if there are unread messages in the thread.
