### ISSUE TITLE
<photo/video>_upload() with like count desactivated

### ISSUE THREAD

**Issue by Poloin34** [adw0rd/instagrapi#382]
Hello, I couldn't find anywhere what was the option to hide the like count while uploading a post.

I tried to add an argument, raised an error
Tried to add it in extra_data argument, posted with success, but like count still showing up each time

So, it is possible to? how? If no, would it be possible soon?

**Comment by adw0rd** [comment]
@Poloin34 to disable like and views counts use `extra_data={"like_and_view_counts_disabled": 1}`
