### ISSUE TITLE
[BUG] Automatically log out after several requests when login_by_session

### ISSUE THREAD

**Issue by akhmedyarov** [adw0rd/instagrapi#388]
**Describe the bug**
1. login_by_session_id
2. user_id_from_username
3. user_medias_gql
4. loop media
4.1 media_comments for each media

After looping first media, on the second media I have problem that instagram deletes my session_id and automatically log out from account.

I guess that is because media_comments method uses private API.

**To Reproduce**

```python
client.login_by_sessionid(username, password)
user_id = client.user_id_from_username(password)
medias = client.user_medias_gql(user_id, amount=7)

for media in medias:
    media_dict = media.dict()
    # some logic
    comments = client.media_comments(media_dict['id'], amount=100)

```

**Traceback**
I got 401 Not authorized on next request (second media) to fetch comments

**Expected behavior**
I expect that there should not log out process.

**Desktop:**
 - OS: Ubuntu 18.04
 - Python version - 3.9
 - instagrapi version - 1.13.6

**Comment by adw0rd** [comment]
@akhmedyarov I can't reproduce, but you can try using [Lamadava SaaS](https://lamadava.com/) to get comments
