### ISSUE TITLE
API rate limits

### ISSUE THREAD

**Issue by paradox70** [adw0rd/instagrapi#4]
I searched a lot to find rate limits of Instagram private API but there was nothing, (i.e how many requests  per minute are allowed to call and how many accounts we can login by an IP.)
Do you have any reference to prevent flood and reduce risk of account removal by Instagram?

**Comment by adw0rd** [comment]
@paradox70 These limits are constantly changing, so I use one IPv6 per account

**Comment by paradox70** [comment]
Thanks for your reply and awesome library.
I want to find out:
1- The maximum number of accounts I can login by an IP.
2- The rate limit of uploading medias to ig by an account.
I will find these by testing, If I have free time.

**Comment by adw0rd** [comment]
1 - I'm using 10 accounts for 1 IPv6 proxy
2 - publish from 4 to 16 posts to the feed and 24-48 stories per day

**Comment by paradox70** [comment]
Thanks, You saved my time.
