### ISSUE TITLE
[BUG] Timeline feed request no paginate results

### ISSUE THREAD

**Issue by eduardo-adjinn** [adw0rd/instagrapi#405]
Every time that get_timeline_feed() is called, the api returns the same posts.
I've tried with "is_pull_to_refresh":True and False but with the same result.
I've tried putting "max_id" param in the request... but nothing.
And I've tried setting the posts as seen with the param seen_posts and calling to media_seen() function but the same post are returned

¿It's a bug?¿Or the Instagram API has changged?

**Comment by dmunozv04** [comment]
@eduardo-adjinn have you enabled white hat mode on your Instagram account and have you configured your proxy’s certificate on the device? For white hat you need to go [here](https://www.facebook.com/whitehat/researcher-settings/).

**Comment by rdxshubham** [comment]
Any update Eduardo?

**Comment by eduardo-adjinn** [comment]
No news about it
