### ISSUE TITLE
Unhandled Challenge Exception

### ISSUE THREAD

**Issue by lexan73** [adw0rd/instagrapi#43]
Exception: ChallengeResolve: 
Unknown step_name "submit_phone" for "xxxxxx" in challenge resolver: {'step_name': 'submit_phone', 'step_data': {'phone_number': '+1234567890'}, 'cni': 17964459592361911, 'challenge_type_enum_str': 'SMS', 'status': 'ok'}

**Comment by adw0rd** [comment]
Cannot reproduce
