### ISSUE TITLE
I want help..!

### ISSUE THREAD

**Issue by kimjuchan-effort** [adw0rd/instagrapi#459]
First of all, Thank you for perfect library..

In my situation, I encounter hardship

I want use 5+ accounts in AWS EC2.

I was good at under 5 accounts using.

but, from 6 accounts using, challengerequired exception occur..!

so i want set_proxy(proxy). but where can i buy proxy? 

In my country, there is no information about this..!

**Comment by adw0rd** [comment]
You can use https://www.webshare.io/ or get data without blocking via https://lamadava.com/

**Comment by kimjuchan-effort** [comment]
@adw0rd   thank you so much! This library is so perfect!!

**Comment by kimjuchan-effort** [comment]
good

**Comment by prannavmaytray** [comment]
If you're not able to get this to work then I recommend checking out this [Instagram reels downloader](https://reelit.io)
