### ISSUE TITLE
Is it possible to save the login cookie and use it for login later?

### ISSUE THREAD

**Issue by EsmaeiliSina** [adw0rd/instagrapi#46]
Hi!
Is it possible to login once and save the cookie for next time?

**Comment by adw0rd** [comment]
@EsmaeiliSina yes

```
cl = Client()
cl.login(...)
json.dump(
    cl.get_settings(),
    open('/path/to/file.json', 'w')
)
...
cl = Client(json.load(open('/path/to/file.json')))
```

**Comment by Mengtailin** [comment]
Hi

**Comment by Mengtailin** [comment]
Hi
Why can ‘media_comments()’ only return 20 pieces of data？
Look forward to your reply

**Comment by Mengtailin** [comment]
Hi
Why can ‘media_comments()’ only return 20 pieces of data？
Look forward to reply
