### ISSUE TITLE
Upload post using url

### ISSUE THREAD

**Issue by Deathpoolxrs** [adw0rd/instagrapi#460]
Hey I want to know can i Upload post using url 
sample example:
media_pk = cl.media_pk_from_url('https://www.instagram.com/p/CWOEStsptCq/')

media = cl.photo_upload(media_pk,"Test caption for photo with #hashtags and mention users such @instagram")

**Comment by adw0rd** [comment]
![image](https://user-images.githubusercontent.com/546889/143658796-1879ae2a-9f23-4f5d-a5b8-1e0e94b55a88.png)

https://adw0rd.github.io/instagrapi/usage-guide/media.html
