### ISSUE TITLE
[BUG] exception occured: KeyError('graphql') when hashtag_medias_recent

### ISSUE THREAD

**Issue by fro0m** [adw0rd/instagrapi#481]
**Describe the bug**
exception occured: KeyError('graphql') after cl.hashtag_medias_recent(hashtag, amount = 150)

**Desktop (please complete the following information):**
 - OS: . lubuntu 21.04
 - Python version 3.9
 - instagrapi version - instagrapi-1.16.2.egg-info

**Comment by adw0rd** [comment]
You IP address is blocked by instagram (doesn't return "graphql"), you can try to using https://lamadava.com/ for getting hashtag data

![image](https://user-images.githubusercontent.com/546889/145364180-1b417091-84e8-4b9e-9f6f-dae7a25fb4cf.png)

**Comment by valo83** [comment]
Nothing free?

**Comment by adw0rd** [comment]
@valo83 you can try use `cl.hashtag_medias_recent_v1`
https://adw0rd.github.io/instagrapi/usage-guide/hashtag.html

**Comment by claell** [comment]
I ran into the same issue. Thanks for the info why this happens. Are there roughly known limits from Instagram to make sure not to run into this?
