### ISSUE TITLE
Status 429: Too many requests

### ISSUE THREAD

**Issue by mikebgrep** [adw0rd/instagrapi#49]
`userr_id_main = cl.user_id_from_username('someuser')

## User followers of the main user
user_followers = cl.user_followers(userr_id_main)`

Status 429:Too many requests;
How to slow down the requssts some of the users I need to check followers are with 19k followers to 192k followers.I need to set some time sleep but when I use user_followers() I don`t know how to do it.

**Comment by adw0rd** [comment]
Use request_timeout:

`cl.request_timeout = 5  # seconds`
