### ISSUE TITLE
Upload Multiple images error

### ISSUE THREAD

**Issue by rishabh-modi-3** [adw0rd/instagrapi#492]
my script is given below
when i try to upload multiple photos its giving error

from instagrapi import Client
cl = Client()
cl.login("username", "password")
media = cl.photo_upload(
    "/home/rishabh/a5.jpg",
    "Test caption for photo with #hashtags and mention users such"
    extra_data={
        "custom_accessibility_caption": "alt text example",
        "like_and_view_counts_disabled": 1,
        "disable_comments": 1,
    }
)
media = cl.photo_upload(
    "/home/rishabh/a5.jpg",
    "Test caption for photo with #hashtags and mention users such"
    extra_data={
        "custom_accessibility_caption": "alt text example",
        "like_and_view_counts_disabled": 1,
        "disable_comments": 1,
    }
)

**Comment by rishabh-modi2** [comment]
I solved issue sorry for disturbances
