### ISSUE TITLE
[BUG] user_id = cl.user_id_from_username("cittaditorino") \\ like_count=-1

### ISSUE THREAD

**Issue by valo83** [adw0rd/instagrapi#493]
![immagine](https://user-images.githubusercontent.com/32481886/146229914-c8bcafaf-94c9-452f-84ea-4197f8e1d78e.png)

_ _ _

Sometime the result about **like_count** is not correct.
Can someone help me?
Thanks
Valo

**Comment by adw0rd** [comment]
When `like_count = -1`, the instagram server returns it and this is the correct value, this means that likes are disabled for your country

**Comment by adw0rd** [comment]
This is not a bug!

**Comment by adw0rd** [comment]
You can try https://lamadava.com/, it uses accounts from other countries for which likes are not disabled
https://api.lamadava.com/docs

**Comment by valo83** [comment]
but sometime works. it's curious.
Thanks anyway

**Comment by adw0rd** [comment]
![image](https://user-images.githubusercontent.com/546889/146240494-b217c3dd-b5f6-405f-b28b-b72742348b65.png)
![image](https://user-images.githubusercontent.com/546889/146240607-b01b8eb9-88bf-460e-a727-edefaa467092.png)

**Comment by valo83** [comment]
ok.
But I need to learn how to use it :)
