### ISSUE TITLE
Add SessionID option in relogin

### ISSUE THREAD

**Issue by imDivu** [adw0rd/instagrapi#496]

**Comment by imDivu** [comment]
> Add [Sessionid](https://github.com/adw0rd/instagrapi/blob/8c32f1bde2bf71a8f0f5eabd5da5826051bab969/instagrapi/mixins/auth.py#L307) option in [relogin](https://github.com/adw0rd/instagrapi/blob/8c32f1bde2bf71a8f0f5eabd5da5826051bab969/instagrapi/mixins/auth.py#L452)

**Comment by adw0rd** [comment]
@imDivu "cl.relogin" - need for create a new session, why add the "sessionid" option if you are creating new session? What is the point of that?
