### ISSUE TITLE
Clear the old query in new api call

### ISSUE THREAD

**Issue by mikebgrep** [adw0rd/instagrapi#51]
Do it have some function like clear the old query.Because when I make a search for followers of an user it save the search on the next search give me same result.I am not sure its from my flask application or is it from the bot.Thanks
ps.Definitely is from the api I try on simple script if I not close it didn`t load the updated information

**Comment by jaraya81** [comment]
You should use the parameter use_cache = False in the method user_followers, by default it's True.

**Comment by mikebgrep** [comment]
Great thank you
