### ISSUE TITLE
Add custom text for StoryLink sticker

### ISSUE THREAD

**Issue by ljcanales** [adw0rd/instagrapi#517]
Add the functionality to specify the text of the StoryLink sticker
Something like:
`
StoryLink(webUri="https://github.com", text="Tap me")
`

**Comment by adw0rd** [comment]
Instagram doesn't support link text, or what do you mean?

**Comment by ljcanales** [comment]
It is support in app.

![Screenshot_20211230-141312~2](https://user-images.githubusercontent.com/64669280/147773905-e5050203-6e38-4bc5-ad8a-eeec8a96fe2d.png)

Then:
![Screenshot_20211230-141331~2](https://user-images.githubusercontent.com/64669280/147774081-c79d6828-d961-4523-a805-d47861f10ecd.png)

**Comment by adw0rd** [comment]
@ljcanales oh, thanks! I will add this feature tomorrow!

**Comment by danielsantos852** [comment]
Good day, everyone!

Can anyone point me to where I can learn about how to add these URL stickers to my stories?

Thanks in advance!

**Comment by adw0rd** [comment]
https://adw0rd.github.io/instagrapi/usage-guide/story.html
