### ISSUE TITLE
infinity loop in hashtag_medias_top_a1

### ISSUE THREAD

**Issue by jaraya81** [adw0rd/instagrapi#52]
I am using the hashtag_medias_top method and it is iterating infinitely in hashtag_medias_top_a1 (average remains at 8 and never increases to 9 which is the amount)

**Comment by adw0rd** [comment]
@jaraya81 on which hashtag you reproduce the problem?

**Comment by jaraya81** [comment]
With #ciudadbolivar in this script https://github.com/jaraya81/instagrapi/blob/example/examples/medias.py

**Comment by adw0rd** [comment]
@jaraya81  fixed 1.3.9
