### ISSUE TITLE
hashtag_related_hashtags doesn't returning anything[BUG]

### ISSUE THREAD

**Issue by gollkn** [adw0rd/instagrapi#524]
**Describe the bug**
I'm trying to use hashtag_related_hashtags method with instagrapi-rest and I'm using it like this 

```
@router.post("/related")
async def hasthag_related(sessionid: str = Form(...),
                         name: str = Form(...),
                         clients: ClientStorage = Depends(get_clients)):
    """Get similar hastags
    """
    cl = clients.get(sessionid)
    return cl.hashtag_related_hashtags(name)
```
but when I'm sending a request it's returning 200 status with empty Array.

**Comment by mrmmg** [comment]
@gollkn can you solve this issue?

**Comment by adw0rd** [comment]
@gollkn cannot reproduce, give me a hashtag name, please

**Comment by mrmmg** [comment]
@adw0rd @gollkn  for example I tried 
Messi
Ronaldo

**Comment by adw0rd** [comment]
@mrmmg please send link to hashtag, e.g. https://www.instagram.com/explore/tags/messi/

**Comment by gollkn** [comment]
Hi @adw0rd,  this is not actual hashtag content this is the request which returning related hashtags so like when I'm searching 
"mes"
![CleanShot 2022-01-12 at 11 56 08](https://user-images.githubusercontent.com/47605174/149086563-ffd6a475-180a-4acf-a20f-1b1fbd934656.png)
it's returning related hashtags. this is what I'm trying to achieve with this method.

```
@router.post("/related")
async def hasthag_related(sessionid: str = Form(...),
                         name: str = Form(...),
                         clients: ClientStorage = Depends(get_clients)):
    """Get similar hastags
    """
    cl = clients.get(sessionid)
    return cl.hashtag_related_hashtags("mes")
```

**Comment by adw0rd** [comment]
> Hi @adw0rd, this is not actual hashtag content this is the request which returning related hashtags so like when I'm searching "mes" ![CleanShot 2022-01-12 at 11 58 18](https://user-images.githubusercontent.com/47605174/149086882-ab7f0d2b-986a-4447-a120-16f18f204ae2.png)
> 
> it's returning related hashtags. this is what I'm trying to achieve with this method.
> 
> ```
> @router.post("/related")
> async def hasthag_related(sessionid: str = Form(...),
>                          name: str = Form(...),
>                          clients: ClientStorage = Depends(get_clients)):
>     """Get similar hastags
>     """
>     cl = clients.get(sessionid)
>     return cl.hashtag_related_hashtags("mes")
> ```

@gollkn these are not related hashtags, these are suggested hashtags as search results

hashtag_related_hashtags - will return a list of related hashtags generated by Instagram, e.g. "bmw" may return "audi, mercedes" and more else, not "bmw2, bmw3..." like in the search bar

**Comment by adw0rd** [comment]
hashtag_related_hashtags - this method doesn't work now, Instagram doesn't return any data for this endpoint

**Comment by gollkn** [comment]
> hashtag_related_hashtags - this method doesn't work now, Instagram doesn't return any data for this endpoint

Thanks but which method can I use to get result which is shown in picture ?

**Comment by adw0rd** [comment]
@gollkn try this https://github.com/adw0rd/instagrapi/blob/master/instagrapi/mixins/fbsearch.py#L58
