### ISSUE TITLE
[BUG] account_edit with email have no effect

### ISSUE THREAD

**Issue by ennis214** [adw0rd/instagrapi#526]
**Describe the bug**
Doing account_edit with email seems to be not working. It didn't change and no error msg return

**To Reproduce**
`cl.ccount_edit(email = "xxxxxxx@gmail.com")`

**Traceback**
No error msg

**Expected behavior**
Upon printing `cl.account_info()`, email field is still empty

**Desktop (please complete the following information):**
 - OS: MacOS
 - Python version 3.8.8
 - instagrapi version 1.16.11

**Comment by ennis214** [comment]
With further investigation, it happened when the account already have a phone number attached

**Comment by adw0rd** [comment]
@ennis214 try instagrapi 1.16.13 and new methods: `cl. send_confirm_email` and `cl.send_confirm_phone_number`
https://adw0rd.github.io/instagrapi/usage-guide/account.html
