### ISSUE TITLE
Get Additional Data when using hashtags to get posts

### ISSUE THREAD

**Issue by gholamrezaeipt** [adw0rd/instagrapi#531]
**Is your feature request related to a problem? Please describe.**

I need to have a little bit of additional information about each item when I use hashtags functions. For example, when I have the information of each post, I should have the first 10 comments

For Now I have to get the hashtag information separately with a for loop which is a long and time consuming process.

Is such a thing possible?

**Additional context**
I need something like this:

assume that we call a route: `/hashtag/recents`

the result: 

```
[
  {
      "pk": 0000000000000000,
      .
      .
      .
      "comment_count": 200,
      "comments": {}  //for example the first 10 comments from 200, if comment_count equals to zero then return empty object
  },
  {
    ...
  },
  {
    ...
  }
]
```

**Comment by adw0rd** [comment]
@gholamrezaeipt i don't know such a possibility, but you can find and implement it in instagrapi
