### ISSUE TITLE
[BUG] consent_required

### ISSUE THREAD

**Issue by saygin-bey** [adw0rd/instagrapi#542]
I keep getting this error: consent_required

I'm facing this right after logging into the account. Whatever I tried to solve it didn't work. I even switched to a business account

Please Help Me !!

**Comment by adw0rd** [comment]
@saygin-bey show your code and traceback first

**Comment by saygin-bey** [comment]
I had to constantly change the device id. I solved the problem. Thanks

**Comment by Jiroun** [comment]
@saygin-bey  I am facing same problem , how you fix it ?
