### ISSUE TITLE
Can we reach users with Instagram suggestions?

### ISSUE THREAD

**Issue by Veucci** [adw0rd/instagrapi#545]
I want to see and follow my suggestion list. Can I see the suggestion list like the home page of the mobile app?
Like this:
![suggestions](https://user-images.githubusercontent.com/66924680/150424736-0d4904ec-8409-4439-852d-8bd19caa94d5.png)

**Comment by abdullahbektass** [comment]
I worked on this last week. There is currently a public request method 'profile_related_info' in the library. However, Instagram is no longer responding to this public request. Instead I found an "fbsearch" request with the fbsearch/accounts_recs/ endpoint from web browser network activities.

I added the following method to fbsearch.py. It returns 80 seggested profiles for each profile.


```
def fbsearch_suggested_profiles(self, user_id: str) -> List[UserShort]:
        params = {
            "target_user_id": user_id,
            "include_friendship_status": "true",
        }
        result = self.private_request("fbsearch/accounts_recs/", params=params)
        return result["users"]
```

**Comment by yeeyou** [comment]
@abdullahbektass Thank you, It really works. I've create a PR, so it will be easier for other to use if merged.
