### ISSUE TITLE
[BUG] post is getting removed

### ISSUE THREAD

**Issue by rishabh-modi2** [adw0rd/instagrapi#548]
whenever i post using instagrapi.
its getting removed..

i tried many times.

getting this :::::::-

instagrapi.exceptions.ChallengeUnknownStep: ChallengeResolve: Unknown step_name "escalation_challenge_informational" for "comedy_cementary" in challenge resolver: {'step_name': 'escalation_challenge_informational', 'step_data': {'choice': 0, 'community_guideline_body': ['• You have posted content too many times.', '• You have a blocked link in your post.'], 'community_guideline_header': 'We remove content when:', 'responsible_content': {'entity_id': 2756090312585923690, 'content_type': 'post', 'taken_at': 1642771589, 'deleted_content_preview': 'https://instagram.fjai2-3.fna.fbcdn.net/v/t51.2885-15/e35/s150x150/272173001_456952282599060_2446071785528903842_n.jpg?_nc_ht=instagram.fjai2-3.fna.fbcdn.net&_nc_cat=100&_nc_ohc=QdTEegGfbXoAX_qBh1R&edm=AMwhvZcBAAAA&ccb=7-4&ig_cache_key=Mjc1NjA5MDMxMjU4NTkyMzY5MA%3D%3D.2-ccb7-4&oh=00_AT_U3LHUuI_uDSkV86KCrxHlUhCO2OpkLwImpDFi1R4gZw&oe=61F0F7F3&_nc_sid=a3358c', 'takedown_type': 0, 'violation_type': '131', 'violation_text': '', 'content_type_text': 'post', 'caption': 'i am memer'}, 'is_appealable': False, 'strike_level': 0, 'violation_content_group': 'content spam', 'entry_point': 'challenge', 'system_id': 132947280075456}, 'flow_render_type': 3, 'bloks_action': 'com.instagram.challenge.navigation.take_challenge', 'cni': 17845813298715582, 'challenge_context': '{"step_name": "escalation_challenge_informational", "cni": 17845813298715582, "is_stateless": false, "challenge_type_enum": "ESCALATION"}', 'challenge_type_enum_str': 'ESCALATION', 'status': 'ok'}

We removed your post because it goes against our Community Guidelines. Even if you didn't mean to offend, our guidelines encourage people to express themselves in a way that's respectful to everyone.
We remove content when:
• You have posted content too many times.
• You have a blocked link in your post.
Learn more about what we remove.

**Comment by adw0rd** [comment]
@rishabh-modi2 log in through the Instagram app and confirm the challenge

**Comment by rishabh-modi2** [comment]
> @rishabh-modi2 log in through the Instagram app and confirm the challenge

i tried again after accepting challange. but error is same

**Comment by rishabh-modi2** [comment]
> It Says Clearly, Post is against community guidelines

i understand you. but the same post(image) i post using instagram app is not against community guidelines.
but when posted by instagrapi is against policy.
is not this abnormal and a bug.

**Comment by rishabh-modi2** [comment]
Sorry Guys for disturbance,,,

I found solution...
i created account using instagram.com in pc.
and used instagrapi. and continuously got error
but as adwod said its by instgram app

i installed instagram app and logged in there now the problem is solved it working fine thanks you guys and our greate devloper..
