### ISSUE TITLE
[BUG]Proxy Bug

### ISSUE THREAD

**Issue by vsdfnvuitsb** [adw0rd/instagrapi#576]
Thanks to @adw0rd  for making such a great project open source。

I found a problem. When I use the following code in the program to set up access through the proxy, it does not seem to use the proxy. The code is as follows:

`cl.set_proxy('http://xxx:xxx@xxx.com:xxxx')`

When I looked at the instagrapi source code it didn't seem like the proxy was being used when sending the request.The relevant code is in the _send_private_request function of private.py.The code is as follows:

`response = self.private.post(
                    api_url, data=data, params=params
                )`

Is that why?

Looking forward to your reply.

**Comment by adw0rd** [comment]
the proxy is set at the session level for all outgoing requests

it's not a bug, it's correct way to set common data like as proxies and headers in python-requests

print(cl.private.proxies)

**Comment by adw0rd** [comment]
https://docs.python-requests.org/en/master/user/advanced.html

**Comment by vsdfnvuitsb** [comment]
However, after setting the proxy through set_proxy, the actual request ip printed is still the local ip, and it is not accessed through the proxy.

**Comment by adw0rd** [comment]
Please show your code to understand how you print local IP

**Comment by vsdfnvuitsb** [comment]
> Please show your code to understand how you print local IP

Add a new function under the PrivateRequestMixin class in the private.py file.The code is as follows:

```
    def send_uuuuuu_req(self):
        response = self.private.get(
            'http://ip-api.com/json'
        )
        print(response.text)
```

response my local ip

**Comment by vsdfnvuitsb** [comment]
Print `response.headers` in the `PrivateRequestMixin` class of `private.py` where the value of `X-FB-Client-IP-Forwarded` is my local ip. @adw0rd 

Below is my complete code:

```
class InsServerClient:
    def __init__(self):
        self.cl = Client()
        self.rebox = []
        self.init_location()

    def init_location(self):
        self.cl.set_proxy('http://xxx:xxx@xxx:9000')
        self.cl.set_locale('zh-SG')
        self.cl.set_country_code(65)
        self.cl.set_timezone_offset(8 * 3600)
        print(self.cl.private.proxies)
    
    def check_session(self):
        self.cl.load_settings('dump.json')
        try:
            self.cl.get_timeline_feed()
        except:
            pass
            
if __name__ == '__main__':
    InsServerClient().check_session()


```
