### ISSUE TITLE
How to accept threads from the "pending inbox"?

### ISSUE THREAD

**Issue by msr8** [adw0rd/instagrapi#582]
I got them from `client.direct_pending_inbox()` but cannot find a way to accept them. Any help?

**Comment by 88um** [comment]
If you already have threads, you can either mark them as seen or give a response.

```Python
from instagrapi import Client
c = Client()
c.loginbysessionid("ursession")
myThreads = c.direct_pending_inbox(20)
myMessage = "sup"
for thread in myThreads:
       c.direct_send_seen(thread) // accept and send a seen
       c.direct_answer(thread,myMessage) // accept and send a message

**Comment by msr8** [comment]
Thank you! Honestly I found it kinda funny that you used `//` for comments instead of the python `#` haha. Lemme guess, a javascript coder?
