### ISSUE TITLE
[BUG] VideoSourceError

### ISSUE THREAD

**Issue by helallao** [adw0rd/instagrapi#584]
I can't upload video, igtv, clip. it gives VideoSourceError.
i downloaded an instagram page's video from source and tried to upload my page but it gives VideoSourceError.
Also i can upload same file with instagram app

**Comment by jroigfer** [comment]
Debugging I saw the error occurs in video_configure method :
        return self.private_request(
            "media/configure/?video=1", self.with_default_data(data)
        )
This request return the error.

**Comment by adw0rd** [comment]
Read this https://github.com/adw0rd/instagrapi/issues?q=VideoSourceError

VideoSourceError - this means the Instagram server does not understand your video format, you need to prepare the video before uploading it

**Comment by maksam07** [comment]
I'm facing the same problem. Can you tell me how to prepare it? Video 5-20 seconds, through the web version of Instagram loads without problems, but does not want to through the api.
