### ISSUE TITLE
Create method view count for story objects

### ISSUE THREAD

**Issue by markdrrr** [adw0rd/instagrapi#59]
When we have received information or a Story object, I ask you to make the function of sending a request for viewing.
So that the user from whom we looked at the story sees us in their statistics.
![image](https://user-images.githubusercontent.com/56235826/103365360-f5a7cd00-4ad0-11eb-869f-daed92c1c363.png)

**Comment by adw0rd** [comment]
@markdrrr use so `cl.story_seen([story1_pk, story2_pk])`
