### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Alinush124578** [adw0rd/instagrapi#594]
Due to the new Instagram update, the highlighted part did not work, please fix it

**Comment by adw0rd** [comment]
@Alinush124578 show your code, traceback, examples

**Comment by Alinush124578** [comment]
code : 
`from instagrapi import Client
cl = Client()



s_id = '' #Session_id


def main():
    link = 'https://www.instagram.com/s/aGlnaGxpZ2h0OjE3OTQ0MjM4NDczODQwNDA4?story_media_id=2783500379422796645_2012240260&utm_medium=copy_link'
    cl.login_by_sessionid(s_id)
    pk = cl.highlight_pk_from_url(link)
    info = str(cl.highlight_info(pk))
    print(info)
main()`


trace back : 
`Traceback (most recent call last):
  File "d:\python\insta bot\new_15.py", line 15, in <module>
    main()
  File "d:\python\insta bot\new_15.py", line 12, in main
    pk = cl.highlight_pk_from_url(link)
  File "C:\Users\Bestsenator\AppData\Local\Programs\Python\Python310\lib\site-packages\instagrapi\mixins\highlight.py", line 35, in highlight_pk_from_url
    assert '/highlights/' in url, 'URL must contain "/highlights/"'
AssertionError: URL must contain "/highlights/"`

examples :
https://www.instagram.com/s/aGlnaGxpZ2h0OjE3OTQ0MjM4NDczODQwNDA4?story_media_id=2783500379422796645_2012240260&utm_medium=copy_link
![Screenshot 2022-03-04 085646](https://user-images.githubusercontent.com/40005223/156705094-0be67101-a2b6-44c3-af80-aca65a372dcd.png)

**Comment by adw0rd** [comment]
@Alinush124578 you are not specifying a highlight link, but a share link!
Follow your link and you will see the highlight link

The share link can contain not only a highlight, but also a post

https://github.com/adw0rd/instagrapi/blob/master/instagrapi/mixins/share.py

**Comment by Alinush124578** [comment]
how to use it ??

**Comment by adw0rd** [comment]
@Alinush124578 read the docstring!

`cl.share_info_by_url(URL)`

**Comment by Alinush124578** [comment]
tnx so much
Is it possible to help me with another problem ???
I want to take the time interval between two dates as a list of dates.
For example, from 22/11/17 to 22/11/30
Which I want to be a list as follows:
18/11/22, 19/11/22, 20/11/22, .......
