### ISSUE TITLE
Status 429: Too many requests

### ISSUE THREAD

**Issue by alicanyuksel** [adw0rd/instagrapi#60]
I don't send too many requests at all but I get this error message when executing the script. Is it possible that Instagram has blocked me ?

**Comment by adw0rd** [comment]
How many requests do you send? per minute, hour, day?

And write what kind of requests do you send? If getting information on users is one thing, and if you follow or like something, then another.

I think you are not blocked, you just need to sleep for the day

**Comment by alicanyuksel** [comment]
Thank you for answering.
I have a scheduled job in my server which execute the script every minute. The script checks the database if there is new data added. If so, we login and post a photo about that data. 

The script post a photo 4 or 5 times per day. Like I said, I don't login until there is new data in the database. I don't send the request every minute. So I don't understand how I was able to exceed the limits...

**Comment by adw0rd** [comment]
@alicanyuksel instagrapi keeps its own log, check if there are many requests
`cl.request_logger = logging.getLogger("private_request")`

If there are still few requests, then your account may be used elsewhere?
Also, you can make few requests per hour, but several in a row at once per minute, this can also be understood from the log

**Comment by alicanyuksel** [comment]
@adw0rd There aren't many requests in log. And yes, I am also logged in my account on my phone.  I'll wait for the day and try again. Because at the moment, I can't even login. But with my phone, I can. 

I'll let you know if it works again. Thanks

**Comment by alicanyuksel** [comment]
@adw0rd after 36 hours, it works again.
