### ISSUE TITLE
[BUG] Links get carried over to following stories

### ISSUE THREAD

**Issue by just-claudio** [adw0rd/instagrapi#608]
**Describe the bug**
Once a story is published with a link, the same link is then repeated on the following stories, even if no StoryLink is given to the video_upload_to_story method.

**To Reproduce**
```
from instagrapi.story import StoryBuilder
from pathlib import Path
from instagrapi import Client
from instagrapi.types import StoryLink

client = Client()
client.login("user", "password")

path = Path("picture.jpg")
link = StoryLink(webUri="http://website.com")

story = StoryBuilder(path).photo(5)

client.video_upload_to_story(story.path, links=[link]) 

client.video_upload_to_story(story.path)  # This story still gets published with the same link
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python version 3.10
 - instagrapi version 1.16.14
 - moveipy version 1.0.3
 - imagemagick version 7.1.0.26

**Additional context**
Looking at the debug information I found out that the link sticker that is stored in stickers is then carried over in the video_upload_to_story method even if no stickers list is passed as argument.
To confirm this, the workaround I'm currently using is to force stickers to be empty when calling the method, like so:

`client.video_upload_to_story(story.path, stickers=[])
`

**Comment by pacotebarato** [comment]
I'm hosting an API using Flask on Heroku and I'm facing the same problem
