### ISSUE TITLE
[BUG] user_followers is freezing

### ISSUE THREAD

**Issue by Eikosa** [adw0rd/instagrapi#639]
![image](https://user-images.githubusercontent.com/20538090/163279264-83cf07e3-99c4-4138-b3dc-fef954a519f0.png)

user_followers function freezes forever

**Comment by adw0rd** [comment]
@Eikosa try `cl.user_followers_v1('575009265', amount=5)`

**Comment by Eikosa** [comment]
Thanks so much.

**Comment by Neto-wasd** [comment]
> @Eikosatentar`cl.user_followers_v1('575009265', amount=5)`

Thanks, I was having the same problem, I wasn't specifying 'amount'.
