### ISSUE TITLE
how can i use proxy with instagrapi?

### ISSUE THREAD

**Issue by Eikosa** [adw0rd/instagrapi#642]
how can i use proxy with instagrapi?

**Comment by floodwm** [comment]
cl = Client()
        cl.set_proxy(proxy)


https://adw0rd.github.io/instagrapi/usage-guide/interactions.html

**Comment by floodwm** [comment]
> how can i use proxy with instagrapi?

cl = Client()
cl.set_proxy(proxy)

https://adw0rd.github.io/instagrapi/usage-guide/interactions.html

**Comment by Eikosa** [comment]
thanks so much
