### ISSUE TITLE
How to add stickers? 

### ISSUE THREAD

**Issue by misterpeople** [adw0rd/instagrapi#644]
I cant find a way to add stickers with this lib, can someone help?

**Comment by adw0rd** [comment]
You have to draw your own sticker (as it is done in the Instagram app)
And instagrapi will help you mark up the metadata for your sticker (link area and more) - StorySticker
https://adw0rd.github.io/instagrapi/usage-guide/story.html

**Comment by adw0rd** [comment]
To understand what data needs to be sent via StorySticker, you need to look in [Charles](https://adw0rd.com/2020/03/26/sniffing-instagram-charles-proxy/en/)

**Comment by Borgerod** [comment]
Hey @adw0rd, Me and Misterpeople are working on a bot together. More specifically what I think he meant by that was;
1.  how do you add **polls** and **slidebar** to a story-upload? As shown below:
![278869468_662309635055408_7871368504280949950_n](https://user-images.githubusercontent.com/97392841/164231293-5280e24b-7f87-4bdf-ad83-e1a1b489a213.jpg)
 
 2. Also, what do you mean by "draw your own sticker"? 
     I don't think I can create my own poll-sticker from scratch then make the API recognize my homemade-sticker as the poll-                          
     sticker?

3. Lastly, whenever I want to upload a photo-story and use storybuilder to add @mentions or #hashtags; then the photo-story gets converted into a video-clip where the text is flashing on the screen, is it supposed to do this or am I doing something wrong? I would like for it to not be a mp4 but remain a jpg. Here's an example on how it looks like: 

https://user-images.githubusercontent.com/97392841/164233302-894fc332-bf88-4e16-bfac-13572d880c14.mp4

**Comment by adw0rd** [comment]
@Borgerod you can install Charles and see how to do it

How the instagram app does it:
1) Creates a photo or video story with the desired stickers and sends it to the instagram server
2) Sends markup so that the sticker can be clicked

I hope you understand my explanation

**Comment by adw0rd** [comment]
> Also, what do you mean by "draw your own sticker"?
I don't think I can create my own poll-sticker from scratch then make the API recognize my homemade-sticker as the poll-
sticker?

Install charles and see how it works

**Comment by Borgerod** [comment]
Thank you for the reply, I'll come back with an update once I've tried it out!

**Comment by murilobellatini** [comment]
@Borgerod  Have you guys tried it out ? 

By the way I got rid of the blinking on a local project, could that become a PR? @adw0rd
