### ISSUE TITLE
Erorr

### ISSUE THREAD

**Issue by yekayee** [adw0rd/instagrapi#645]
Raise PhotoNotUpload(response.text, response=response, **last_json)
instagrapi.exceptions.PhotoNotUpload: {"message":"checkpoint_required","checkpoint_url":"https://i.instagram.com/privacy/checks/?privacy_flow=1\u0026next=instagram://checkpoint/dismiss","lock":false,"flow_render_type":0,"status":"fail"}

**Comment by adw0rd** [comment]
@yekayee  I don't know how to fix it now, so i advise to use https://lamadava.com/
Or fix it yourself and send PR to instagrapi
