### ISSUE TITLE
[BUG] instagrapi.exceptions.UnknownError: checkpoint_required

### ISSUE THREAD

**Issue by yedhrab** [adw0rd/instagrapi#647]
I do this: `instagram account Privacy -> Login Activity -> It was me` but it don't work too.

**Comment by mvx20** [comment]
It gives this error in many activities. Comment, login, like. After a few tries it works fine and then it crashes again.

**Comment by vitormendes977** [comment]
I'm facing the exact same issue.

**Comment by m21c** [comment]
Same here, please help us fix this or advise for a workaround.

**Comment by adw0rd** [comment]
@vitormendes977 @m21c @mvx20 I don't know how to fix it now, so i advise to use https://lamadava.com/ 
Or fix it yourself and send PR to instagrapi

**Comment by vitormendes977** [comment]
@adw0rd don't lamadava and instagrapi have the same code working behind the scenes? How lamadava was not impacted?

**Comment by adw0rd** [comment]
@vitormendes977 Lamadava has 120k accounts and they rotate through them

**Comment by adw0rd** [comment]
> lamadava and instagrapi have the same code working behind the scenes?

yes

**Comment by hanacchi** [comment]
This issue was appearing in the official Instagram app too, so it is not an issue with instagrapi.
It seems like Instagram has resolved this by now and everything works fine again.
There is no need to use any paid service.
