### ISSUE TITLE
add a "mark as read" functionnality

### ISSUE THREAD

**Issue by Poloin34** [adw0rd/instagrapi#655]
Like we can mark a conversation as unread, it would be cool and very useful to mark one as read!

**Comment by Poloin34** [comment]
Waiting for it, here is my way to do it:

```python
r = cl.private.request(
    "OPTIONS",
    f"https://i.instagram.com/api/v1/direct_v2/threads/{thread_id}/items/{message_id}/seen/"
)
```

The strange thing is that it return a 405 response, but it does work

**Comment by adw0rd** [comment]
Why didn't you use `cl.direct_send_seen`?
https://github.com/adw0rd/instagrapi/blob/master/instagrapi/mixins/direct.py#L357

**Comment by Poloin34** [comment]
uhh, my bad, I had not seen it... Thanks

Le dim. 1 mai 2022 à 21:15, Mikhail Andreev ***@***.***> a
écrit :
