### ISSUE TITLE
For some reason clips_share_preview_to_feed is bein ignored

### ISSUE THREAD

**Issue by fredpiuma** [adw0rd/instagrapi#667]
Any one knows why clips (reels) if posted but feed preview not?

**Comment by adw0rd** [comment]
IDK, "Share Preview To Feed" works fine:

![image](https://user-images.githubusercontent.com/546889/168039187-fd33723b-1d98-4d93-b05b-29d5435271f8.png)

https://www.instagram.com/dhbastards/
