### ISSUE TITLE
user_followers amount doen't work

### ISSUE THREAD

**Issue by dakota95** [adw0rd/instagrapi#68]
when i run this code i get all followers of its user_id

```
 from instagrapi import Client

cl = Client()
cl.login(ACCOUNT_USERNAME, ACCOUNT_PASSWORD)
cl.request_timeout = 5 # seconds
followers = cl.user_followers(user_id, 15).keys()
```

i need to run this code on accounts with many followers (over 4k) and so it turns out very slow, too.

**Comment by adw0rd** [comment]
@dakota95 fixed in 1.4.0
