### ISSUE TITLE
Add skip business accounts

### ISSUE THREAD

**Issue by mikebgrep** [adw0rd/instagrapi#69]
If already don`t have It will be nice to skip business accounts when like comment and follow.

**Comment by adw0rd** [comment]
![image](https://user-images.githubusercontent.com/546889/103492147-f9718180-4e39-11eb-82b7-cad3d36876d0.png)

**Comment by adw0rd** [comment]
```
>>> cl.user_info(cl.user_id_from_username('forbes')).is_business
True

>>> cl.user_info(cl.user_id_from_username('adw0rd')).is_business
False
```
