### ISSUE TITLE
Direct profile share method

### ISSUE THREAD

**Issue by dheeraj009joshi** [adw0rd/instagrapi#693]
It should be like we share the profile from the url

**Comment by adw0rd** [comment]
@dheeraj009joshi implemented
![image](https://user-images.githubusercontent.com/546889/173165833-19795d06-ea27-49b5-afb4-8fd5cabd5865.png)

instagrapi 1.16.20

**Comment by dheeraj009joshi** [comment]
Thanks for this

**Comment by dheeraj009joshi** [comment]
You completed this in 2 min😳😳

**Comment by dheeraj009joshi** [comment]
Amazing👍👍
