### ISSUE TITLE
[BUG]  TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by olli-dot-dev** [adw0rd/instagrapi#697]
When trying to get the user_id from an account, I get the following erro:
`
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
`

My code basically looks like the following:

```
cl = Client()
cl.load_settings('/home/python/ig_dump.json')
accounts=["account_1", "account_2", "account_3", "account_4", "account_5", "account_6.dev"]

for user in accounts:
    user_id = int(cl.user_id_from_username(user))
```

The error occurs right aber the line user_id = int(cl.user_id_from_username(user))

**Comment by adw0rd** [comment]
Fixed in 1.16.19
