### ISSUE TITLE
[BUG] ChallengeUnknownStep when trying to log in

### ISSUE THREAD

**Issue by hittiks** [adw0rd/instagrapi#700]
Handle this when trying to log in:

`instagrapi.exceptions.ChallengeUnknownStep: ChallengeResolve: Unknown step_name "delta_acknowledge_approved" for "None" in challenge resolver: {'step_name': 'delta_acknowledge_approved', 'flow_render_type': 3, 'bloks_action': 'com.instagram.challenge.navigation.take_challenge', 'cni': 18196017667167850, 'challenge_context': '{"step_name": "delta_acknowledge_approved", "cni": 18196017667167850, "is_stateless": false, "challenge_type_enum": "GENERIC_PHISHED", "present_as_modal": false}', 'challenge_type_enum_str': 'GENERIC_PHISHED', 'status': 'ok'}`

And in my phone Instagram have window with message about phishing. Next step is EMAIL/SMS challenge.

How reproduce behavior:
- only with more times logining:)

**Comment by ghrlt** [comment]
Yes, Instagram think that your password got leaked.
Manually follow the instructions in the Instagram app and then login with the fresh session

**Comment by muners** [comment]
In another library, authentication processing was performed within the library with the code below, but can't it be done with this library?

https://github.com/dilame/instagram-private-api/blob/623a348343e34058c3a286693740aa3698aed3cc/examples/checkpoint.example.ts

In the past, there were cases where you could log in without problems on the smartphone app, but you would be asked for an authentication code only when logging in from the library. Will the app be locked now?
