### ISSUE TITLE
To add a Media property for comments_disabled/interactive

### ISSUE THREAD

**Issue by imagination901** [adw0rd/instagrapi#706]
Currently, there's an option to get  comment_count, but there's no way to know whether the comments are closed or not. 

This always returns 0 even if the comments are closed.

Is it possible to add this functionality?

**Comment by kingbotss** [comment]
with media_info you can get that details.

**Comment by imagination901** [comment]
Hey kingbotss, thanks for your reply. The thing is media_info returns a Media object. Below, you can see the declaration of this class. There's no such property there. The only thing close enough is comment_count, which is 0 for both posts with 0 comments and for posts with comments disabled. There's no way to differentiate those. There's no other attribute like comments_disabled: bool or something like that. Hence, my request to add this feature.

class Media(BaseModel):
    pk: str
    id: str
    code: str
    taken_at: datetime
    media_type: int
    product_type: Optional[str] = ""  # igtv or feed
    thumbnail_url: Optional[HttpUrl]
    location: Optional[Location] = None
    user: UserShort
    comment_count: Optional[int] = 0 #-----------------------< This
    like_count: int
    has_liked: Optional[bool]
    caption_text: str
    accessibility_caption: Optional[str]
    usertags: List[Usertag]
    video_url: Optional[HttpUrl]  # for Video and IGTV
    view_count: Optional[int] = 0  # for Video and IGTV
    video_duration: Optional[float] = 0.0  # for Video and IGTV
    title: Optional[str] = ""
    resources: List[Resource] = []
    clips_metadata: dict = {}

**Comment by kingbotss** [comment]
The media info endpoint returns more details, You can check.

**Comment by imagination901** [comment]
Here's the output of the media_info function for this random post with comments turned off https://www.instagram.com/p/BzKYwnpi712/
I'm not sure where to look for the attribute you refer to.

media_info(): 
pk='2074579472581639542' 
id='2074579472581639542_11578752162' 
code='BzKYwnpi712' 
taken_at=datetime.datetime(2019, 6, 26, 6, 6, 6, tzinfo=datetime.timezone.utc) 
media_type=1 
product_type='' 
thumbnail_url=HttpUrl('https://instagram.fifo4-1.fna.fbcdn.net/v/t51.2885-15/64613952_883010682035863_9110585929113117144_n.jpg?stp=dst-jpg_e35&_nc_ht=instagram.fifo4-1.fna.fbcdn.net&_nc_cat=107&_nc_ohc=w6vMd5ByxJMAX9O2HBg&edm=AP_V10EBAAAA&ccb=7-5&oh=00_AT-1RFYV7rNtvTP06JQpRoTuJz9GfOnZW8eAM7Tdt69WIg&oe=62AC7960&_nc_sid=4f375e', 
scheme='https', 
host='instagram.fifo4-1.fna.fbcdn.net', 
tld='net', 
host_type='domain', 
port='443', 
path='/v/t51.2885-15/64613952_883010682035863_9110585929113117144_n.jpg', 
query='stp=dst-jpg_e35&_nc_ht=instagram.fifo4-1.fna.fbcdn.net&_nc_cat=107&_nc_ohc=w6vMd5ByxJMAX9O2HBg&edm=AP_V10EBAAAA&ccb=7-5&oh=00_AT-1RFYV7rNtvTP06JQpRoTuJz9GfOnZW8eAM7Tdt69WIg&oe=62AC7960&_nc_sid=4f375e') 
location=None 
user=UserShort(pk='11578752162', username='sensodyne_latvia', full_name='Sensodyne_latvia', profile_pic_url=HttpUrl('https://instagram.fifo4-1.fna.fbcdn.net/v/t51.2885-19/51600999_358922564721327_7029198993380868096_n.jpg?stp=dst-jpg_s150x150&_nc_ht=instagram.fifo4-1.fna.fbcdn.net&_nc_cat=103&_nc_ohc=TRwsGkaSgZkAX9q8WYh&edm=AP_V10EBAAAA&ccb=7-5&oh=00_AT9MMz2OPgjCAV3PEt86CKhGPNddiQYQSyFz4hQVI1hy4A&oe=62AC0F3F&_nc_sid=4f375e', scheme='https', host='instagram.fifo4-1.fna.fbcdn.net', tld='net', host_type='domain', port='443', path='/v/t51.2885-19/51600999_358922564721327_7029198993380868096_n.jpg', query='stp=dst-jpg_s150x150&_nc_ht=instagram.fifo4-1.fna.fbcdn.net&_nc_cat=103&_nc_ohc=TRwsGkaSgZkAX9q8WYh&edm=AP_V10EBAAAA&ccb=7-5&oh=00_AT9MMz2OPgjCAV3PEt86CKhGPNddiQYQSyFz4hQVI1hy4A&oe=62AC0F3F&_nc_sid=4f375e'), profile_pic_url_hd=None, is_private=False, stories=[]) 
comment_count=0 
like_count=30 
has_liked=None 
caption_text='Vai Tu zināji, ka ieteicams skalot muti 30 sekundes līdz 1 minūtei ar tam paredzēto līdzekli, pirms to izspļaut? Pārliecinies, ka lieto mutes dobuma kopšanas produktus pareizi, lai varētu saskatīt vēlamos rezultātus 😊\n.\n.\n.\n#sensodyne #latvia #smile #healthcare #enjoylife #sensitivity #sensitiveteeth #smile #smilewide #springsmile #beautifulsmile' 
accessibility_caption=None 
usertags=[] 
video_url=None 
view_count=0 
video_duration=0.0 
title='' 
resources=[] 
clips_metadata={}

**Comment by imagination901** [comment]
Thanks for the clue, kingbots. Indeed, the media_info function calls a number of functions, the final one of which is extract_media_gql.  All you have to do is to extend the Media class and add a property for comments_possible. I consider this issue resolved.
