### ISSUE TITLE
ValidationError: 1 validation error for User external_url

### ISSUE THREAD

**Issue by mikebgrep** [adw0rd/instagrapi#71]
ValidationError apear after 
  `  user_id = cl.user_id_from_username(each_user)`
```
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for User
external_url

```
how to except this Error do I need to import something?

**Comment by adw0rd** [comment]
@mikebgrep Can you provide the name of the user who has this problem reproduced?

```
In [3]: cl.user_id_from_username('adw0rd')
Out[3]: 1903424587
```

**Comment by mikebgrep** [comment]
I will try to reproduce it it was from .hashtag_medias_recent(), media_like()

**Comment by mikebgrep** [comment]
They restrict me I don't know its will be in help hashtag was fashionblogger

**Comment by adw0rd** [comment]
@mikebgrep I need username

**Comment by mikebgrep** [comment]
If appear again i will catch the username
