### ISSUE TITLE
[BUG] media.location returns None even if location is present in the actual post

### ISSUE THREAD

**Issue by marcouderzo** [adw0rd/instagrapi#747]
Hi,
I'm having some issues with retrieving locations from posts of a profile.
This piece of code
```
medias = client.user_medias(userid)

for m in medias:
   print(m.location)
```
always prints None, even if all medias are returned correctly and most of the posts do have locations when checking the instagram page itself. I checked the printed output, and indeed `location=None`.

Why is that? Am I missing something?

Thanks

**Comment by adw0rd** [comment]
Try using `user_medias_v1`:

```
>>> medias = cl.user_medias_v1(cl.user_id)
>>> for m in medias:
>>>     print(m.location)

None
None
pk=449507392 name='Norway' phone='' website='' category='' hours={} address=None city=None zip=None lng=8.0 lat=61.0 external_id=108646839159211 external_id_source='facebook_places'

```

**Comment by marcouderzo** [comment]
Thanks, this seems to work
