### ISSUE TITLE
Delay between requests

### ISSUE THREAD

**Issue by Theder** [adw0rd/instagrapi#75]
Are there any guidelines for the length of the delay between requests (for scraping users info)? I use a delay of 20 seconds between each request and 50 seconds after every 10 request. But sometimes error 302 occurs when it requires you to enter a security code sent by mail/sms. Error 429 sometimes occurs too, but rarely.
Is it worth increasing the delays between requests in this case? Or are there some other ways to avoid such errors?

**Comment by adw0rd** [comment]
@Theder Instagram often changes its conditions (limits) and it is difficult to predict the algorithm for a long time. If you research the current timings and share information it will be great!
