### ISSUE TITLE
[BUG] Receiving a JSON Parse error

### ISSUE THREAD

**Issue by ItzmeSwapy** [adw0rd/instagrapi#752]
`Status 200: JSONDecodeError in public_request (url=https://www.instagram.com/myusername/?__a=1) >>> for (;;);{"__ar":1,"error":1357004,"errorSummary":"Sorry, something went wrong","errorDescription":"Please try closing and re-opening your browser window.","payload":null,"hsrp":{"hblp":{"consistency":{"rev":1005773003}}},"lid":"7114874598313241892"}`

this is the error that I am receiving

**Comment by adw0rd** [comment]
@ItzmeSwapy show your code and  full traceback

**Comment by kingbotss** [comment]
`for (;;);`
Your response has it. So it is throwing error. Publc_request may not work all the time. You may need to have login.

**Comment by adityaa-codes** [comment]
try using user_info_by_username_v1(username)

**Comment by LordAliCloner** [comment]
> `Status 200: JSONDecodeError in public_request (url=https://www.instagram.com/myusername/?__a=1) >>> for (;;);{"__ar":1,"error":1357004,"errorSummary":"Sorry, something went wrong","errorDescription":"Please try closing and re-opening your browser window.","payload":null,"hsrp":{"hblp":{"consistency":{"rev":1005773003}}},"lid":"7114874598313241892"}`
> 
> this is the error that I am receiving

just go to line 166 in public.py and edit public_a1_request=>

```
def public_a1_request(self, endpoint, data=None, params=None, headers=None):
        url = self.PUBLIC_API_URL + endpoint.lstrip("/")
        if params:
            params.update({"__a": 1,'__d':'dis'})
        else:
            params = {"__a": 1,'__d':'dis'}
```

**Comment by LordAliCloner** [comment]
> > > `Status 200: JSONDecodeError in public_request (url=https://www.instagram.com/myusername/?__a=1) >>> for (;;);{"__ar":1,"error":1357004,"errorSummary":"Sorry, something went wrong","errorDescription":"Please try closing and re-opening your browser window.","payload":null,"hsrp":{"hblp":{"consistency":{"rev":1005773003}}},"lid":"7114874598313241892"}`
> > 
> > 
> > > 
> > 
> > 
> > > this is the error that I am receiving
> > 
> > 
> > just go to line 166 in public.py and edit public_a1_request=>
> > ```
> > 
> > def public_a1_request(self, endpoint, data=None, params=None, headers=None):
> > 
> >         url = self.PUBLIC_API_URL + endpoint.lstrip("/")
> > 
> >         if params:
> > 
> >             params.update({"__a": 1,'__d':'dis'})
> > 
> >         else:
> > 
> >             params = {"__a": 1,'__d':'dis'}
> > ```
> 
> Thanks for responding, this might work

^_^            ^_^

**Comment by coisan** [comment]
> > `Status 200: JSONDecodeError in public_request (url=https://www.instagram.com/myusername/?__a=1) >>> for (;;);{"__ar":1,"error":1357004,"errorSummary":"Sorry, something went wrong","errorDescription":"Please try closing and re-opening your browser window.","payload":null,"hsrp":{"hblp":{"consistency":{"rev":1005773003}}},"lid":"7114874598313241892"}`
> > this is the error that I am receiving
> 
> just go to line 166 in public.py and edit public_a1_request=>
> 
> ```
> def public_a1_request(self, endpoint, data=None, params=None, headers=None):
>         url = self.PUBLIC_API_URL + endpoint.lstrip("/")
>         if params:
>             params.update({"__a": 1,'__d':'dis'})
>         else:
>             params = {"__a": 1,'__d':'dis'}
> ```

This worked for me too. Thanks!

**Comment by LordAliCloner** [comment]
> > > `Status 200: JSONDecodeError in public_request (url=https://www.instagram.com/myusername/?__a=1) >>> for (;;);{"__ar":1,"error":1357004,"errorSummary":"Sorry, something went wrong","errorDescription":"Please try closing and re-opening your browser window.","payload":null,"hsrp":{"hblp":{"consistency":{"rev":1005773003}}},"lid":"7114874598313241892"}`
> > > this is the error that I am receiving
> > 
> > 
> > just go to line 166 in public.py and edit public_a1_request=>
> > ```
> > def public_a1_request(self, endpoint, data=None, params=None, headers=None):
> >         url = self.PUBLIC_API_URL + endpoint.lstrip("/")
> >         if params:
> >             params.update({"__a": 1,'__d':'dis'})
> >         else:
> >             params = {"__a": 1,'__d':'dis'}
> > ```
> 
> This worked for me too. Thanks!

🙂🙂

**Comment by trevtravtrev** [comment]
> [LordAliCloner](/LordAliCloner)

Can you open a PR to fix this? would rather not have to fork and maintain separately 👍

**Comment by trevtravtrev** [comment]
> > `Status 200: JSONDecodeError in public_request (url=https://www.instagram.com/myusername/?__a=1) >>> for (;;);{"__ar":1,"error":1357004,"errorSummary":"Sorry, something went wrong","errorDescription":"Please try closing and re-opening your browser window.","payload":null,"hsrp":{"hblp":{"consistency":{"rev":1005773003}}},"lid":"7114874598313241892"}`
> > this is the error that I am receiving
> 
> just go to line 166 in public.py and edit public_a1_request=>
> 
> ```
> def public_a1_request(self, endpoint, data=None, params=None, headers=None):
>         url = self.PUBLIC_API_URL + endpoint.lstrip("/")
>         if params:
>             params.update({"__a": 1,'__d':'dis'})
>         else:
>             params = {"__a": 1,'__d':'dis'}
> ```

This solution has now been merged into instagrapi as of yesterday. A new issue has now popped up where user data public_email and latitiude and longitude and (possibly more) are now all returning 'None' even when they should be returning something. Issues #774  and #775 are likely related. Any ideas how this could have caused those?

**Comment by LordAliCloner** [comment]
> > > `Status 200: JSONDecodeError in public_request (url=https://www.instagram.com/myusername/?__a=1) >>> for (;;);{"__ar":1,"error":1357004,"errorSummary":"Sorry, something went wrong","errorDescription":"Please try closing and re-opening your browser window.","payload":null,"hsrp":{"hblp":{"consistency":{"rev":1005773003}}},"lid":"7114874598313241892"}`
> > > this is the error that I am receiving
> > 
> > 
> > just go to line 166 in public.py and edit public_a1_request=>
> > ```
> > def public_a1_request(self, endpoint, data=None, params=None, headers=None):
> >         url = self.PUBLIC_API_URL + endpoint.lstrip("/")
> >         if params:
> >             params.update({"__a": 1,'__d':'dis'})
> >         else:
> >             params = {"__a": 1,'__d':'dis'}
> > ```
> 
> This solution has now been merged into instagrapi as of yesterday. A new issue has now popped up where user data public_email and latitiude and longitude and (possibly more) are now all returning 'None' even when they should be returning something. Issues #774 and #775 are likely related. Any ideas how this could have caused those?

Send me some examples

**Comment by peter6C6F6C** [comment]
bump, this is not closed or resolved.
