### ISSUE TITLE
[BUG] Story downloader returns invalid media_id error

### ISSUE THREAD

**Issue by HellBoy-OP** [adw0rd/instagrapi#765]
**Describe the bug**
Unable to download stories using `story_download`

**To Reproduce**
```python3
pk = cl.story_pk_from_url(url)
cl.story_download(pk, folder=dl_path)
```

**Traceback**
`Invalid media_id 63355746059527093815`

**Expected behavior**
Download the story to defined `dl_path` folder.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Python version [3.10.2]
 - instagrapi version [1.16.20]

**Additional context**
I have checked the `url` and `dl_path` and everything is okay. It should download the story of `url` to desired path but gives invalid `media_id` error instead.

**Comment by HellBoy-OP** [comment]
> @HellBoy-OP what was the url?


**highlight:** `https://www.instagram.com/s/aGlnaGxpZ2h0OjE4MDM2Mzc2MTUzMzQ1Nzky?story_media_id=2753154602009861343_48567565326&igshid=YmMyMTA2M2Y=`

**24 hrs story:** `https://instagram.com/stories/ctfu_.radhe/2881600227196194541?utm_source=ig_story_item_share&igshid=MDJmNzVkMjY=`

Both returns same error. 
Also I tried removing `&igshid=MDJmNzVkMjY=` from links, but same.

**Comment by 411A** [comment]
This error is came back again: `Invalid media_id` (`instagrapi.exceptions.ClientUnauthorizedError: 401 Client Error: Unauthorized for url:...`).
I used session file with same info as my device settings on client. It only happens on stories and highlights.
