### ISSUE TITLE
Question: Convert results from Instagram to json

### ISSUE THREAD

**Issue by reisenmachtfreude** [adw0rd/instagrapi#768]
I would like to export my followers data to a JSON file. The following code works but the conversion to JSON seems a bit ugly (but necessary since Objects of the class UserShort are returned). It would be great if anyone could give me a hint about how to realize a more pretty solution.
```
import json
from instagrapi import Client

cl = Client()
cl.login("...", "...")

# Get my followers
followers = cl.user_followers(cl.user_id)

followers_json = []
for pk, user_short in followers.items():
	followers_json.append(user_short.dict())

with open("followers.json",'w') as f:
	json.dump(followers_json, f)
```

**Comment by adw0rd** [comment]
Use `followers.values()` and `user_short.json()`

and read this https://pydantic-docs.helpmanual.io/


https://github.com/adw0rd/instagrapi/blob/master/instagrapi/types.py#L75

<img width="498" alt="image" src="https://user-images.githubusercontent.com/546889/178671123-b710be52-69de-41d4-8e64-4971e92ed62e.png">

**Comment by reisenmachtfreude** [comment]
Thank you very much!
