### ISSUE TITLE
Small spelling error

### ISSUE THREAD

**Issue by msr8** [adw0rd/instagrapi#784]
Dont think it requires a whole issue for it but I just found it out and thought you should know. In the `direct_send_video` function, it prints out `Analizing` instead of `Analyzing`. Screenshots attached below

![Screenshot 2022-07-15 at 12 25 56](https://user-images.githubusercontent.com/79649185/179168693-9b26643a-1bc8-4db7-bab9-3c10a568e0eb.png)
![Screenshot 2022-07-15 at 12 26 06](https://user-images.githubusercontent.com/79649185/179168725-a169093f-425d-4700-8bd6-02e5d0a541e5.png)

**Comment by adityaa-codes** [comment]
Solved
