### ISSUE TITLE
[BUG] Client won't call its methods

### ISSUE THREAD

**Issue by KnightHok** [adw0rd/instagrapi#786]
I wanted to make a Class called Instagram so that when I initialize it a Client object is already available. The code seems to work in its own main function but when I call the Instagram class from another file I keep getting this error and I'm not sure why.

**To Reproduce**
This is the code for the Instagram class. It only works when I use its file as main
`
from instagrapi import Client`
`import os.path`
`import os`
`from dotenv import load_dotenv
`

`class Instagram:`
    `instagram_session = None`
    `def __init__(self, username, password):`
        `self.instagram_session = Client()`
        `self.instagram_session.login(username, password)`

    def submitMedia(self, file_path, caption):
        if os.path.isfile(file_path):
            current_file_ext = file_path[-4:]

            if current_file_ext == ".jpg":
                print("Uploading Instagram Photo")
                return self.instagram_session.photo_upload(file_path, caption)
            elif current_file_ext == ".mp4":
                print("Uploading Instagram Reel")
                return self.instagram_session.clip_upload(file_path, caption)

`if __name__ == "__main__":`
    `load_dotenv("../../.env")`

    user_name = os.getenv("INSTAGRAM_USERNAME")
    password = os.getenv("INSTAGRAM_PASSWORD")
    session = Instagram(user_name, password=password)
    session.submitMedia(
        "/Users/reza/Documents/Side Projects/Discord Social Media/test2.mp4", "")
`

Below is the file I'm using to import the Instagram Class then calling it 

`from insta2 import Instagram`
`import os`
`from dotenv import load_dotenv`
`user_name = os.getenv("INSTAGRAM_USERNAME")`
`password = os.getenv("INSTAGRAM_PASSWORD")`
`client = Instagram(user_name, password)`
`client.submitMedia("/Users/reza/Documents/Side Projects/Discord Social Media/test2.mp4", "")
`

**Traceback**
This is the error I get when I try using the Instagram Class from another file

Traceback (most recent call last):
  File "/Users/reza/Documents/Side Projects/Discord Social Media/social_media/Instagram/test.py", line 9, in <module>
    client = insta2.Instagram(user_name, password)
  File "/Users/reza/Documents/Side Projects/Discord Social Media/social_media/Instagram/insta2.py", line 12, in __init__
    self.instagram_session.login(username, password)
  File "/Users/reza/Documents/Side Projects/Discord Social Media/mydiscord/lib/python3.9/site-packages/instagrapi/mixins/auth.py", line 377, in login
    enc_password = self.password_encrypt(password)
  File "/Users/reza/Documents/Side Projects/Discord Social Media/mydiscord/lib/python3.9/site-packages/instagrapi/mixins/password.py", line 22, in password_encrypt
    aes_encrypted, tag = cipher_aes.encrypt_and_digest(password.encode("utf8"))
AttributeError: 'NoneType' object has no attribute 'encode'

**Expected behavior**
I was expecting the instance of the Instagram Class to be able to be able to access its Client variable and make method calls

**Screenshots**
<img width="884" alt="Screen Shot 2022-07-16 at 9 24 34 AM" src="https://user-images.githubusercontent.com/53544848/179356843-c7a04b6e-5264-4ff1-8268-1e9b3bd23f39.png">
<img width="882" alt="Screen Shot 2022-07-16 at 9 25 30 AM" src="https://user-images.githubusercontent.com/53544848/179356847-466f83e9-4f17-43c9-aa75-fa156892f9f5.png">

 - OS: [Mac OSX Monterey 12.3.1]
 - Python version [3.9.1]
 - instagrapi version [1.16.21]
 - moveipy version [1.0.3] (I don't think I'm actively using this module is any of my calls but I provided the version that is in my environment)
 - imagemagick version if used

**Additional context**
This is my first github issues post so let me know if it's not detailed enough or if I'm misinterpreting any concepts. Any type of feedback is good. Also this module has been cool great team behind it.

**Comment by adw0rd** [comment]
Your error says that you are passing NoneType as a password, learn how to work with the debugger (pudb, pdb, ipdb...)
