### ISSUE TITLE
Editing Bio

### ISSUE THREAD

**Issue by Jammy108** [adw0rd/instagrapi#8]
Thanks for the great API wrapper!

It would be great if a way to edit the logged in account's bio could be added! Things such as changing the profile picture, name, bio, link etc.

No problem if it can't be done, thanks.

**Comment by adw0rd** [comment]
@Jammy108 I will implement this week

**Comment by adw0rd** [comment]
@Jammy108 finished https://github.com/adw0rd/instagrapi/blob/master/instagrapi/account.py#L42

Examples: https://github.com/adw0rd/instagrapi/blob/master/tests.py#L647

**Comment by adw0rd** [comment]
Added to https://github.com/adw0rd/instagrapi/blob/master/README.md
