### ISSUE TITLE
[QUESTION] What is the difference between pk and id?

### ISSUE THREAD

**Issue by msr8** [adw0rd/instagrapi#817]
Like take a post for example. It has two unique values, pk and id, whats the difference?

**Comment by vapefy** [comment]
`media_id` - String ID `"{media_id}_{user_id}"`, e.g. `"2277033926878261772_1903424587"`
`media_pk` - Integer ID (real media id), e.g. `2277033926878261772`

**Comment by msr8** [comment]
Ohhh okay, and what's the matter with a user's pk and id?

**Comment by vapefy** [comment]
there is no different i guess. `User` has no id, just a pk. ik some arguments of functions has user_id, but it is the same.
check this out, it helps a lot. [https://adw0rd.github.io/instagrapi/](url)

**Comment by msr8** [comment]
Thank you!
