### ISSUE TITLE
[BUG] The username you entered doesn't appear to belong to an account

### ISSUE THREAD

**Issue by v-bazhenov** [adw0rd/instagrapi#818]
Hi,

When trying to login with
`cl.login(username, password)`

I'm getting this error message
`The username you entered doesn't appear to belong to an account. Please check your username and try again.`

The username and password are correct and I'm able to login via Instagram App or desktop.
This is weird as it works fine when I run this from my local machine from python shell.
But it throws me the above error if I run it from AWS instance.

Any ideas?

Also I noticed that the following error is thrown:

`HTTPError: 400 Client Error: Bad Request for url: https://i.instagram.com/api/v1/accounts/login/`

I also tried using proxy - but it does not help

**Comment by adw0rd** [comment]
This message return back from instagram, I don't know why. If you help the project and investigate the reasons, then I will be extremely grateful to you!

**Comment by LoreVanOudenhove** [comment]
I have noticed the exact same bug when using AWS Lambda (with/without using a proxy)...
The weird thing is that it seems to work from time to time, but then suddenly the Error shows up.

**Comment by alex-96-eng** [comment]
This doesn't seem to happen much when it's local, but soon as I deploy to Azure it throws this error.

**Comment by bilakos26** [comment]
I was trying to work with proxies and this error was popping up when one proxy wasn't good enough.

**Comment by pama1999** [comment]
Alright same thing is happening to me,

Working on my local pc works perfect no login issue or anything,

but as soon I run it on a windows server, I get the same login error, although I have to mention that it works sometimes and sometimes not

**Comment by petersevera** [comment]
Got this error first time yesterday, tried from many proxies - always the same error... It was working fine from those IP for months... Please, help

**Comment by petersevera** [comment]
changing proxy ip helps

**Comment by LoreVanOudenhove** [comment]
Which type of proxies do you use?

> changing proxy ip helps

Which type of proxies do you use?

**Comment by pama1999** [comment]
tried on a linux server machine and it works! 

switched to another windows server with another ip and I get this error "sometimes"

**Comment by Siegi96** [comment]
I also get this message quite frequently, even when using residential IPs. Same accounts with same IPs work fine when I do a login with another of my services, where I use a selenium script to login. So this definetly has something to do with the login logic of the library @adw0rd .

**Comment by F481** [comment]
@adw0rd This issue is not resolved. You should reopen it, so the community can see that this bug is still existing and can work on it. I have the same problem and like some other users changing the proxy does not help.

I had the situation that it was always working on my local machine (MacBook Pro) while developing. It did not work after uploading to AWS Lambda, Azure Functions or Google Cloud Functions, but in parallel it was still working on my local machine. I did some testing and deployed it to a Raspberry Pi in my home network (same outgoing IP as my machine). Running the script on the RPi resolved in the above error. After that it's not working any longer on my local machine too. Also not after getting a new IP address.

**Comment by adw0rd** [comment]
@F481 Changing proxies always helps me, but if you find a new way to get out of this block, then send a PR

**Comment by F481** [comment]
Just a hint for the people who also notice this error and using / changing proxy does not help.

I got it work for me now by changing "country", "country_code", "Phone code", "locale" and "timezone_offset" in the file mixins/auth.py to my "real" values. In addition you can try to play around with the "USER_AGENT_BASE" in config.py.

**Comment by adw0rd** [comment]
@F481 All this can be changed through the settings: load_settings, set_settings, get_settings

This is described with examples in [the documentation](https://adw0rd.github.io/instagrapi/usage-guide/interactions.html)

**Comment by imJunaidAfzal** [comment]
Anyone found any permanent solution for this issue?

**Comment by pedrocastellanos** [comment]
I have the same problem. Any solution?

**Comment by adw0rd** [comment]
> I have the same problem. Any solution?

use another proxy

**Comment by pedrocastellanos** [comment]
@adw0rd I'm not using proxy

**Comment by adw0rd** [comment]
> @adw0rd I'm not using proxy

That is the problem
