### ISSUE TITLE
[BUG] cl.user_stories return Instagram HTML code

### ISSUE THREAD

**Issue by kostyakoz** [adw0rd/instagrapi#825]
**Describe the bug**
Hello again. `cl.user_stories` return to me HTML code of Instagram web page in logs, can anything be done to handle it? It so long so I can't even post it here, check https://gist.github.com/kostyakoz/6ae965812b29470fa70367ac5f74463c

**To Reproduce**
Provide a piece of code to reproduce the problem.

**Traceback**
Before HTML code I see this:

```
03/08/2022 08:24:17 public.py: [INFO][Thread-1] - [socks5://xxx:xxx@xxx:10088] [200] GET https://www.instagram.com/challenge/?next=/graphql/query/%253Fvariables%253D%25257B%252522reel_ids%252522%25253A%25255B5744628421%25255D%25252C%252522precomposed_overlay%252522%25253Afalse%25257D%2526query_hash%253D303a4ae99711322310f25250d988f3b7
03/08/2022 08:24:17 public.py: [ERROR][Thread-1] - Status 200: JSONDecodeError in public_request (url=https://www.instagram.com/challenge/?next=/graphql/query/%253Fvariables%253D%25257B%252522reel_ids%252522%25253A%25255B5744628421%25255D%25252C%252522precomposed_overlay%252522%25253Afalse%25257D%2526query_hash%253D303a4ae99711322310f25250d988f3b7) >>>
```

Why does this use `public.py` for Stories? Stories are only available with authorisation 🤔 and I'm using client login.

**Desktop (please complete the following information):**
- OS: 18.04.5
- Python version 3.8.0
- instagrapi version 1.16.27

**Comment by adw0rd** [comment]
@kostyakoz try using `cl.user_stories_v1`

**Comment by adw0rd** [comment]
> Why does this use public.py for Stories? Stories are only available with authorisation 🤔 and I'm using client login.

If you have good proxies, then `cl.user_stories` will work
