### ISSUE TITLE
2 factor authentication

### ISSUE THREAD

**Issue by alimardani1994** [adw0rd/instagrapi#83]
I have enabled 2 factor authentication for my account with my phone number, and when I call login method, instagram sends me code on my phone, but login method returns true, and actually client does not login.
any idea for this issue?

**Comment by adw0rd** [comment]
2FA implemented yesterday:

`login(username, password, verification_code=’<2FA CODE>’)`

https://adw0rd.github.io/instagrapi/usage-guide/interactions.html
