### ISSUE TITLE
[BUG]Lamadava Service: Too Many Redirects/Instagram Server Error/No Free Accounts

### ISSUE THREAD

**Issue by SoonWhy** [adw0rd/instagrapi#831]
When I use the Lamadava Service (v1/user/by/id) today, it does not work with the error: Too many redirects.

And when I try the api online at https://api.lamadava.com/docs#/, it shows the same info:

![Snipaste_2022-08-06_12-08-52](https://user-images.githubusercontent.com/62386447/183233037-93fa4aab-ec59-4981-9cb4-25fea7b3b838.jpg)

I've tried to change the api.lamadava.com to api.instagrapi.com but it still does not work.

Could U help me with it？ Thank U!

**Comment by SoonWhy** [comment]
The service works well in last 7 days. And I believe I have used for around 60,000 requests which is less than 100, 000 requests/month.

**Comment by SoonWhy** [comment]
Besides, when I try the api v1/user/by/username, there's another problem:
![image](https://user-images.githubusercontent.com/62386447/183233133-fff70121-eebd-4eec-81c4-1ba1efb21ef0.png)
 Maybe this can help you to fix the bug~

**Comment by SoonWhy** [comment]
It works now. It seems like that waiting for some hours can handle this problem.
Anyway, thanks for your service~

**Comment by SoonWhy** [comment]
Sorry for bothering you, but My service dose not work now. I check the server for the script and I found nearly every request shows that: Too Many Redirects.
And several of them shows that Instagram Server Error.
I try to use different procy and online 'try it out', it still does not work. Could u help me? Thanks!

**Comment by SoonWhy** [comment]
Sorry for bothering you, but My service dose not work now. I check the server for the script and I found nearly every request shows that: Too Many Redirects.
And several of them shows that Instagram Server Error.
I try to use different procy and online 'try it out', it still does not work. Could u help me? Thanks!

**Comment by SoonWhy** [comment]
Now I receive a new error info: No free accounts. I want to know that this is some problem of my own Lamadava account or it is caused by your service TAT. If it is caused by your service, I do deeply hope that it can be fixed soon.

**Comment by SoonWhy** [comment]
@adw0rd Druing last 3 days, I find that the problem usually happened between  00:00 (UTC) to 06:00 (UTC).
Although there's enough time for me to get data in a day. But it still cause some problem and make meaningless bill cost for Lamadava. 
I'll appreciate it that you'll reply soon. Thanks.

**Comment by adw0rd** [comment]
@SoonWhy this occurs when instagram massively bans accounts, and at this time I'm sleeping and I can't react. I will try to fix this problem this month
