### ISSUE TITLE
[BUG] story liker not working 

### ISSUE THREAD

**Issue by anandhashok** [adw0rd/instagrapi#832]
### Compensate with donations ($10 and more) for the time I spent to fix problems or send  me your [Pull Request](https://github.com/adw0rd/instagrapi/pulls) with fixes

[![Donate](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/adw0rd)

* Bitcoin: 3KHgnvNNWio6wyQ71cgNeBQojXStxzkzfd
* Ethereum: 0x6e644c6b975B47801072b07a9a57DDfEC10DE74F
* https://paypal.me/adw0rd
* For Russia: СБП, Qiwi и тп: **+79118107609**

**Describe the bug**

**To Reproduce**
Provide a piece of code to reproduce the problem.

**Traceback**
Show your full traceback so that it is clear where exactly the error occurred.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 21.04]
 - Python version [e.g. 3.8.3]
 - instagrapi version [e.g. 1.9.3, not "latest"]
 - moveipy version if used
 - imagemagick version if used

**Additional context**

**Comment by adw0rd** [comment]
Cannot reproduce, show your code
