### ISSUE TITLE
Open "confirm email" link

### ISSUE THREAD

**Issue by Siegi96** [adw0rd/instagrapi#835]
Hey, I added my a new email to my account and sent the confirmation mail, now I want to automatically confirm the email by opening the link from the email. The link is https://www.instagram.com/accounts/confirm_email/{code}, if you open it you have to log in manually, except when you are already logged in. Is it possible to just call this link using the _send_private_request() method when the session data is already in cache?

**Comment by adw0rd** [comment]
I do it like this:

```
cl.inject_sessionid_to_public()
cl.public.get(confirm_email_url)
```
