### ISSUE TITLE
The username you entered doesn't appear to belong to an account. Please check your username and try again.

### ISSUE THREAD

**Issue by petersevera** [adw0rd/instagrapi#836]
Привет!

Помогите, плиз. Все работало, более или менее. Теперь с телефона все также пашет, сижу со своего аккаунта, ничего не менял. А вот скрипт выдает с любого айпи:
The username you entered doesn't appear to belong to an account. Please check your username and try again.

Раньше ни разу такого не было... Куда копать?

**Comment by petersevera** [comment]
Changing proxy ip helps

**Comment by alex-96-eng** [comment]
Dupe of: https://github.com/adw0rd/instagrapi/issues/818
