### ISSUE TITLE
PhotoNotUpload ERROR

### ISSUE THREAD

**Issue by jalilrooney** [adw0rd/instagrapi#84]
Hello everyone!

I have been trying to upload a photo for hours now but I couldn't make it.

- I wrote the full path to my photo location
- the code I used is: `cl.photo_upload(path=picture_path, caption= description)`
- The error I'm getting is:
`instagrapi.exceptions.PhotoNotUpload: {"debug_info":{"retriable":false,"type":"ProcessingFailedError","message":"Request processing failed"}}`

Does anyone here knows what might be the problem? I thought a lot about the resolution, but when I checked instagram photo requirements I found out that they accept '1080x1080' and my picture's format is PNG

Thanks a lot in advance

**Comment by DeusAres** [comment]
Issue still persists. Trying to upload PIL images, saved as PNG or JPG with correct conversion, still no luck. Could it be file size?

**Comment by DeusAres** [comment]
Found the problem, the images are not allowed to be uploaded as PNG. Secure that the format is JPG

**Comment by adw0rd** [comment]
@DeusAres thank you!

**Comment by msr8** [comment]
OHHHH, I thought this issue was because of the size, thanks!

**Comment by vizvasrj** [comment]
the square image is best to upload. try cropping before upload

**Comment by Never367** [comment]
I got the same error with JPG image format, dimensions 1200*1600.
Previously, the same images were loaded without problems.

**Comment by zahrevsky** [comment]
@DeusAres Thank you!

**Comment by trexgris** [comment]
Same issue with a JPG

**Comment by adw0rd** [comment]
@trexgris Everything works fine with JPG downloaded from instagram. Check what's wrong with your files

**Comment by betabrandao** [comment]
I uploaded square photo 1080p with 96dpi successfully, but other formats got error.
