### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sheldygg** [adw0rd/instagrapi#844]
Hello, I'm building a bot to download media from instagram and I'm using this library for that.

i use this method **user_medias** then turn it into a dict and get this https://pastebin.com/74UN7T75

from the dict you can get the url to photo, but i get some bad link where my photo is cropped
its my original post https://www.instagram.com/p/CcjC4AMNY7v/

I think this is due to the fact that the library does not go through each post, but goes to the profile and extracts only the preview of the photo where it is cropped

**Comment by adw0rd** [comment]
@sheldygg show the correct link and tell me where to get it

**Comment by sheldygg** [comment]
@adw0rd what's wrong with the link?

**Comment by adw0rd** [comment]
@sheldygg I was talking about "from the dict you can get the url to photo", give me the correct url of the photo. I don't know where to get it

**Comment by sheldygg** [comment]
@JulienMaille https://instagram.fiev13-1.fna.fbcdn.net/v/t51.2885-15/278888544_1238521416955050_8322967733642174444_n.jpg?stp=c0.180.1440.1440a_dst-jpg_e35_s640x640_sh0.08&_nc_ht=instagram.fiev13-1.fna.fbcdn.net&_nc_cat=106&_nc_ohc=hC2XWVGUWe8AX83Vtcz&tn=MOhuts52L_MLde5V&edm=APU89FABAAAA&ccb=7-5&oh=00_AT8PKEWsDH940R70ZdyWMb9INHFElu24eozR5I9qxoI5iA&oe=63013F5C&_nc_sid=86f79a

**Comment by adw0rd** [comment]
@sheldygg it's the same as in https://pastebin.com/74UN7T75
you said there is a better option of photo
