### ISSUE TITLE
Any way to add web browser's sessions and cookies to instagrapi?

### ISSUE THREAD

**Issue by SaeedFazlollahzadeh** [adw0rd/instagrapi#908]
**Is your feature request related to a problem? Please describe.**
Not sure if it's problem or feature or even exists in this project.
I want to keep session of my last login, or even read login session and cookie from my web browser, so that it's not necessary to login clean each time.

**Describe the solution you'd like**
A way to keep session is I'd prefer.

Thanks

**Comment by adw0rd** [comment]
https://adw0rd.github.io/instagrapi/usage-guide/interactions.html
