### ISSUE TITLE
Putting it all together - bot.py

### ISSUE THREAD

**Issue by jaumzaum1** [adw0rd/instagrapi#91]
Please, if anyone created a working bot and was able to use the library correctly to follow/unfollow users, pleeeeeease send the file in here :)
I am having very hard time trying to create a working bot. 
This could help to increase the "examples" folder too.

**Comment by ljcanales** [comment]
Done.
@jaumzaum1 try [https://github.com/adw0rd/instagrapi/blob/master/examples/bot.py](/examples/bot.py)
Commit #213

**Comment by adw0rd** [comment]
Created a repository for the bot https://github.com/adw0rd/instagrapi-bot/issues
