### ISSUE TITLE
user_medias() always returning list of Medias with no location

### ISSUE THREAD

**Issue by Jammy108** [adw0rd/instagrapi#92]
Hey,

When using user_medias(), it always returns a list of Media objects with the location attribute as None. However, if you use media_info() with a photo PK, location is always gotten correctly.

Its not a huge issue as you can just then use media_info but I thought it was worth bringing up.

Thanks for the awesome work!

**Comment by adw0rd** [comment]
@Jammy108 `user_medias` use first `user_medias_gql` (Public Graphql API) which does not contain location data. Use user_medias_v1 instead:

``` python
>>> cl.user_medias_gql(1903424587, amount=1)[0].location
None

>>> cl.user_medias_v1(1903424587, amount=1)[0].location.dict()
{'pk': 271758927,
 'name': 'Уткина Заводь',
 'address': '',
 'lng': 30.511951,
 'lat': 59.863589,
 'external_id': 692052190859331,
 'external_id_source': 'facebook_places'}
```
