### ISSUE TITLE
[BUG] Lamadava SaaS Overcharging 2x 

### ISSUE THREAD

**Issue by peter6C6F6C** [adw0rd/instagrapi#928]
@adw0rd your service is over charging by double. 
![1](https://user-images.githubusercontent.com/34286598/193980224-8d284675-eb2c-4287-9ba3-9ceae1f7457f.png)
![1](https://user-images.githubusercontent.com/34286598/193980239-6043d934-a193-4c28-be2d-28c9f862d951.png)

**Comment by peter6C6F6C** [comment]
@adw0rd I believe it is because it is counting each /v1 request as a request to /v1 and to /v1/user
please fix.

**Comment by adw0rd** [comment]
@peter6C6F6C I will deal with this soon. Thank you!

**Comment by adw0rd** [comment]
@peter6C6F6C fixed it, thank you!
