### ISSUE TITLE
[BUG] bloks_versioning_id need to be change in source

### ISSUE THREAD

**Issue by SaeidB** [adw0rd/instagrapi#976]
hi . 

generating bloks_versioning_id is not correct and i get error in endpoits that contain bloks/...

in few days ago, i tried to create a session.json from my physical phone (using mitm proxy), 

i load that session into instagrapi and it works, but when i see requests in mitm , i notice that bloks_versioning_id is not the same , this means instagrapi generate incorrect bloks_versioning_id,

i also get error from instagram were i pass bloks_versioning_id in data binary 

This need to be changed :
self.bloks_versioning_id = hashlib.sha256(json.dumps(self.device_settings).encode()).hexdigest()

**Comment by SaeidB** [comment]
I've checked some other api and seem that bloks_versioning_id is a constant parameters ?

**Comment by adw0rd** [comment]
@SaeidB submit your PR with improvements

**Comment by 07h** [comment]
@SaeidB which one? "54a609be99b71e070ffecba098354aa8615da5ac4ebc1e44bb7be28e5b244972" ?

**Comment by SaeidB** [comment]
> @SaeidB which one? "54a609be99b71e070ffecba098354aa8615da5ac4ebc1e44bb7be28e5b244972" ?

self.bloks_versioning_id

**Comment by 07h** [comment]
@SaeidB i mean
> I've checked some other api and seem that bloks_versioning_id is a constant parameters ?
constant bloks_versioning_id = "54a609be99b71e070ffecba098354aa8615da5ac4ebc1e44bb7be28e5b244972" ? Or what value did you find?

**Comment by SaeidB** [comment]
> @SaeidB i mean
> > I've checked some other api and seem that bloks_versioning_id is a constant parameters ?
> 
> constant bloks_versioning_id = "54a609be99b71e070ffecba098354aa8615da5ac4ebc1e44bb7be28e5b244972" ? Or what value did you find?


Different version of instagram has different bloks_versioning_id,  i saw in Instagram apk that it was constant, also i saw in another api that its constant, 

Also if its not constant and need to ne generated, current model is not correct
