### ISSUE TITLE
[BUG] Lamadava: InstagramServerError "Instagram did not respond, please try again later"

### ISSUE THREAD

**Issue by gbiz123** [adw0rd/instagrapi#982]
### Compensate with donations ($15 and more) for the time I spent to fix problems or send me your [Pull Request](https://github.com/adw0rd/instagrapi/pulls) with fixes

[![Donate](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/adw0rd)

* Tron TRX/USDT: `TLprxuzHjXPkHYa7ZfTTt165p7Fphwy1Ee`
* Bitcoin: `bc1qmp7538hktvg2gx994hrpkmsmyjc03q29awe9ra`
* Ethereum: `0x0E674815d513d4a00F6a7Cd4A990807aB97cC70D`
* Dogecoin: `DSEXzMBYhBTwhNqzPGxVWFsTqVsTCeDejo`

**Describe the bug**
Instagram server is not responding to Lamadava API when calling a1 user method. Lamadava returns an InstagramServerError in the JSON, but no user data. It was working perfectly until recently. Did Instagram change something?

**To Reproduce**
```
import requests
r = requests.get('https://api.lamadava.com/a1/user?username=***ANY_USERNAME***&access_key=**ACCESS_KEY***)
print(r.json())

>> {'detail': 'Instagram did not respond, please try again later',
>> 'exc_type': 'InstagramServerError'}

```

**Expected behavior**
Receive user JSON data.

**Desktop (please complete the following information):**
 - OS: Gentoo linux
 - Python 3.10
 - Lamadava API

Any help is appreciated, thank you.

**Comment by adw0rd** [comment]
@gbiz123 This is a temporary problem, it occurs mainly during massive blocking of accounts by Instagram, it will stabilize soon. You should try again in a few seconds
