### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Yan19960220** [adw0rd/instagrapi#983]
### Compensate with donations ($15 and more) for the time I spent to fix problems or send me your [Pull Request](https://github.com/adw0rd/instagrapi/pulls) with fixes

[![Donate](https://www.buymeacoffee.com/assets/img/custom_images/yellow_img.png)](https://www.buymeacoffee.com/adw0rd)

* Tron TRX/USDT: `TLprxuzHjXPkHYa7ZfTTt165p7Fphwy1Ee`
* Bitcoin: `bc1qmp7538hktvg2gx994hrpkmsmyjc03q29awe9ra`
* Ethereum: `0x0E674815d513d4a00F6a7Cd4A990807aB97cC70D`
* Dogecoin: `DSEXzMBYhBTwhNqzPGxVWFsTqVsTCeDejo`

**Describe the bug**
The interfaces for user_following and user_followers don't work anymore. 

**To Reproduce**
Provide a piece of code to reproduce the problem.
<img width="594" alt="image" src="https://user-images.githubusercontent.com/59574706/201956889-72c3db5c-617f-4247-8639-b0abc6c7343e.png">

**Traceback**
Show your full traceback so that it is clear where exactly the error occurred.
<img width="734" alt="image" src="https://user-images.githubusercontent.com/59574706/201957025-4c1dc2eb-ce3a-47e9-9cf6-17764ebdfc20.png">

**Expected behavior**
Expected to save all the pk values for the users.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MacOS Ventura 13.0.1]
 - Python version [3.8]
 - instagrapi version [1.9.3]

**Additional context**

**Comment by Yan19960220** [comment]
I have noticed that this bug appears after the I/O: 

Status 429: Too many requests
Ignore 429: Continue login

I don't know if this make any effect on that.

**Comment by adw0rd** [comment]
This Account is Private
```

>>> cl.user_info(8492152853)
User(pk='8492152853', username='michel_chvlr', full_name='Michel Chevalier', is_private=True, ...
```

Try this:

```
>>> cl.user_followers(29817608135, amount=10).keys()
dict_keys(['56680916876', '52517000315', '4922625042', '2356004145', '5900971838', '48859341867', '9986735673', '23146386', '1466128524', '1395918656'])


```

**Comment by ivoidcat** [comment]
I also encountered this problem

**Comment by vasilywang** [comment]
I encountered the same problem, I get login_required (403) error when I call user_following and user_followers

**Comment by claell** [comment]
For the additional problem, see #1050.
